module ICacheMissUnitWayLookupCase019(
    input  logic        clock,
    input  logic        reset,
    input  logic        io_hartId,
    input  logic        io_fencei,
    input  logic        io_flush,
    input  logic        io_wfi_wfiReq,
    input  logic        io_fetchReq_valid,
    input  logic [41:0] io_fetchReq_bits_blkPAddr,
    input  logic [7:0]  io_fetchReq_bits_vSetIdx,
    input  logic        io_prefetchReq_valid,
    input  logic [41:0] io_prefetchReq_bits_blkPAddr,
    input  logic [7:0]  io_prefetchReq_bits_vSetIdx,
    input  logic [1:0]  io_victim_resp_way,
    input  logic        io_memAcquire_ready,
    input  logic        io_memGrant_valid,
    input  logic [3:0]  io_memGrant_bits_opcode,
    input  logic [2:0]  io_memGrant_bits_size,
    input  logic [3:0]  io_memGrant_bits_source,
    input  logic        io_memGrant_bits_denied,
    input  logic [255:0] io_memGrant_bits_data,
    input  logic        io_memGrant_bits_corrupt,
    input  logic        io_wayLookupRead_ready,
    input  logic        io_wayLookupWrite_valid,
    input  logic [1:0][7:0]  io_wayLookupWrite_bits_entry_vSetIdx,
    input  logic [1:0][3:0]  io_wayLookupWrite_bits_entry_waymask,
    input  logic [1:0][31:0] io_wayLookupWrite_bits_entry_maybeRvcMap,
    input  logic [1:0]       io_wayLookupWrite_bits_entry_metaCodes,
    input  logic [35:0]      io_wayLookupWrite_bits_entry_pTag,
    input  logic [1:0]       io_wayLookupWrite_bits_entry_itlbPbmt,
    input  logic [2:0]       io_wayLookupWrite_bits_exceptionEntry_itlbException_value,
    input  logic [54:0]      io_wayLookupWrite_bits_exceptionEntry_gpAddr_addr,
    input  logic             io_wayLookupWrite_bits_exceptionEntry_isForVSnonLeafPTE,
    input  logic             io_wayLookupWrite_bits_ftqIdx_flag,
    input  logic [5:0]       io_wayLookupWrite_bits_ftqIdx_value,
    output logic        io_wfi_wfiSafe,
    output logic        io_fetchReq_ready,
    output logic        io_prefetchReq_ready,
    output logic        io_resp_valid,
    output logic [41:0] io_resp_bits_blkPAddr,
    output logic [7:0]  io_resp_bits_vSetIdx,
    output logic [3:0]  io_resp_bits_waymask,
    output logic [511:0] io_resp_bits_data,
    output logic [31:0] io_resp_bits_maybeRvcMap,
    output logic        io_resp_bits_corrupt,
    output logic        io_resp_bits_denied,
    output logic        io_metaWrite_req_valid,
    output logic [35:0] io_metaWrite_req_bits_entry_meta_phyTag,
    output logic [31:0] io_metaWrite_req_bits_entry_meta_maybeRvcMap,
    output logic        io_metaWrite_req_bits_entry_code,
    output logic [7:0]  io_metaWrite_req_bits_vSetIdx,
    output logic [3:0]  io_metaWrite_req_bits_waymask,
    output logic        io_dataWrite_req_valid,
    output logic [63:0] io_dataWrite_req_bits_entries_0_data,
    output logic        io_dataWrite_req_bits_entries_0_code,
    output logic [63:0] io_dataWrite_req_bits_entries_1_data,
    output logic        io_dataWrite_req_bits_entries_1_code,
    output logic [63:0] io_dataWrite_req_bits_entries_2_data,
    output logic        io_dataWrite_req_bits_entries_2_code,
    output logic [63:0] io_dataWrite_req_bits_entries_3_data,
    output logic        io_dataWrite_req_bits_entries_3_code,
    output logic [63:0] io_dataWrite_req_bits_entries_4_data,
    output logic        io_dataWrite_req_bits_entries_4_code,
    output logic [63:0] io_dataWrite_req_bits_entries_5_data,
    output logic        io_dataWrite_req_bits_entries_5_code,
    output logic [63:0] io_dataWrite_req_bits_entries_6_data,
    output logic        io_dataWrite_req_bits_entries_6_code,
    output logic [63:0] io_dataWrite_req_bits_entries_7_data,
    output logic        io_dataWrite_req_bits_entries_7_code,
    output logic [7:0]  io_dataWrite_req_bits_vSetIdx,
    output logic [3:0]  io_dataWrite_req_bits_waymask,
    output logic        io_victim_req_valid,
    output logic [7:0]  io_victim_req_bits_vSetIdx,
    output logic        io_memAcquire_valid,
    output logic [3:0]  io_memAcquire_bits_source,
    output logic [47:0] io_memAcquire_bits_address,
    output logic [1:0]  io_memAcquire_bits_user_alias,
    output logic        io_refillEvent_valid,
    output logic [63:0] io_refillEvent_addr,
    output logic [63:0] io_refillEvent_data0,
    output logic [63:0] io_refillEvent_data1,
    output logic [63:0] io_refillEvent_data2,
    output logic [63:0] io_refillEvent_data3,
    output logic [63:0] io_refillEvent_data4,
    output logic [63:0] io_refillEvent_data5,
    output logic [63:0] io_refillEvent_data6,
    output logic [63:0] io_refillEvent_data7,
    output logic [7:0]  io_refillEvent_mask,
    output logic [7:0]  io_refillEvent_coreid,
    output logic [7:0]  io_refillEvent_index,
    output logic        io_wayLookupRead_valid,
    output logic [1:0][7:0]  io_wayLookupRead_bits_entry_vSetIdx,
    output logic [1:0][3:0]  io_wayLookupRead_bits_entry_waymask,
    output logic [1:0][31:0] io_wayLookupRead_bits_entry_maybeRvcMap,
    output logic [1:0]       io_wayLookupRead_bits_entry_metaCodes,
    output logic [35:0]      io_wayLookupRead_bits_entry_pTag,
    output logic [1:0]       io_wayLookupRead_bits_entry_itlbPbmt,
    output logic [2:0]       io_wayLookupRead_bits_exceptionEntry_itlbException_value,
    output logic [54:0]      io_wayLookupRead_bits_exceptionEntry_gpAddr_addr,
    output logic             io_wayLookupRead_bits_exceptionEntry_isForVSnonLeafPTE,
    output logic             io_wayLookupWrite_ready,
    output logic             io_wayLookupPerf_empty
);
    logic [600:0] gateway;

    ICacheMissUnit missUnit (
        .clock(clock),
        .reset(reset),
        .io_hartId(io_hartId),
        .io_fencei(io_fencei),
        .io_flush(io_flush),
        .io_wfi_wfiReq(io_wfi_wfiReq),
        .io_wfi_wfiSafe(io_wfi_wfiSafe),
        .io_fetchReq_ready(io_fetchReq_ready),
        .io_fetchReq_valid(io_fetchReq_valid),
        .io_fetchReq_bits_blkPAddr(io_fetchReq_bits_blkPAddr),
        .io_fetchReq_bits_vSetIdx(io_fetchReq_bits_vSetIdx),
        .io_prefetchReq_ready(io_prefetchReq_ready),
        .io_prefetchReq_valid(io_prefetchReq_valid),
        .io_prefetchReq_bits_blkPAddr(io_prefetchReq_bits_blkPAddr),
        .io_prefetchReq_bits_vSetIdx(io_prefetchReq_bits_vSetIdx),
        .io_resp_valid(io_resp_valid),
        .io_resp_bits_blkPAddr(io_resp_bits_blkPAddr),
        .io_resp_bits_vSetIdx(io_resp_bits_vSetIdx),
        .io_resp_bits_waymask(io_resp_bits_waymask),
        .io_resp_bits_data(io_resp_bits_data),
        .io_resp_bits_maybeRvcMap(io_resp_bits_maybeRvcMap),
        .io_resp_bits_corrupt(io_resp_bits_corrupt),
        .io_resp_bits_denied(io_resp_bits_denied),
        .io_metaWrite_req_valid(io_metaWrite_req_valid),
        .io_metaWrite_req_bits_entry_meta_phyTag(io_metaWrite_req_bits_entry_meta_phyTag),
        .io_metaWrite_req_bits_entry_meta_maybeRvcMap(io_metaWrite_req_bits_entry_meta_maybeRvcMap),
        .io_metaWrite_req_bits_entry_code(io_metaWrite_req_bits_entry_code),
        .io_metaWrite_req_bits_vSetIdx(io_metaWrite_req_bits_vSetIdx),
        .io_metaWrite_req_bits_waymask(io_metaWrite_req_bits_waymask),
        .io_dataWrite_req_valid(io_dataWrite_req_valid),
        .io_dataWrite_req_bits_entries_0_data(io_dataWrite_req_bits_entries_0_data),
        .io_dataWrite_req_bits_entries_0_code(io_dataWrite_req_bits_entries_0_code),
        .io_dataWrite_req_bits_entries_1_data(io_dataWrite_req_bits_entries_1_data),
        .io_dataWrite_req_bits_entries_1_code(io_dataWrite_req_bits_entries_1_code),
        .io_dataWrite_req_bits_entries_2_data(io_dataWrite_req_bits_entries_2_data),
        .io_dataWrite_req_bits_entries_2_code(io_dataWrite_req_bits_entries_2_code),
        .io_dataWrite_req_bits_entries_3_data(io_dataWrite_req_bits_entries_3_data),
        .io_dataWrite_req_bits_entries_3_code(io_dataWrite_req_bits_entries_3_code),
        .io_dataWrite_req_bits_entries_4_data(io_dataWrite_req_bits_entries_4_data),
        .io_dataWrite_req_bits_entries_4_code(io_dataWrite_req_bits_entries_4_code),
        .io_dataWrite_req_bits_entries_5_data(io_dataWrite_req_bits_entries_5_data),
        .io_dataWrite_req_bits_entries_5_code(io_dataWrite_req_bits_entries_5_code),
        .io_dataWrite_req_bits_entries_6_data(io_dataWrite_req_bits_entries_6_data),
        .io_dataWrite_req_bits_entries_6_code(io_dataWrite_req_bits_entries_6_code),
        .io_dataWrite_req_bits_entries_7_data(io_dataWrite_req_bits_entries_7_data),
        .io_dataWrite_req_bits_entries_7_code(io_dataWrite_req_bits_entries_7_code),
        .io_dataWrite_req_bits_vSetIdx(io_dataWrite_req_bits_vSetIdx),
        .io_dataWrite_req_bits_waymask(io_dataWrite_req_bits_waymask),
        .io_victim_req_valid(io_victim_req_valid),
        .io_victim_req_bits_vSetIdx(io_victim_req_bits_vSetIdx),
        .io_victim_resp_way(io_victim_resp_way),
        .io_memAcquire_ready(io_memAcquire_ready),
        .io_memAcquire_valid(io_memAcquire_valid),
        .io_memAcquire_bits_source(io_memAcquire_bits_source),
        .io_memAcquire_bits_address(io_memAcquire_bits_address),
        .io_memAcquire_bits_user_alias(io_memAcquire_bits_user_alias),
        .io_memGrant_valid(io_memGrant_valid),
        .io_memGrant_bits_opcode(io_memGrant_bits_opcode),
        .io_memGrant_bits_size(io_memGrant_bits_size),
        .io_memGrant_bits_source(io_memGrant_bits_source),
        .io_memGrant_bits_denied(io_memGrant_bits_denied),
        .io_memGrant_bits_data(io_memGrant_bits_data),
        .io_memGrant_bits_corrupt(io_memGrant_bits_corrupt),
        .gatewayIn_packed_2_bore(gateway)
    );

    assign io_refillEvent_valid = gateway[600];
    assign io_refillEvent_addr = gateway[599:536];
    assign io_refillEvent_data0 = gateway[87:24];
    assign io_refillEvent_data1 = gateway[151:88];
    assign io_refillEvent_data2 = gateway[215:152];
    assign io_refillEvent_data3 = gateway[279:216];
    assign io_refillEvent_data4 = gateway[343:280];
    assign io_refillEvent_data5 = gateway[407:344];
    assign io_refillEvent_data6 = gateway[471:408];
    assign io_refillEvent_data7 = gateway[535:472];
    assign io_refillEvent_mask = gateway[23:16];
    assign io_refillEvent_coreid = gateway[15:8];
    assign io_refillEvent_index = gateway[7:0];

    ICacheWayLookup wayLookup (
        .clock(clock),
        .reset(reset),
        .io_flush(io_flush),
        .io_flushFromBpu_s3_valid(1'b0),
        .io_flushFromBpu_s3_bits_flag(1'b0),
        .io_flushFromBpu_s3_bits_value(6'h0),
        .io_read_ready(io_wayLookupRead_ready),
        .io_read_valid(io_wayLookupRead_valid),
        .io_read_bits_entry_vSetIdx(io_wayLookupRead_bits_entry_vSetIdx),
        .io_read_bits_entry_waymask(io_wayLookupRead_bits_entry_waymask),
        .io_read_bits_entry_maybeRvcMap(io_wayLookupRead_bits_entry_maybeRvcMap),
        .io_read_bits_entry_metaCodes(io_wayLookupRead_bits_entry_metaCodes),
        .io_read_bits_entry_pTag(io_wayLookupRead_bits_entry_pTag),
        .io_read_bits_entry_itlbPbmt(io_wayLookupRead_bits_entry_itlbPbmt),
        .io_read_bits_exceptionEntry_itlbException_value(io_wayLookupRead_bits_exceptionEntry_itlbException_value),
        .io_read_bits_exceptionEntry_gpAddr_addr(io_wayLookupRead_bits_exceptionEntry_gpAddr_addr),
        .io_read_bits_exceptionEntry_isForVSnonLeafPTE(io_wayLookupRead_bits_exceptionEntry_isForVSnonLeafPTE),
        .io_write_ready(io_wayLookupWrite_ready),
        .io_write_valid(io_wayLookupWrite_valid),
        .io_write_bits_entry_vSetIdx(io_wayLookupWrite_bits_entry_vSetIdx),
        .io_write_bits_entry_waymask(io_wayLookupWrite_bits_entry_waymask),
        .io_write_bits_entry_maybeRvcMap(io_wayLookupWrite_bits_entry_maybeRvcMap),
        .io_write_bits_entry_metaCodes(io_wayLookupWrite_bits_entry_metaCodes),
        .io_write_bits_entry_pTag(io_wayLookupWrite_bits_entry_pTag),
        .io_write_bits_entry_itlbPbmt(io_wayLookupWrite_bits_entry_itlbPbmt),
        .io_write_bits_exceptionEntry_itlbException_value(io_wayLookupWrite_bits_exceptionEntry_itlbException_value),
        .io_write_bits_exceptionEntry_gpAddr_addr(io_wayLookupWrite_bits_exceptionEntry_gpAddr_addr),
        .io_write_bits_exceptionEntry_isForVSnonLeafPTE(io_wayLookupWrite_bits_exceptionEntry_isForVSnonLeafPTE),
        .io_write_bits_ftqIdx_flag(io_wayLookupWrite_bits_ftqIdx_flag),
        .io_write_bits_ftqIdx_value(io_wayLookupWrite_bits_ftqIdx_value),
        .io_update_valid(io_resp_valid),
        .io_update_bits_blkPAddr(io_resp_bits_blkPAddr),
        .io_update_bits_vSetIdx(io_resp_bits_vSetIdx),
        .io_update_bits_waymask(io_resp_bits_waymask),
        .io_update_bits_maybeRvcMap(io_resp_bits_maybeRvcMap),
        .io_update_bits_corrupt(io_resp_bits_corrupt),
        .io_perf_empty(io_wayLookupPerf_empty)
    );
endmodule

module xs_bugcase_tb (
    input  logic        clk,
    input  logic        rst_n,
    input  logic        hartId,
    input  logic        fencei,
    input  logic        flush,
    input  logic        wfi_req,
    input  logic        fetch_valid,
    input  logic [41:0] fetch_blk_paddr,
    input  logic [7:0]  fetch_vset,
    input  logic        prefetch_valid,
    input  logic [41:0] prefetch_blk_paddr,
    input  logic [7:0]  prefetch_vset,
    input  logic [1:0]  victim_way,
    input  logic        mem_acquire_ready,
    input  logic        mem_grant_valid,
    input  logic [3:0]  mem_grant_opcode,
    input  logic [2:0]  mem_grant_size,
    input  logic [3:0]  mem_grant_source,
    input  logic        mem_grant_denied,
    input  logic [63:0] mem_grant_data0,
    input  logic [63:0] mem_grant_data1,
    input  logic [63:0] mem_grant_data2,
    input  logic [63:0] mem_grant_data3,
    input  logic        mem_grant_corrupt,
    input  logic        way_read_ready,
    input  logic        way_write_valid,
    input  logic [15:0] way_write_vset,
    input  logic [7:0]  way_write_waymask,
    input  logic [63:0] way_write_maybe_rvc,
    input  logic [1:0]  way_write_meta_codes,
    input  logic [35:0] way_write_ptag,
    input  logic [1:0]  way_write_itlb_pbmt,
    input  logic [2:0]  way_write_excp_value,
    input  logic [54:0] way_write_gpaddr,
    input  logic        way_write_is_vs_nonleaf,
    input  logic        way_write_ftq_flag,
    input  logic [5:0]  way_write_ftq_value,
    output logic        wfi_safe,
    output logic        fetch_ready,
    output logic        prefetch_ready,
    output logic        miss_resp_valid,
    output logic [41:0] miss_resp_blk_paddr,
    output logic [7:0]  miss_resp_vset,
    output logic [3:0]  miss_resp_waymask,
    output logic [63:0] miss_resp_data0,
    output logic [63:0] miss_resp_data1,
    output logic [63:0] miss_resp_data2,
    output logic [63:0] miss_resp_data3,
    output logic [63:0] miss_resp_data4,
    output logic [63:0] miss_resp_data5,
    output logic [63:0] miss_resp_data6,
    output logic [63:0] miss_resp_data7,
    output logic [31:0] miss_resp_maybe_rvc,
    output logic        miss_resp_corrupt,
    output logic        miss_resp_denied,
    output logic        meta_write_valid,
    output logic [35:0] meta_write_ptag,
    output logic [31:0] meta_write_maybe_rvc,
    output logic        meta_write_code,
    output logic [7:0]  meta_write_vset,
    output logic [3:0]  meta_write_waymask,
    output logic        data_write_valid,
    output logic [7:0]  data_write_vset,
    output logic [3:0]  data_write_waymask,
    output logic [63:0] data_write_data0,
    output logic [63:0] data_write_data1,
    output logic [63:0] data_write_data2,
    output logic [63:0] data_write_data3,
    output logic [63:0] data_write_data4,
    output logic [63:0] data_write_data5,
    output logic [63:0] data_write_data6,
    output logic [63:0] data_write_data7,
    output logic        victim_req_valid,
    output logic [7:0]  victim_req_vset,
    output logic        mem_acquire_valid,
    output logic [3:0]  mem_acquire_source,
    output logic [47:0] mem_acquire_address,
    output logic [1:0]  mem_acquire_alias,
    output logic        refill_valid,
    output logic [63:0] refill_addr,
    output logic [63:0] refill_data0,
    output logic [63:0] refill_data1,
    output logic [63:0] refill_data2,
    output logic [63:0] refill_data3,
    output logic [63:0] refill_data4,
    output logic [63:0] refill_data5,
    output logic [63:0] refill_data6,
    output logic [63:0] refill_data7,
    output logic [7:0]  refill_mask,
    output logic [7:0]  refill_coreid,
    output logic [7:0]  refill_index,
    output logic        way_read_valid,
    output logic [15:0] way_read_vset,
    output logic [7:0]  way_read_waymask,
    output logic [63:0] way_read_maybe_rvc,
    output logic [1:0]  way_read_meta_codes,
    output logic [35:0] way_read_ptag,
    output logic [1:0]  way_read_itlb_pbmt,
    output logic [2:0]  way_read_excp_value,
    output logic [54:0] way_read_gpaddr,
    output logic        way_read_is_vs_nonleaf,
    output logic        way_write_ready,
    output logic        way_perf_empty
);
    logic [255:0] mem_grant_data;
    logic [511:0] miss_resp_data;
    logic [1:0][7:0] way_write_vset_vec;
    logic [1:0][3:0] way_write_waymask_vec;
    logic [1:0][31:0] way_write_maybe_rvc_vec;
    logic [1:0][7:0] way_read_vset_vec;
    logic [1:0][3:0] way_read_waymask_vec;
    logic [1:0][31:0] way_read_maybe_rvc_vec;
    logic [1:0] way_read_meta_codes_vec;

    assign mem_grant_data = {mem_grant_data3, mem_grant_data2, mem_grant_data1, mem_grant_data0};
    assign way_write_vset_vec = {way_write_vset[15:8], way_write_vset[7:0]};
    assign way_write_waymask_vec = {way_write_waymask[7:4], way_write_waymask[3:0]};
    assign way_write_maybe_rvc_vec = {way_write_maybe_rvc[63:32], way_write_maybe_rvc[31:0]};
    assign way_read_vset = {way_read_vset_vec[1], way_read_vset_vec[0]};
    assign way_read_waymask = {way_read_waymask_vec[1], way_read_waymask_vec[0]};
    assign way_read_maybe_rvc = {way_read_maybe_rvc_vec[1], way_read_maybe_rvc_vec[0]};
    assign way_read_meta_codes = way_read_meta_codes_vec;
    assign miss_resp_data0 = miss_resp_data[63:0];
    assign miss_resp_data1 = miss_resp_data[127:64];
    assign miss_resp_data2 = miss_resp_data[191:128];
    assign miss_resp_data3 = miss_resp_data[255:192];
    assign miss_resp_data4 = miss_resp_data[319:256];
    assign miss_resp_data5 = miss_resp_data[383:320];
    assign miss_resp_data6 = miss_resp_data[447:384];
    assign miss_resp_data7 = miss_resp_data[511:448];

    ICacheMissUnitWayLookupCase019 dut (
        .clock(clk),
        .reset(!rst_n),
        .io_hartId(hartId),
        .io_fencei(fencei),
        .io_flush(flush),
        .io_wfi_wfiReq(wfi_req),
        .io_fetchReq_valid(fetch_valid),
        .io_fetchReq_bits_blkPAddr(fetch_blk_paddr),
        .io_fetchReq_bits_vSetIdx(fetch_vset),
        .io_prefetchReq_valid(prefetch_valid),
        .io_prefetchReq_bits_blkPAddr(prefetch_blk_paddr),
        .io_prefetchReq_bits_vSetIdx(prefetch_vset),
        .io_victim_resp_way(victim_way),
        .io_memAcquire_ready(mem_acquire_ready),
        .io_memGrant_valid(mem_grant_valid),
        .io_memGrant_bits_opcode(mem_grant_opcode),
        .io_memGrant_bits_size(mem_grant_size),
        .io_memGrant_bits_source(mem_grant_source),
        .io_memGrant_bits_denied(mem_grant_denied),
        .io_memGrant_bits_data(mem_grant_data),
        .io_memGrant_bits_corrupt(mem_grant_corrupt),
        .io_wayLookupRead_ready(way_read_ready),
        .io_wayLookupWrite_valid(way_write_valid),
        .io_wayLookupWrite_bits_entry_vSetIdx(way_write_vset_vec),
        .io_wayLookupWrite_bits_entry_waymask(way_write_waymask_vec),
        .io_wayLookupWrite_bits_entry_maybeRvcMap(way_write_maybe_rvc_vec),
        .io_wayLookupWrite_bits_entry_metaCodes(way_write_meta_codes),
        .io_wayLookupWrite_bits_entry_pTag(way_write_ptag),
        .io_wayLookupWrite_bits_entry_itlbPbmt(way_write_itlb_pbmt),
        .io_wayLookupWrite_bits_exceptionEntry_itlbException_value(way_write_excp_value),
        .io_wayLookupWrite_bits_exceptionEntry_gpAddr_addr(way_write_gpaddr),
        .io_wayLookupWrite_bits_exceptionEntry_isForVSnonLeafPTE(way_write_is_vs_nonleaf),
        .io_wayLookupWrite_bits_ftqIdx_flag(way_write_ftq_flag),
        .io_wayLookupWrite_bits_ftqIdx_value(way_write_ftq_value),
        .io_wfi_wfiSafe(wfi_safe),
        .io_fetchReq_ready(fetch_ready),
        .io_prefetchReq_ready(prefetch_ready),
        .io_resp_valid(miss_resp_valid),
        .io_resp_bits_blkPAddr(miss_resp_blk_paddr),
        .io_resp_bits_vSetIdx(miss_resp_vset),
        .io_resp_bits_waymask(miss_resp_waymask),
        .io_resp_bits_data(miss_resp_data),
        .io_resp_bits_maybeRvcMap(miss_resp_maybe_rvc),
        .io_resp_bits_corrupt(miss_resp_corrupt),
        .io_resp_bits_denied(miss_resp_denied),
        .io_metaWrite_req_valid(meta_write_valid),
        .io_metaWrite_req_bits_entry_meta_phyTag(meta_write_ptag),
        .io_metaWrite_req_bits_entry_meta_maybeRvcMap(meta_write_maybe_rvc),
        .io_metaWrite_req_bits_entry_code(meta_write_code),
        .io_metaWrite_req_bits_vSetIdx(meta_write_vset),
        .io_metaWrite_req_bits_waymask(meta_write_waymask),
        .io_dataWrite_req_valid(data_write_valid),
        .io_dataWrite_req_bits_entries_0_data(data_write_data0),
        .io_dataWrite_req_bits_entries_0_code(),
        .io_dataWrite_req_bits_entries_1_data(data_write_data1),
        .io_dataWrite_req_bits_entries_1_code(),
        .io_dataWrite_req_bits_entries_2_data(data_write_data2),
        .io_dataWrite_req_bits_entries_2_code(),
        .io_dataWrite_req_bits_entries_3_data(data_write_data3),
        .io_dataWrite_req_bits_entries_3_code(),
        .io_dataWrite_req_bits_entries_4_data(data_write_data4),
        .io_dataWrite_req_bits_entries_4_code(),
        .io_dataWrite_req_bits_entries_5_data(data_write_data5),
        .io_dataWrite_req_bits_entries_5_code(),
        .io_dataWrite_req_bits_entries_6_data(data_write_data6),
        .io_dataWrite_req_bits_entries_6_code(),
        .io_dataWrite_req_bits_entries_7_data(data_write_data7),
        .io_dataWrite_req_bits_entries_7_code(),
        .io_dataWrite_req_bits_vSetIdx(data_write_vset),
        .io_dataWrite_req_bits_waymask(data_write_waymask),
        .io_victim_req_valid(victim_req_valid),
        .io_victim_req_bits_vSetIdx(victim_req_vset),
        .io_memAcquire_valid(mem_acquire_valid),
        .io_memAcquire_bits_source(mem_acquire_source),
        .io_memAcquire_bits_address(mem_acquire_address),
        .io_memAcquire_bits_user_alias(mem_acquire_alias),
        .io_refillEvent_valid(refill_valid),
        .io_refillEvent_addr(refill_addr),
        .io_refillEvent_data0(refill_data0),
        .io_refillEvent_data1(refill_data1),
        .io_refillEvent_data2(refill_data2),
        .io_refillEvent_data3(refill_data3),
        .io_refillEvent_data4(refill_data4),
        .io_refillEvent_data5(refill_data5),
        .io_refillEvent_data6(refill_data6),
        .io_refillEvent_data7(refill_data7),
        .io_refillEvent_mask(refill_mask),
        .io_refillEvent_coreid(refill_coreid),
        .io_refillEvent_index(refill_index),
        .io_wayLookupRead_valid(way_read_valid),
        .io_wayLookupRead_bits_entry_vSetIdx(way_read_vset_vec),
        .io_wayLookupRead_bits_entry_waymask(way_read_waymask_vec),
        .io_wayLookupRead_bits_entry_maybeRvcMap(way_read_maybe_rvc_vec),
        .io_wayLookupRead_bits_entry_metaCodes(way_read_meta_codes_vec),
        .io_wayLookupRead_bits_entry_pTag(way_read_ptag),
        .io_wayLookupRead_bits_entry_itlbPbmt(way_read_itlb_pbmt),
        .io_wayLookupRead_bits_exceptionEntry_itlbException_value(way_read_excp_value),
        .io_wayLookupRead_bits_exceptionEntry_gpAddr_addr(way_read_gpaddr),
        .io_wayLookupRead_bits_exceptionEntry_isForVSnonLeafPTE(way_read_is_vs_nonleaf),
        .io_wayLookupWrite_ready(way_write_ready),
        .io_wayLookupPerf_empty(way_perf_empty)
    );
endmodule
