module ICacheMainPipeWayLookupCase018(
    input  logic        clock,
    input  logic        reset,
    input  logic [5:0]  io_hartId,
    input  logic        io_dataRead_req_ready,
    input              io_missReq_ready,
    input              io_missResp_valid,
    input  [41:0]      io_missResp_bits_blkPAddr,
    input  [511:0]     io_missResp_bits_data,
    input  [31:0]      io_missResp_bits_maybeRvcMap,
    input              io_missResp_bits_corrupt,
    input              io_missResp_bits_denied,
    input              io_eccEnable,
    input              io_req_valid,
    input  [48:0]      io_req_bits_startVAddr_addr,
    input  [48:0]      io_req_bits_nextCachelineVAddr_addr,
    input              io_req_bits_ftqIdx_flag,
    input  [5:0]       io_req_bits_ftqIdx_value,
    input  [4:0]       io_req_bits_takenCfiOffset,
    input              io_req_bits_isBackendException,
    input              io_flush,
    input              io_flushFromBpu_s3_valid,
    input              io_flushFromBpu_s3_bits_flag,
    input  [5:0]       io_flushFromBpu_s3_bits_value,
    input              io_pmp_resp_instr,
    input              io_pmp_resp_mmio,
    input              io_respStall,
    input              io_wayLookupWrite_valid,
    input  [1:0][7:0]  io_wayLookupWrite_bits_entry_vSetIdx,
    input  [1:0][3:0]  io_wayLookupWrite_bits_entry_waymask,
    input  [1:0][31:0] io_wayLookupWrite_bits_entry_maybeRvcMap,
    input  [1:0]       io_wayLookupWrite_bits_entry_metaCodes,
    input  [35:0]      io_wayLookupWrite_bits_entry_pTag,
    input  [1:0]       io_wayLookupWrite_bits_entry_itlbPbmt,
    input  [2:0]       io_wayLookupWrite_bits_exceptionEntry_itlbException_value,
    input  [54:0]      io_wayLookupWrite_bits_exceptionEntry_gpAddr_addr,
    input              io_wayLookupWrite_bits_exceptionEntry_isForVSnonLeafPTE,
    input              io_wayLookupWrite_bits_ftqIdx_flag,
    input  [5:0]       io_wayLookupWrite_bits_ftqIdx_value,
    input              io_wayLookupUpdate_valid,
    input  [41:0]      io_wayLookupUpdate_bits_blkPAddr,
    input  [7:0]       io_wayLookupUpdate_bits_vSetIdx,
    input  [3:0]       io_wayLookupUpdate_bits_waymask,
    input  [31:0]      io_wayLookupUpdate_bits_maybeRvcMap,
    input              io_wayLookupUpdate_bits_corrupt,
    output             io_dataRead_req_valid,
    output [1:0][7:0]  io_dataRead_req_bits_vSetIdx,
    output             io_dataRead_req_bits_isDoubleLine,
    output [1:0][3:0]  io_dataRead_req_bits_waymask,
    output [5:0]       io_dataRead_req_bits_blkOffset,
    output [5:0]       io_dataRead_req_bits_blkEndOffset,
    output             io_replacerTouch_req_0_valid,
    output [7:0]       io_replacerTouch_req_0_bits_vSetIdx,
    output [1:0]       io_replacerTouch_req_0_bits_way,
    output             io_replacerTouch_req_1_valid,
    output [7:0]       io_replacerTouch_req_1_bits_vSetIdx,
    output [1:0]       io_replacerTouch_req_1_bits_way,
    output             io_wayLookupRead_ready,
    output             io_wayLookupRead_valid,
    output             io_wayLookupWrite_ready,
    output             io_wayLookupPerf_empty,
    output             io_missReq_valid,
    output [41:0]      io_missReq_bits_blkPAddr,
    output [7:0]       io_missReq_bits_vSetIdx,
    output             io_req_ready,
    output [47:0]      io_pmp_req_bits_addr,
    output             io_resp_valid,
    output             io_resp_bits_doubleline,
    output [48:0]      io_resp_bits_vAddr_0_addr,
    output [511:0]     io_resp_bits_data,
    output [31:0]      io_resp_bits_maybeRvcMap,
    output [46:0]      io_resp_bits_pAddr_addr,
    output [2:0]       io_resp_bits_exception_value,
    output             io_resp_bits_pmpMmio,
    output [1:0]       io_resp_bits_itlbPbmt,
    output             io_resp_bits_isBackendException,
    output [54:0]      io_resp_bits_gpAddr_addr,
    output             io_resp_bits_isForVSnonLeafPTE,
    output             io_errors_0_valid,
    output [47:0]      io_errors_0_bits_paddr,
    output             io_errors_0_bits_report_to_beu,
    output             io_errors_1_valid,
    output [47:0]      io_errors_1_bits_paddr,
    output             io_errors_1_bits_report_to_beu,
    output [1:0]       io_perf_rawHits,
    output             io_perf_pendingMiss
);
    logic [7:0][63:0] data_resp_datas;
    logic [7:0]       data_resp_codes;
    logic [600:0]     gateway0;
    logic [600:0]     gateway1;
    logic [1:0][7:0]  way_read_vSetIdx;
    logic [1:0][3:0]  way_read_waymask;
    logic [1:0][31:0] way_read_maybeRvcMap;
    logic [1:0]       way_read_metaCodes;
    logic [35:0]      way_read_pTag;
    logic [1:0]       way_read_itlbPbmt;
    logic [2:0]       way_read_exception_value;
    logic [54:0]      way_read_gpAddr_addr;
    logic             way_read_isForVSnonLeafPTE;

    assign data_resp_datas = '{
        (64'h0101010101010101 ^ {56'h0, io_req_bits_startVAddr_addr[12:5]}),
        (64'h1111111111111111 ^ {15'h0, io_req_bits_startVAddr_addr}),
        (64'h2222222222222222 ^ {15'h0, io_req_bits_nextCachelineVAddr_addr}),
        (64'h3333333333333333 ^ {58'h0, io_req_bits_ftqIdx_value}),
        (64'h4444444444444444 ^ {59'h0, io_req_bits_takenCfiOffset}),
        (64'h5555555555555555 ^ {56'h0, way_read_vSetIdx[0]}),
        (64'h6666666666666666 ^ {56'h0, way_read_vSetIdx[1]}),
        (64'h7777777777777777 ^ {28'h0, way_read_pTag})
    };
    assign data_resp_codes = '0;

    ICacheMainPipe mainPipe (
        .clock(clock),
        .reset(reset),
        .io_hartId(io_hartId),
        .io_dataRead_req_ready(io_dataRead_req_ready),
        .io_dataRead_req_valid(io_dataRead_req_valid),
        .io_dataRead_req_bits_vSetIdx(io_dataRead_req_bits_vSetIdx),
        .io_dataRead_req_bits_isDoubleLine(io_dataRead_req_bits_isDoubleLine),
        .io_dataRead_req_bits_waymask(io_dataRead_req_bits_waymask),
        .io_dataRead_req_bits_blkOffset(io_dataRead_req_bits_blkOffset),
        .io_dataRead_req_bits_blkEndOffset(io_dataRead_req_bits_blkEndOffset),
        .io_dataRead_resp_datas(data_resp_datas),
        .io_dataRead_resp_codes(data_resp_codes),
        .io_replacerTouch_req_0_valid(io_replacerTouch_req_0_valid),
        .io_replacerTouch_req_0_bits_vSetIdx(io_replacerTouch_req_0_bits_vSetIdx),
        .io_replacerTouch_req_0_bits_way(io_replacerTouch_req_0_bits_way),
        .io_replacerTouch_req_1_valid(io_replacerTouch_req_1_valid),
        .io_replacerTouch_req_1_bits_vSetIdx(io_replacerTouch_req_1_bits_vSetIdx),
        .io_replacerTouch_req_1_bits_way(io_replacerTouch_req_1_bits_way),
        .io_wayLookupRead_ready(io_wayLookupRead_ready),
        .io_wayLookupRead_valid(io_wayLookupRead_valid),
        .io_wayLookupRead_bits_entry_vSetIdx(way_read_vSetIdx),
        .io_wayLookupRead_bits_entry_waymask(way_read_waymask),
        .io_wayLookupRead_bits_entry_maybeRvcMap(way_read_maybeRvcMap),
        .io_wayLookupRead_bits_entry_metaCodes(way_read_metaCodes),
        .io_wayLookupRead_bits_entry_pTag(way_read_pTag),
        .io_wayLookupRead_bits_entry_itlbPbmt(way_read_itlbPbmt),
        .io_wayLookupRead_bits_exceptionEntry_itlbException_value(way_read_exception_value),
        .io_wayLookupRead_bits_exceptionEntry_gpAddr_addr(way_read_gpAddr_addr),
        .io_wayLookupRead_bits_exceptionEntry_isForVSnonLeafPTE(way_read_isForVSnonLeafPTE),
        .io_missReq_ready(io_missReq_ready),
        .io_missReq_valid(io_missReq_valid),
        .io_missReq_bits_blkPAddr(io_missReq_bits_blkPAddr),
        .io_missReq_bits_vSetIdx(io_missReq_bits_vSetIdx),
        .io_missResp_valid(io_missResp_valid),
        .io_missResp_bits_blkPAddr(io_missResp_bits_blkPAddr),
        .io_missResp_bits_vSetIdx(io_missResp_bits_blkPAddr[13:6]),
        .io_missResp_bits_data(io_missResp_bits_data),
        .io_missResp_bits_maybeRvcMap(io_missResp_bits_maybeRvcMap),
        .io_missResp_bits_corrupt(io_missResp_bits_corrupt),
        .io_missResp_bits_denied(io_missResp_bits_denied),
        .io_eccEnable(io_eccEnable),
        .io_req_ready(io_req_ready),
        .io_req_valid(io_req_valid),
        .io_req_bits_startVAddr_addr(io_req_bits_startVAddr_addr),
        .io_req_bits_nextCachelineVAddr_addr(io_req_bits_nextCachelineVAddr_addr),
        .io_req_bits_ftqIdx_flag(io_req_bits_ftqIdx_flag),
        .io_req_bits_ftqIdx_value(io_req_bits_ftqIdx_value),
        .io_req_bits_takenCfiOffset(io_req_bits_takenCfiOffset),
        .io_req_bits_isBackendException(io_req_bits_isBackendException),
        .io_flush(io_flush),
        .io_flushFromBpu_s3_valid(io_flushFromBpu_s3_valid),
        .io_flushFromBpu_s3_bits_flag(io_flushFromBpu_s3_bits_flag),
        .io_flushFromBpu_s3_bits_value(io_flushFromBpu_s3_bits_value),
        .io_pmp_req_bits_addr(io_pmp_req_bits_addr),
        .io_pmp_resp_instr(io_pmp_resp_instr),
        .io_pmp_resp_mmio(io_pmp_resp_mmio),
        .io_resp_valid(io_resp_valid),
        .io_resp_bits_doubleline(io_resp_bits_doubleline),
        .io_resp_bits_vAddr_0_addr(io_resp_bits_vAddr_0_addr),
        .io_resp_bits_data(io_resp_bits_data),
        .io_resp_bits_maybeRvcMap(io_resp_bits_maybeRvcMap),
        .io_resp_bits_pAddr_addr(io_resp_bits_pAddr_addr),
        .io_resp_bits_exception_value(io_resp_bits_exception_value),
        .io_resp_bits_pmpMmio(io_resp_bits_pmpMmio),
        .io_resp_bits_itlbPbmt(io_resp_bits_itlbPbmt),
        .io_resp_bits_isBackendException(io_resp_bits_isBackendException),
        .io_resp_bits_gpAddr_addr(io_resp_bits_gpAddr_addr),
        .io_resp_bits_isForVSnonLeafPTE(io_resp_bits_isForVSnonLeafPTE),
        .io_respStall(io_respStall),
        .io_errors_0_valid(io_errors_0_valid),
        .io_errors_0_bits_paddr(io_errors_0_bits_paddr),
        .io_errors_0_bits_report_to_beu(io_errors_0_bits_report_to_beu),
        .io_errors_1_valid(io_errors_1_valid),
        .io_errors_1_bits_paddr(io_errors_1_bits_paddr),
        .io_errors_1_bits_report_to_beu(io_errors_1_bits_report_to_beu),
        .io_perf_rawHits(io_perf_rawHits),
        .io_perf_pendingMiss(io_perf_pendingMiss),
        .gatewayIn_packed_0_bore(gateway0),
        .gatewayIn_packed_1_bore(gateway1)
    );

    ICacheWayLookup wayLookup (
        .clock(clock),
        .reset(reset),
        .io_flush(io_flush),
        .io_flushFromBpu_s3_valid(io_flushFromBpu_s3_valid),
        .io_flushFromBpu_s3_bits_flag(io_flushFromBpu_s3_bits_flag),
        .io_flushFromBpu_s3_bits_value(io_flushFromBpu_s3_bits_value),
        .io_read_ready(io_wayLookupRead_ready),
        .io_read_valid(io_wayLookupRead_valid),
        .io_read_bits_entry_vSetIdx(way_read_vSetIdx),
        .io_read_bits_entry_waymask(way_read_waymask),
        .io_read_bits_entry_maybeRvcMap(way_read_maybeRvcMap),
        .io_read_bits_entry_metaCodes(way_read_metaCodes),
        .io_read_bits_entry_pTag(way_read_pTag),
        .io_read_bits_entry_itlbPbmt(way_read_itlbPbmt),
        .io_read_bits_exceptionEntry_itlbException_value(way_read_exception_value),
        .io_read_bits_exceptionEntry_gpAddr_addr(way_read_gpAddr_addr),
        .io_read_bits_exceptionEntry_isForVSnonLeafPTE(way_read_isForVSnonLeafPTE),
        .io_write_ready(io_wayLookupWrite_ready),
        .io_write_valid(io_wayLookupWrite_valid),
        .io_write_bits_entry_vSetIdx(io_wayLookupWrite_bits_entry_vSetIdx),
        .io_write_bits_entry_waymask(io_wayLookupWrite_bits_entry_waymask),
        .io_write_bits_entry_maybeRvcMap(io_wayLookupWrite_bits_entry_maybeRvcMap),
        .io_write_bits_entry_metaCodes(io_wayLookupWrite_bits_entry_metaCodes),
        .io_write_bits_entry_pTag(io_wayLookupWrite_bits_entry_pTag),
        .io_write_bits_entry_itlbPbmt(io_wayLookupWrite_bits_entry_itlbPbmt),
        .io_write_bits_exceptionEntry_itlbException_value(io_wayLookupWrite_bits_exceptionEntry_itlbException_value),
        .io_write_bits_exceptionEntry_gpAddr_addr(io_wayLookupWrite_bits_exceptionEntry_gpAddr_addr),
        .io_write_bits_exceptionEntry_isForVSnonLeafPTE(io_wayLookupWrite_bits_exceptionEntry_isForVSnonLeafPTE),
        .io_write_bits_ftqIdx_flag(io_wayLookupWrite_bits_ftqIdx_flag),
        .io_write_bits_ftqIdx_value(io_wayLookupWrite_bits_ftqIdx_value),
        .io_update_valid(io_wayLookupUpdate_valid),
        .io_update_bits_blkPAddr(io_wayLookupUpdate_bits_blkPAddr),
        .io_update_bits_vSetIdx(io_wayLookupUpdate_bits_vSetIdx),
        .io_update_bits_waymask(io_wayLookupUpdate_bits_waymask),
        .io_update_bits_maybeRvcMap(io_wayLookupUpdate_bits_maybeRvcMap),
        .io_update_bits_corrupt(io_wayLookupUpdate_bits_corrupt),
        .io_perf_empty(io_wayLookupPerf_empty)
    );
endmodule

module xs_bugcase_tb (
    input  logic        clk,
    input  logic        rst_n,
    input  logic [5:0]  hartId,
    input  logic        data_ready,
    input  logic        miss_ready,
    input  logic        miss_resp_valid,
    input  logic [41:0] miss_resp_blk_paddr,
    input  logic [63:0] miss_resp_data0,
    input  logic [63:0] miss_resp_data1,
    input  logic [63:0] miss_resp_data2,
    input  logic [63:0] miss_resp_data3,
    input  logic [63:0] miss_resp_data4,
    input  logic [63:0] miss_resp_data5,
    input  logic [63:0] miss_resp_data6,
    input  logic [63:0] miss_resp_data7,
    input  logic [31:0] miss_resp_maybe_rvc,
    input  logic        miss_resp_corrupt,
    input  logic        miss_resp_denied,
    input  logic        ecc_enable,
    input  logic        req_valid,
    input  logic [48:0] req_start_vaddr,
    input  logic [48:0] req_next_vaddr,
    input  logic        req_ftq_flag,
    input  logic [5:0]  req_ftq_value,
    input  logic [4:0]  req_taken_cfi_offset,
    input  logic        req_backend_exception,
    input  logic        flush,
    input  logic        bpu_valid,
    input  logic        bpu_flag,
    input  logic [5:0]  bpu_value,
    input  logic        pmp_instr,
    input  logic        pmp_mmio,
    input  logic        resp_stall,
    input  logic        write_valid,
    input  logic [15:0] write_vset,
    input  logic [7:0]  write_waymask,
    input  logic [63:0] write_maybe_rvc,
    input  logic [1:0]  write_meta_codes,
    input  logic [35:0] write_ptag,
    input  logic [1:0]  write_itlb_pbmt,
    input  logic [2:0]  write_excp_value,
    input  logic [54:0] write_gpaddr,
    input  logic        write_is_vs_nonleaf,
    input  logic        write_ftq_flag,
    input  logic [5:0]  write_ftq_value,
    input  logic        update_valid,
    input  logic [41:0] update_blk_paddr,
    input  logic [7:0]  update_vset,
    input  logic [3:0]  update_waymask,
    input  logic [31:0] update_maybe_rvc,
    input  logic        update_corrupt,
    output logic        data_req_valid,
    output logic [15:0] data_req_vset,
    output logic        data_req_doubleline,
    output logic [7:0]  data_req_waymask,
    output logic [5:0]  data_req_blk_offset,
    output logic [5:0]  data_req_blk_end_offset,
    output logic        touch0_valid,
    output logic [7:0]  touch0_vset,
    output logic [1:0]  touch0_way,
    output logic        touch1_valid,
    output logic [7:0]  touch1_vset,
    output logic [1:0]  touch1_way,
    output logic        way_read_ready,
    output logic        way_read_valid,
    output logic        way_write_ready,
    output logic        way_perf_empty,
    output logic        miss_req_valid,
    output logic [41:0] miss_req_blk_paddr,
    output logic [7:0]  miss_req_vset,
    output logic        req_ready,
    output logic [47:0] pmp_req_addr,
    output logic        resp_valid,
    output logic        resp_doubleline,
    output logic [48:0] resp_vaddr,
    output logic [63:0] resp_data0,
    output logic [63:0] resp_data1,
    output logic [63:0] resp_data2,
    output logic [63:0] resp_data3,
    output logic [63:0] resp_data4,
    output logic [63:0] resp_data5,
    output logic [63:0] resp_data6,
    output logic [63:0] resp_data7,
    output logic [31:0] resp_maybe_rvc,
    output logic [46:0] resp_paddr,
    output logic [2:0]  resp_exception,
    output logic        resp_pmp_mmio,
    output logic [1:0]  resp_itlb_pbmt,
    output logic        resp_backend_exception,
    output logic [54:0] resp_gpaddr,
    output logic        resp_is_vs_nonleaf,
    output logic        error0_valid,
    output logic [47:0] error0_paddr,
    output logic        error0_report,
    output logic        error1_valid,
    output logic [47:0] error1_paddr,
    output logic        error1_report,
    output logic [1:0]  perf_raw_hits,
    output logic        perf_pending_miss
);
    logic [1:0][7:0]  write_vset_vec;
    logic [1:0][3:0]  write_waymask_vec;
    logic [1:0][31:0] write_maybe_rvc_vec;
    logic [1:0][7:0]  data_req_vset_vec;
    logic [1:0][3:0]  data_req_waymask_vec;
    logic [511:0]     miss_resp_data;
    logic [511:0]     resp_data;

    assign write_vset_vec = {write_vset[15:8], write_vset[7:0]};
    assign write_waymask_vec = {write_waymask[7:4], write_waymask[3:0]};
    assign write_maybe_rvc_vec = {write_maybe_rvc[63:32], write_maybe_rvc[31:0]};
    assign data_req_vset = {data_req_vset_vec[1], data_req_vset_vec[0]};
    assign data_req_waymask = {data_req_waymask_vec[1], data_req_waymask_vec[0]};
    assign miss_resp_data =
        {miss_resp_data7, miss_resp_data6, miss_resp_data5, miss_resp_data4,
         miss_resp_data3, miss_resp_data2, miss_resp_data1, miss_resp_data0};

    ICacheMainPipeWayLookupCase018 dut (
        .clock(clk),
        .reset(!rst_n),
        .io_hartId(hartId),
        .io_dataRead_req_ready(data_ready),
        .io_missReq_ready(miss_ready),
        .io_missResp_valid(miss_resp_valid),
        .io_missResp_bits_blkPAddr(miss_resp_blk_paddr),
        .io_missResp_bits_data(miss_resp_data),
        .io_missResp_bits_maybeRvcMap(miss_resp_maybe_rvc),
        .io_missResp_bits_corrupt(miss_resp_corrupt),
        .io_missResp_bits_denied(miss_resp_denied),
        .io_eccEnable(ecc_enable),
        .io_req_valid(req_valid),
        .io_req_bits_startVAddr_addr(req_start_vaddr),
        .io_req_bits_nextCachelineVAddr_addr(req_next_vaddr),
        .io_req_bits_ftqIdx_flag(req_ftq_flag),
        .io_req_bits_ftqIdx_value(req_ftq_value),
        .io_req_bits_takenCfiOffset(req_taken_cfi_offset),
        .io_req_bits_isBackendException(req_backend_exception),
        .io_flush(flush),
        .io_flushFromBpu_s3_valid(bpu_valid),
        .io_flushFromBpu_s3_bits_flag(bpu_flag),
        .io_flushFromBpu_s3_bits_value(bpu_value),
        .io_pmp_resp_instr(pmp_instr),
        .io_pmp_resp_mmio(pmp_mmio),
        .io_respStall(resp_stall),
        .io_wayLookupWrite_valid(write_valid),
        .io_wayLookupWrite_bits_entry_vSetIdx(write_vset_vec),
        .io_wayLookupWrite_bits_entry_waymask(write_waymask_vec),
        .io_wayLookupWrite_bits_entry_maybeRvcMap(write_maybe_rvc_vec),
        .io_wayLookupWrite_bits_entry_metaCodes(write_meta_codes),
        .io_wayLookupWrite_bits_entry_pTag(write_ptag),
        .io_wayLookupWrite_bits_entry_itlbPbmt(write_itlb_pbmt),
        .io_wayLookupWrite_bits_exceptionEntry_itlbException_value(write_excp_value),
        .io_wayLookupWrite_bits_exceptionEntry_gpAddr_addr(write_gpaddr),
        .io_wayLookupWrite_bits_exceptionEntry_isForVSnonLeafPTE(write_is_vs_nonleaf),
        .io_wayLookupWrite_bits_ftqIdx_flag(write_ftq_flag),
        .io_wayLookupWrite_bits_ftqIdx_value(write_ftq_value),
        .io_wayLookupUpdate_valid(update_valid),
        .io_wayLookupUpdate_bits_blkPAddr(update_blk_paddr),
        .io_wayLookupUpdate_bits_vSetIdx(update_vset),
        .io_wayLookupUpdate_bits_waymask(update_waymask),
        .io_wayLookupUpdate_bits_maybeRvcMap(update_maybe_rvc),
        .io_wayLookupUpdate_bits_corrupt(update_corrupt),
        .io_dataRead_req_valid(data_req_valid),
        .io_dataRead_req_bits_vSetIdx(data_req_vset_vec),
        .io_dataRead_req_bits_isDoubleLine(data_req_doubleline),
        .io_dataRead_req_bits_waymask(data_req_waymask_vec),
        .io_dataRead_req_bits_blkOffset(data_req_blk_offset),
        .io_dataRead_req_bits_blkEndOffset(data_req_blk_end_offset),
        .io_replacerTouch_req_0_valid(touch0_valid),
        .io_replacerTouch_req_0_bits_vSetIdx(touch0_vset),
        .io_replacerTouch_req_0_bits_way(touch0_way),
        .io_replacerTouch_req_1_valid(touch1_valid),
        .io_replacerTouch_req_1_bits_vSetIdx(touch1_vset),
        .io_replacerTouch_req_1_bits_way(touch1_way),
        .io_wayLookupRead_ready(way_read_ready),
        .io_wayLookupRead_valid(way_read_valid),
        .io_wayLookupWrite_ready(way_write_ready),
        .io_wayLookupPerf_empty(way_perf_empty),
        .io_missReq_valid(miss_req_valid),
        .io_missReq_bits_blkPAddr(miss_req_blk_paddr),
        .io_missReq_bits_vSetIdx(miss_req_vset),
        .io_req_ready(req_ready),
        .io_pmp_req_bits_addr(pmp_req_addr),
        .io_resp_valid(resp_valid),
        .io_resp_bits_doubleline(resp_doubleline),
        .io_resp_bits_vAddr_0_addr(resp_vaddr),
        .io_resp_bits_data(resp_data),
        .io_resp_bits_maybeRvcMap(resp_maybe_rvc),
        .io_resp_bits_pAddr_addr(resp_paddr),
        .io_resp_bits_exception_value(resp_exception),
        .io_resp_bits_pmpMmio(resp_pmp_mmio),
        .io_resp_bits_itlbPbmt(resp_itlb_pbmt),
        .io_resp_bits_isBackendException(resp_backend_exception),
        .io_resp_bits_gpAddr_addr(resp_gpaddr),
        .io_resp_bits_isForVSnonLeafPTE(resp_is_vs_nonleaf),
        .io_errors_0_valid(error0_valid),
        .io_errors_0_bits_paddr(error0_paddr),
        .io_errors_0_bits_report_to_beu(error0_report),
        .io_errors_1_valid(error1_valid),
        .io_errors_1_bits_paddr(error1_paddr),
        .io_errors_1_bits_report_to_beu(error1_report),
        .io_perf_rawHits(perf_raw_hits),
        .io_perf_pendingMiss(perf_pending_miss)
    );

    assign resp_data0 = resp_data[63:0];
    assign resp_data1 = resp_data[127:64];
    assign resp_data2 = resp_data[191:128];
    assign resp_data3 = resp_data[255:192];
    assign resp_data4 = resp_data[319:256];
    assign resp_data5 = resp_data[383:320];
    assign resp_data6 = resp_data[447:384];
    assign resp_data7 = resp_data[511:448];
endmodule
