// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module OldestArbiter(
  input        clock,
  input        reset,
  output       io_in_0_ready,
  input        io_in_0_valid,
  input  [5:0] io_in_0_bits_addr,
  input        io_in_0_bits_robIdx_flag,
  input  [8:0] io_in_0_bits_robIdx_value,
  input        io_in_0_bits_issueValid,
  output       io_in_1_ready,
  input        io_in_1_valid,
  input  [5:0] io_in_1_bits_addr,
  input        io_in_1_bits_robIdx_flag,
  input  [8:0] io_in_1_bits_robIdx_value,
  input        io_in_1_bits_issueValid,
  output       io_out_valid,
  output [5:0] io_out_bits_addr,
  output       io_out_bits_robIdx_flag,
  output [8:0] io_out_bits_robIdx_value,
  output       io_out_bits_issueValid
);

  reg  [1:0]      validVecReg;
  reg             robIdxVecReg_0_flag;
  reg  [8:0]      robIdxVecReg_0_value;
  reg             robIdxVecReg_1_flag;
  reg  [8:0]      robIdxVecReg_1_value;
  reg  [1:0][1:0] priorityVecReg;
  wire [1:0]      mergePriority =
    (io_in_0_valid ? priorityVecReg[1'h0] : 2'h0)
    | (io_in_1_valid ? priorityVecReg[1'h1] : 2'h0);
  wire [1:0]      lzdMergePriority =
    mergePriority[0] ? 2'h0 : mergePriority[1] ? 2'h1 : 2'h2;
  wire            olderThanOtherNum_differentFlag =
    robIdxVecReg_0_flag ^ robIdxVecReg_1_flag;
  wire            olderThanOtherNum =
    olderThanOtherNum_differentFlag ^ robIdxVecReg_0_value < robIdxVecReg_1_value
    | ~validVecReg[1'h1];
  wire            _lzdHit_0_T =
    (priorityVecReg[1'h0][0]
       ? 2'h0
       : priorityVecReg[1'h0][1] ? 2'h1 : 2'h2) == lzdMergePriority;
  wire            olderThanOtherNum_1 =
    olderThanOtherNum_differentFlag ^ robIdxVecReg_1_value < robIdxVecReg_0_value
    | ~validVecReg[1'h0];
  `ifndef SYNTHESIS
    wire _GEN =
      ~reset & 2'({1'h0, priorityVecReg[1'h1] == priorityVecReg[1'h0]} + 2'h1) != 2'h1;
    always @(posedge clock) begin
      if (~reset
          & 2'({1'h0, priorityVecReg[1'h0][0]}
               + {1'h0, priorityVecReg[1'h0][1]}) != 2'h1) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: priorityRegVec_0 must be one hot\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (_GEN) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: priorityVecReg must be different\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset
          & 2'({1'h0, priorityVecReg[1'h1][0]}
               + {1'h0, priorityVecReg[1'h1][1]}) != 2'h1) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: priorityRegVec_1 must be one hot\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (_GEN) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: priorityVecReg must be different\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire            _lzdHit_1_T =
    (priorityVecReg[1'h1][0]
       ? 2'h0
       : priorityVecReg[1'h1][1] ? 2'h1 : 2'h2) == lzdMergePriority;
  wire            _GEN_0 = validVecReg[1'h0] & validVecReg[1'h1];
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      validVecReg <= '{1'h0, 1'h0};
      priorityVecReg <= '{2'h2, 2'h1};
    end
    else begin
      validVecReg[1'h1] <= io_in_1_valid;
      validVecReg[1'h0] <= io_in_0_valid;
      priorityVecReg[1'h1] <= _GEN_0 ? 2'h2 >> olderThanOtherNum_1 : 2'h2;
      priorityVecReg[1'h0] <= _GEN_0 ? 2'h2 >> olderThanOtherNum : 2'h1;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    robIdxVecReg_0_flag <= io_in_0_bits_robIdx_flag;
    robIdxVecReg_0_value <= io_in_0_bits_robIdx_value;
    robIdxVecReg_1_flag <= io_in_1_bits_robIdx_flag;
    robIdxVecReg_1_value <= io_in_1_bits_robIdx_value;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        validVecReg[1'h0] = _RANDOM[/*Zero width*/ 1'b0][1];
        validVecReg[1'h1] = _RANDOM[/*Zero width*/ 1'b0][0];
        robIdxVecReg_0_flag = _RANDOM[/*Zero width*/ 1'b0][2];
        robIdxVecReg_0_value = _RANDOM[/*Zero width*/ 1'b0][11:3];
        robIdxVecReg_1_flag = _RANDOM[/*Zero width*/ 1'b0][12];
        robIdxVecReg_1_value = _RANDOM[/*Zero width*/ 1'b0][21:13];
        priorityVecReg[1'h0] = _RANDOM[/*Zero width*/ 1'b0][25:24];
        priorityVecReg[1'h1] = _RANDOM[/*Zero width*/ 1'b0][23:22];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        validVecReg = '{1'h0, 1'h0};
        priorityVecReg = '{2'h2, 2'h1};
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_0_ready = ~io_in_0_valid | _lzdHit_0_T;
  assign io_in_1_ready = ~io_in_1_valid | _lzdHit_1_T;
  assign io_out_valid = io_in_0_valid | io_in_1_valid;
  assign io_out_bits_addr =
    (_lzdHit_0_T ? io_in_0_bits_addr : 6'h0) | (_lzdHit_1_T ? io_in_1_bits_addr : 6'h0);
  assign io_out_bits_robIdx_flag =
    _lzdHit_0_T & io_in_0_bits_robIdx_flag | _lzdHit_1_T & io_in_1_bits_robIdx_flag;
  assign io_out_bits_robIdx_value =
    (_lzdHit_0_T ? io_in_0_bits_robIdx_value : 9'h0)
    | (_lzdHit_1_T ? io_in_1_bits_robIdx_value : 9'h0);
  assign io_out_bits_issueValid =
    _lzdHit_0_T & io_in_0_bits_issueValid | _lzdHit_1_T & io_in_1_bits_issueValid;
endmodule

