package xscomponents

import chisel3.RawModule
import chisel3.stage.ChiselGeneratorAnnotation
import _root_.circt.stage.ChiselStage
import _root_.circt.stage.FirtoolOption

object XsComponentsMain extends App {
  val tops = Map[String, () => RawModule](
    "XsReal000PipelineLoadunitLarge" -> (() => new XsReal000PipelineLoadunitLarge),
    "XsReal001RobRobLarge" -> (() => new XsReal001RobRobLarge),
    "XsReal002MemMemblockLarge" -> (() => new XsReal002MemMemblockLarge),
    "XsReal003DecodeDecodeunitcompLarge" -> (() => new XsReal003DecodeDecodeunitcompLarge),
    "XsReal004LsqueueStorequeueLarge" -> (() => new XsReal004LsqueueStorequeueLarge),
    "XsReal005MmuPagetablecacheLarge" -> (() => new XsReal005MmuPagetablecacheLarge),
    "XsReal006DcacheDcachewrapperLarge" -> (() => new XsReal006DcacheDcachewrapperLarge),
    "XsReal007FuCsrLarge" -> (() => new XsReal007FuCsrLarge),
    "XsReal008DecodeDecodeunitLarge" -> (() => new XsReal008DecodeDecodeunitLarge),
    "XsReal009NewcsrNewcsrLarge" -> (() => new XsReal009NewcsrNewcsrLarge),
    "XsReal010IssueIssuequeueLarge" -> (() => new XsReal010IssueIssuequeueLarge),
    "XsReal011MainpipeMissqueueLarge" -> (() => new XsReal011MainpipeMissqueueLarge),
    "XsReal012MmuPagetablewalkerLarge" -> (() => new XsReal012MmuPagetablewalkerLarge),
    "XsReal013PrefetchSmsprefetcherLarge" -> (() => new XsReal013PrefetchSmsprefetcherLarge),
    "XsReal014DispatchNewdispatchLarge" -> (() => new XsReal014DispatchNewdispatchLarge),
    "XsReal015Tl2ChiMshrLarge" -> (() => new XsReal015Tl2ChiMshrLarge),
    "XsReal016DecodeVecdecoderLarge" -> (() => new XsReal016DecodeVecdecoderLarge),
    "XsReal017MmuL2TlbLarge" -> (() => new XsReal017MmuL2TlbLarge),
    "XsReal018VectorVsegmentunitLarge" -> (() => new XsReal018VectorVsegmentunitLarge),
    "XsReal019BackendCtrlblockLarge" -> (() => new XsReal019BackendCtrlblockLarge),
    "XsReal020DatapathDatapathLarge" -> (() => new XsReal020DatapathDatapathLarge),
    "XsReal021Tl2ChiMainpipeLarge" -> (() => new XsReal021Tl2ChiMainpipeLarge),
    "XsReal022BackendRegionLarge" -> (() => new XsReal022BackendRegionLarge),
    "XsReal023RenameRenameLarge" -> (() => new XsReal023RenameRenameLarge),
    "XsReal024MainpipeMainpipeLarge" -> (() => new XsReal024MainpipeMainpipeLarge),
    "XsReal025IfuIfuLarge" -> (() => new XsReal025IfuIfuLarge),
    "XsReal026LsqueueLoadqueuereplayLarge" -> (() => new XsReal026LsqueueLoadqueuereplayLarge),
    "XsReal027SbufferSbufferLarge" -> (() => new XsReal027SbufferSbufferLarge),
    "XsReal028PrefetchL1PrefetchcomponentLarge" -> (() => new XsReal028PrefetchL1PrefetchcomponentLarge),
    "XsReal029PipelineStoreunitLarge" -> (() => new XsReal029PipelineStoreunitLarge),
    "XsReal030PrefetchBertiLarge" -> (() => new XsReal030PrefetchBertiLarge),
    "XsReal031DataBankeddataarrayLarge" -> (() => new XsReal031DataBankeddataarrayLarge),
    "XsReal032IssueEntriesLarge" -> (() => new XsReal032IssueEntriesLarge),
    "XsReal033XiangshanPackageLarge" -> (() => new XsReal033XiangshanPackageLarge),
    "XsReal034MmuTlbLarge" -> (() => new XsReal034MmuTlbLarge),
    "XsReal035BackendBackendLarge" -> (() => new XsReal035BackendBackendLarge),
    "XsReal036VectorVeccommonLarge" -> (() => new XsReal036VectorVeccommonLarge),
    "XsReal037Tl2TlMainpipeLarge" -> (() => new XsReal037Tl2TlMainpipeLarge),
    "XsReal038PrefetchBestoffsetprefetchLarge" -> (() => new XsReal038PrefetchBestoffsetprefetchLarge),
    "XsReal039LoadpipeLoadpipeLarge" -> (() => new XsReal039LoadpipeLoadpipeLarge),
    "XsReal040MmuRepeaterLarge" -> (() => new XsReal040MmuRepeaterLarge),
    "XsReal041ScScLarge" -> (() => new XsReal041ScScLarge),
    "XsReal042ExuExeunitLarge" -> (() => new XsReal042ExuExeunitLarge),
    "XsReal043TageTageLarge" -> (() => new XsReal043TageTageLarge),
    "XsReal044SramSramtemplateLarge" -> (() => new XsReal044SramSramtemplateLarge),
    "XsReal045NewcsrMachinelevelLarge" -> (() => new XsReal045NewcsrMachinelevelLarge),
    "XsReal046PipelineAtomicsunitLarge" -> (() => new XsReal046PipelineAtomicsunitLarge),
    "XsReal047LsqueueLoadmisalignbufferLarge" -> (() => new XsReal047LsqueueLoadmisalignbufferLarge),
    "XsReal048LsqueueStoremisalignbufferLarge" -> (() => new XsReal048LsqueueStoremisalignbufferLarge),
    "XsReal049LsqueueLsqwrapperLarge" -> (() => new XsReal049LsqueueLsqwrapperLarge),
    "XsReal050Coupledl2Coupledl2Large" -> (() => new XsReal050Coupledl2Coupledl2Large),
    "XsReal051DcacheUncacheLarge" -> (() => new XsReal051DcacheUncacheLarge),
    "XsReal052WrapperCsrLarge" -> (() => new XsReal052WrapperCsrLarge),
    "XsReal053FtqFtqLarge" -> (() => new XsReal053FtqFtqLarge),
    "XsReal054VectorVsplitLarge" -> (() => new XsReal054VectorVsplitLarge),
    "XsReal055DecodeFusiondecoderLarge" -> (() => new XsReal055DecodeFusiondecoderLarge),
    "XsReal056IcacheIcacheprefetchpipeLarge" -> (() => new XsReal056IcacheIcacheprefetchpipeLarge),
    "XsReal057BpuBpuLarge" -> (() => new XsReal057BpuBpuLarge),
    "XsReal058LsqueueLoadqueueuncacheLarge" -> (() => new XsReal058LsqueueLoadqueueuncacheLarge),
    "XsReal059VectorVmergebufferLarge" -> (() => new XsReal059VectorVmergebufferLarge),
    "XsReal060MdpStoresetLarge" -> (() => new XsReal060MdpStoresetLarge),
    "XsReal061UtilityChiseltaggedtraceLarge" -> (() => new XsReal061UtilityChiseltaggedtraceLarge),
    "XsReal062MmuBitmapcheckLarge" -> (() => new XsReal062MmuBitmapcheckLarge),
    "XsReal063LsqueueLoadqueuerawLarge" -> (() => new XsReal063LsqueueLoadqueuerawLarge),
    "XsReal064IcacheIcachemissunitLarge" -> (() => new XsReal064IcacheIcachemissunitLarge),
    "XsReal065NewcsrCsrpermitmoduleLarge" -> (() => new XsReal065NewcsrCsrpermitmoduleLarge),
    "XsReal066LsqueueLoadqueueLarge" -> (() => new XsReal066LsqueueLoadqueueLarge),
    "XsReal067DatapathWbarbiterLarge" -> (() => new XsReal067DatapathWbarbiterLarge),
    "XsReal068Tl2TlMshrLarge" -> (() => new XsReal068Tl2TlMshrLarge),
    "XsReal069IbufferIbufferLarge" -> (() => new XsReal069IbufferIbufferLarge),
    "XsReal070PrefetchL1StreamprefetcherLarge" -> (() => new XsReal070PrefetchL1StreamprefetcherLarge),
    "XsReal071IcacheIcachemainpipeLarge" -> (() => new XsReal071IcacheIcachemainpipeLarge),
    "XsReal072BackendVecexcpdatamergemoduleLarge" -> (() => new XsReal072BackendVecexcpdatamergemoduleLarge),
    "XsReal073PrefetchPrefetcherwrapperLarge" -> (() => new XsReal073PrefetchPrefetcherwrapperLarge),
    "XsReal074DatapathBypassnetworkLarge" -> (() => new XsReal074DatapathBypassnetworkLarge),
    "XsReal075RobVtypebufferLarge" -> (() => new XsReal075RobVtypebufferLarge),
    "XsReal076Coupledl2GrantbufferLarge" -> (() => new XsReal076Coupledl2GrantbufferLarge),
    "XsReal077RegfileRegfileLarge" -> (() => new XsReal077RegfileRegfileLarge),
    "XsReal078WrapperVfaluLarge" -> (() => new XsReal078WrapperVfaluLarge),
    "XsReal079PrefetchPrefetcherLarge" -> (() => new XsReal079PrefetchPrefetcherLarge),
    "XsReal080XiangshanL2TopLarge" -> (() => new XsReal080XiangshanL2TopLarge),
    "XsReal081RenameRenametableLarge" -> (() => new XsReal081RenameRenametableLarge),
    "XsReal082Tl2ChiMmiobridgeLarge" -> (() => new XsReal082Tl2ChiMmiobridgeLarge),
    "XsReal083ChiMessageLarge" -> (() => new XsReal083ChiMessageLarge),
    "XsReal084IttageIttageLarge" -> (() => new XsReal084IttageIttageLarge),
    "XsReal085MainpipeWritebackqueueLarge" -> (() => new XsReal085MainpipeWritebackqueueLarge),
    "XsReal086DecodeDecodestageLarge" -> (() => new XsReal086DecodeDecodestageLarge),
    "XsReal087NewcsrInterruptfilterLarge" -> (() => new XsReal087NewcsrInterruptfilterLarge),
    "XsReal088FuPmpLarge" -> (() => new XsReal088FuPmpLarge),
    "XsReal089LsqueueStorequeuedataLarge" -> (() => new XsReal089LsqueueStorequeuedataLarge),
    "XsReal090PrefetchTemporalprefetchLarge" -> (() => new XsReal090PrefetchTemporalprefetchLarge),
    "XsReal091Coupledl2RequestbufferLarge" -> (() => new XsReal091Coupledl2RequestbufferLarge),
    "XsReal092MmuTlbstorageLarge" -> (() => new XsReal092MmuTlbstorageLarge),
    "XsReal093FrontendFrontendLarge" -> (() => new XsReal093FrontendFrontendLarge),
    "XsReal094Coupledl2RequestarbLarge" -> (() => new XsReal094Coupledl2RequestarbLarge),
    "XsReal095RobRabLarge" -> (() => new XsReal095RobRabLarge),
    "XsReal096Coupledl2CommonLarge" -> (() => new XsReal096Coupledl2CommonLarge),
    "XsReal097FuSrt16DividerLarge" -> (() => new XsReal097FuSrt16DividerLarge),
    "XsReal098LsqueueVirtualloadqueueLarge" -> (() => new XsReal098LsqueueVirtualloadqueueLarge),
    "XsReal099PrefetchPrefetchermonitorLarge" -> (() => new XsReal099PrefetchPrefetchermonitorLarge),
    "XsReal100BackendNfmappedelemidxSmall" -> (() => new XsReal100BackendNfmappedelemidxSmall)
  )

  val top = args.sliding(2).collectFirst { case Array("--top-name", name) => name }.getOrElse("XsReal000PipelineLoadunitLarge")
  val filteredArgs = args.toSeq.sliding(2).foldLeft(args.toSeq) {
    case (acc, Seq("--top-name", name)) => acc.filterNot(x => x == "--top-name" || x == name)
    case (acc, _) => acc
  }
  val gen = tops.getOrElse(top, sys.error(s"unknown xs-component top '$$top'"))
  (new ChiselStage).execute(
    filteredArgs.toArray,
    Seq(
      ChiselGeneratorAnnotation(gen),
      FirtoolOption("--disable-all-randomization"),
    ),
  )
}
