module xs_bugcase_tb (
    input  logic        clk,
    input  logic        rst_n,
    input  logic        read_valid,
    input  logic [7:0]  read_set,
    input  logic [3:0]  read_waymask,
    input  logic        write_valid,
    input  logic [7:0]  write_set,
    input  logic [3:0]  write_waymask,
    input  logic [63:0] write_data,
    input  logic        write_code,
    input  logic        ram_hold,
    output logic        read_ready,
    output logic        write_ready,
    output logic [63:0] resp_data,
    output logic        resp_code
);
    wire        bore_ack;
    wire [65:0] bore_outdata;

    ICacheDataBank_5 dut (
        .clock(clk),
        .reset(!rst_n),
        .io_read_req_ready(read_ready),
        .io_read_req_valid(read_valid),
        .io_read_req_bits_setIdx(read_set),
        .io_read_req_bits_waymask(read_waymask),
        .io_read_resp_entry_data(resp_data),
        .io_read_resp_entry_code(resp_code),
        .io_write_req_ready(write_ready),
        .io_write_req_valid(write_valid),
        .io_write_req_bits_setIdx(write_set),
        .io_write_req_bits_waymask(write_waymask),
        .io_write_req_bits_entry_data(write_data),
        .io_write_req_bits_entry_code(write_code),
        .boreChildrenBd_bore_array(5'h0),
        .boreChildrenBd_bore_all(1'b0),
        .boreChildrenBd_bore_req(1'b0),
        .boreChildrenBd_bore_ack(bore_ack),
        .boreChildrenBd_bore_writeen(1'b0),
        .boreChildrenBd_bore_be(1'b0),
        .boreChildrenBd_bore_addr(9'h0),
        .boreChildrenBd_bore_indata(66'h0),
        .boreChildrenBd_bore_readen(1'b0),
        .boreChildrenBd_bore_addr_rd(9'h0),
        .boreChildrenBd_bore_outdata(bore_outdata),
        .sigFromSrams_bore_ram_hold(ram_hold),
        .sigFromSrams_bore_ram_bypass(1'b0),
        .sigFromSrams_bore_ram_bp_clken(1'b0),
        .sigFromSrams_bore_ram_aux_clk(1'b0),
        .sigFromSrams_bore_ram_aux_ckbp(1'b0),
        .sigFromSrams_bore_ram_mcp_hold(1'b0),
        .sigFromSrams_bore_cgen(1'b0),
        .sigFromSrams_bore_1_ram_hold(ram_hold),
        .sigFromSrams_bore_1_ram_bypass(1'b0),
        .sigFromSrams_bore_1_ram_bp_clken(1'b0),
        .sigFromSrams_bore_1_ram_aux_clk(1'b0),
        .sigFromSrams_bore_1_ram_aux_ckbp(1'b0),
        .sigFromSrams_bore_1_ram_mcp_hold(1'b0),
        .sigFromSrams_bore_1_cgen(1'b0),
        .sigFromSrams_bore_2_ram_hold(ram_hold),
        .sigFromSrams_bore_2_ram_bypass(1'b0),
        .sigFromSrams_bore_2_ram_bp_clken(1'b0),
        .sigFromSrams_bore_2_ram_aux_clk(1'b0),
        .sigFromSrams_bore_2_ram_aux_ckbp(1'b0),
        .sigFromSrams_bore_2_ram_mcp_hold(1'b0),
        .sigFromSrams_bore_2_cgen(1'b0),
        .sigFromSrams_bore_3_ram_hold(ram_hold),
        .sigFromSrams_bore_3_ram_bypass(1'b0),
        .sigFromSrams_bore_3_ram_bp_clken(1'b0),
        .sigFromSrams_bore_3_ram_aux_clk(1'b0),
        .sigFromSrams_bore_3_ram_aux_ckbp(1'b0),
        .sigFromSrams_bore_3_ram_mcp_hold(1'b0),
        .sigFromSrams_bore_3_cgen(1'b0)
    );

    wire _unused_bore = bore_ack ^ (^bore_outdata);
endmodule
