#!/usr/bin/env python3
"""Generate a bind-able SystemVerilog tap module that dumps every Rob I/O port
once per clock cycle as text, plus the JSON port manifest the trace packer
needs to parse the dump back.

The tap is bound into the full XiangShan design (Verilator ref emu) with
``bind Rob RobTap u_rob_tap (.*);`` so every port of the tap must exist under
the same name inside the Rob module.  All tap ports are inputs (observe-only).

Trace text format (one pair of lines per posedge):

    I <cycle> <reset> <in_port_0 %0h> <in_port_1 %0h> ...
    O <cycle> <out_port_0 %0h> <out_port_1 %0h> ...

Port order in both lines matches the SV declaration order recorded in the
JSON manifest (``tap_ports.json``).  The output path defaults to
``rob_trace.txt`` and can be overridden with ``+rob_trace=<path>`` (a FIFO
path works, enabling streaming conversion to the binary bench format).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_rob_bench import log, parse_sv_ports  # noqa: E402


def emit_tap(ports: dict[str, tuple[str, int]], top: str) -> str:
    clock_name = "clock"
    reset_name = "reset"
    io_ports = [(name, dirw) for name, dirw in ports.items() if name not in (clock_name, reset_name)]
    inputs = [(name, w) for name, (d, w) in io_ports if d == "input"]
    outputs = [(name, w) for name, (d, w) in io_ports if d == "output"]

    lines: list[str] = []
    lines.append("// Generated by testcase/xs-components/scripts/gen_rob_tap.py. Do not edit.")
    lines.append("// Observability tap bound into every Rob instance of the full design;")
    lines.append("// dumps all Rob I/O ports as hex text once per posedge.")
    lines.append(f"module {top}Tap(")
    lines.append("    input clock,")
    lines.append("    input reset,")
    decls: list[str] = []
    for name, (_dir, width) in io_ports:
        if width > 1:
            decls.append(f"    input [{width - 1}:0] {name}")
        else:
            decls.append(f"    input {name}")
    lines.append(",\n".join(decls))
    lines.append(");")
    lines.append("")
    lines.append("    integer fd;")
    lines.append("    integer cycle;")
    lines.append("    reg [8*256-1:0] path;")
    lines.append("    initial begin")
    lines.append("        fd = 0;")
    lines.append('        if ($value$plusargs("rob_trace=%s", path)) begin')
    lines.append('            fd = $fopen(path, "w");')
    lines.append("        end")
    lines.append("        if (fd == 0) begin")
    lines.append('            fd = $fopen("rob_trace.txt", "w");')
    lines.append("        end")
    lines.append("        if (fd == 0) begin")
    lines.append('            $display("[RobTap] FATAL: cannot open trace output");')
    lines.append("            $finish;")
    lines.append("        end")
    lines.append("        cycle = 0;")
    lines.append("    end")
    lines.append("")
    lines.append("    always @(posedge clock) begin")
    in_args = ", ".join(name for name, _ in inputs)
    in_fmt = " ".join(["%0d", "%0d"] + ["%0h"] * len(inputs))
    lines.append(
        f'        $fwrite(fd, "I {in_fmt}\\n", cycle, reset'
        + (", " + in_args if in_args else "")
        + ");"
    )
    out_args = ", ".join(name for name, _ in outputs)
    out_fmt = " ".join(["%0d"] + ["%0h"] * len(outputs))
    lines.append(
        f'        $fwrite(fd, "O {out_fmt}\\n", cycle'
        + (", " + out_args if out_args else "")
        + ");"
    )
    lines.append("        cycle <= cycle + 1;")
    lines.append("    end")
    lines.append("")
    lines.append("    final begin")
    lines.append("        if (fd != 0) begin")
    lines.append("            $fclose(fd);")
    lines.append("        end")
    lines.append("    end")
    lines.append("")
    lines.append("endmodule")
    lines.append("")
    lines.append(f"bind {top} {top}Tap u_{top.lower()}_tap (.*);")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--top", default="Rob")
    parser.add_argument("--sv", required=True, help="Rob.sv as instantiated by the full design")
    parser.add_argument("--out", required=True, help="output tap .sv path")
    parser.add_argument("--manifest", required=True, help="output tap_ports.json path")
    args = parser.parse_args()

    ports = parse_sv_ports(Path(args.sv), args.top)
    inputs = [{"name": n, "width": w} for n, (d, w) in ports.items()
              if d == "input" and n not in ("clock", "reset")]
    outputs = [{"name": n, "width": w} for n, (d, w) in ports.items() if d == "output"]
    if "clock" not in ports or "reset" not in ports:
        raise RuntimeError(f"{args.sv} module {args.top} lacks clock/reset ports")

    tap_sv = emit_tap(ports, args.top)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(tap_sv, encoding="utf-8")

    manifest = {
        "top": args.top,
        "sv": str(args.sv),
        "inputs": inputs,
        "outputs": outputs,
        "format": "I <cycle> <reset> <inputs...> / O <cycle> <outputs...>; hex tokens, declaration order",
    }
    manifest_path = Path(args.manifest)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=1) + "\n", encoding="utf-8")

    in_bits = sum(p["width"] for p in inputs)
    out_bits = sum(p["width"] for p in outputs)
    log(f"ports: inputs={len(inputs)} ({in_bits} bits) outputs={len(outputs)} ({out_bits} bits)")
    log(f"wrote {out_path} ({len(tap_sv)} bytes), manifest {manifest_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
