import { JSONParser } from '@streamparser/json'
import {
  attrAsString,
  attrPayloadToString,
  graphSymbol,
  type DesignOverview,
  type EdgeBundle,
  type GraphDetail,
  type GraphSummary,
  type GrhDesign,
  type GrhGraph,
  type GrhOperation,
  type HierarchyNode,
  type LayerBand,
  type SchematicEdge,
  type SchematicNode,
  type WorkerRequest,
  type WorkerResponse,
} from '../lib/grh'

type InstanceRef = {
  moduleName: string
  instanceName: string
}

type NormalizedGraph = {
  symbol: string
  raw: GrhGraph
  summary: GraphSummary
  instances: InstanceRef[]
}

type NormalizedDesign = {
  overview: DesignOverview
  graphsBySymbol: Map<string, NormalizedGraph>
}

const DECLARATION_OP_KINDS = new Set(['kRegister', 'kMemory', 'kLatch'])
const STATE_SOURCE_OP_KINDS = new Set(['kRegisterReadPort', 'kLatchReadPort'])
const STATE_SINK_OP_KINDS = new Set(['kRegisterWritePort', 'kLatchWritePort'])
const STATE_PORT_OP_KINDS = new Set([
  'kRegisterReadPort',
  'kLatchReadPort',
  'kRegisterWritePort',
  'kLatchWritePort',
])

let currentDesign: NormalizedDesign | null = null

function isAutoGeneratedOpSymbol(symbol: string): boolean {
  return /^_+op_\d+$/.test(symbol)
}

function isDeclarationOp(kind: string): boolean {
  return DECLARATION_OP_KINDS.has(kind)
}

function isStateSourceOp(kind: string): boolean {
  return STATE_SOURCE_OP_KINDS.has(kind)
}

function isStateSinkOp(kind: string): boolean {
  return STATE_SINK_OP_KINDS.has(kind)
}

function isStatePortOp(kind: string): boolean {
  return STATE_PORT_OP_KINDS.has(kind)
}

function formatOpKind(kind: string): string {
  const raw = kind.startsWith('k') ? kind.slice(1) : kind
  return raw.replace(/([a-z0-9])([A-Z])/g, '$1 $2')
}

function opSecondaryLabel(op: GrhOperation): string | null {
  return (
    attrAsString(op.attrs, 'moduleName') ??
    attrAsString(op.attrs, 'instanceName') ??
    attrAsString(op.attrs, 'regSymbol') ??
    attrAsString(op.attrs, 'latchSymbol') ??
    attrAsString(op.attrs, 'memSymbol') ??
    (!isAutoGeneratedOpSymbol(op.sym) ? op.sym : null)
  )
}

function opPrimaryLabel(op: GrhOperation, secondaryLabel: string | null): string {
  if (op.kind === 'kInstance' || op.kind === 'kBlackbox') {
    return secondaryLabel ?? formatOpKind(op.kind)
  }
  return formatOpKind(op.kind)
}

function buildTopologicalOrder(outgoing: number[][], incoming: Set<number>[]): number[] {
  const indegree = incoming.map((deps) => deps.size)
  const order: number[] = []
  const queue: number[] = []
  const visited = new Array(indegree.length).fill(false)

  for (let index = 0; index < indegree.length; index += 1) {
    if (indegree[index] === 0) {
      queue.push(index)
    }
  }

  for (let head = 0; head < queue.length; head += 1) {
    const current = queue[head]
    visited[current] = true
    order.push(current)
    for (const target of outgoing[current]) {
      indegree[target] -= 1
      if (indegree[target] === 0) {
        queue.push(target)
      }
    }
  }

  if (order.length === indegree.length) {
    return order
  }

  for (let index = 0; index < indegree.length; index += 1) {
    if (!visited[index]) {
      order.push(index)
    }
  }
  return order
}

function fail(
  requestId: number,
  stage: 'load-design' | 'load-hierarchy-children' | 'load-graph',
  message: string,
) {
  const response: WorkerResponse = { type: 'error', requestId, stage, message }
  postMessage(response)
}

function postDesignProgress(
  requestId: number,
  phase: string,
  loadedBytes: number,
  totalBytes: number,
  progress: number,
) {
  const response: WorkerResponse = {
    type: 'design-progress',
    requestId,
    phase,
    loadedBytes,
    totalBytes,
    progress,
  }
  postMessage(response)
}

async function parseDesignFile(file: File, requestId: number): Promise<GrhDesign> {
  const reader = file.stream().getReader()
  const parser = new JSONParser({
    paths: ['$.graphs.*', '$.tops.*'],
    keepStack: false,
    stringBufferSize: 64 * 1024,
  })
  const rawGraphs: GrhGraph[] = []
  const tops: string[] = []
  const totalBytes = Math.max(file.size, 1)
  let loadedBytes = 0
  let lastReportedPercent = -1

  const parsed = new Promise<GrhDesign>((resolve, reject) => {
    parser.onValue = ({ value, stack }) => {
      const ownerKey = stack[stack.length - 1]?.key
      if (ownerKey === 'graphs') {
        rawGraphs.push(value as GrhGraph)
        return
      }
      if (ownerKey === 'tops' && typeof value === 'string') {
        tops.push(value)
      }
    }
    parser.onError = (error) => reject(error)
    parser.onEnd = () => resolve({ graphs: rawGraphs, tops })
  })

  try {
    postDesignProgress(requestId, 'Parsing JSON', 0, totalBytes, 0)
    while (true) {
      const { done, value } = await reader.read()
      if (done) {
        break
      }
      loadedBytes += value.byteLength
      parser.write(value)
      const percent = Math.min(99, Math.floor((loadedBytes / totalBytes) * 100))
      if (percent > lastReportedPercent) {
        lastReportedPercent = percent
        postDesignProgress(requestId, 'Parsing JSON', loadedBytes, totalBytes, percent / 100)
      }
    }
    if (!parser.isEnded) {
      parser.end()
    }
    return await parsed
  } finally {
    reader.releaseLock()
  }
}

function hierarchyAncestors(path: string): Set<string> {
  const ancestors = new Set<string>()
  const segments = path.split('/').filter(Boolean)
  if (segments.length === 0) {
    return ancestors
  }
  ancestors.add(segments[0])
  for (const segment of segments.slice(1)) {
    const parts = segment.split(':')
    if (parts.length >= 2) {
      ancestors.add(parts[1])
    }
  }
  return ancestors
}

function buildHierarchyChildren(symbol: string, path: string): HierarchyNode[] {
  if (!currentDesign) {
    throw new Error('No design is loaded yet')
  }
  const entry = currentDesign.graphsBySymbol.get(symbol)
  if (!entry) {
    throw new Error(`Hierarchy graph not found: ${symbol}`)
  }

  const ancestors = hierarchyAncestors(path)
  return entry.instances.map((instance, index) => {
    const childPath = `${path}/${instance.instanceName}:${instance.moduleName}:${index}`
    const isCycle = ancestors.has(instance.moduleName)
    const childEntry = currentDesign?.graphsBySymbol.get(instance.moduleName)
    const childCount = isCycle ? 0 : (childEntry?.instances.length ?? 0)
    return {
      id: childPath,
      label: instance.instanceName,
      path: childPath,
      graphSymbol: instance.moduleName,
      moduleName: instance.moduleName,
      instanceName: instance.instanceName,
      childCount,
      childrenLoaded: childCount === 0,
      children: [],
    }
  })
}

function normalizeDesign(payload: GrhDesign): NormalizedDesign {
  const rawGraphs = payload.graphs ?? []
  if (rawGraphs.length === 0) {
    throw new Error('Design JSON does not contain graphs[]')
  }

  const graphEntries = rawGraphs.map((raw) => {
    const symbol = graphSymbol(raw)
    const ops = raw.ops ?? []
    const vals = raw.vals ?? []
    const ports = raw.ports ?? {}
    const instances = ops
      .filter((op) => op.kind === 'kInstance' || op.kind === 'kBlackbox')
      .map((op) => ({
        moduleName: attrAsString(op.attrs, 'moduleName') ?? '<unknown-module>',
        instanceName:
          (attrAsString(op.attrs, 'instanceName') ?? op.sym.replace(/^_+/, '')) || op.sym,
      }))
    const kindCounts = new Map<string, number>()
    for (const op of ops) {
      kindCounts.set(op.kind, (kindCounts.get(op.kind) ?? 0) + 1)
    }
    const topKinds = [...kindCounts.entries()]
      .sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0]))
      .slice(0, 4)
      .map(([kind]) => kind)
    const summary: GraphSummary = {
      symbol,
      opCount: ops.length,
      valueCount: vals.length,
      portCount:
        (ports.in?.length ?? 0) +
        (ports.out?.length ?? 0) +
        (ports.inout?.length ?? 0),
      instanceCount: instances.length,
      children: [...new Set(instances.map((item) => item.moduleName))],
      topKinds,
    }
    return {
      symbol,
      raw,
      summary,
      instances,
    }
  })

  const graphsBySymbol = new Map(graphEntries.map((entry) => [entry.symbol, entry]))
  const tops = payload.tops?.length ? payload.tops : [graphEntries[0].symbol]

  const tree = tops.map((top) => {
    const entry = graphsBySymbol.get(top)
    const childCount = entry?.instances.length ?? 0
    return {
      id: top,
      label: top,
      path: top,
      graphSymbol: top,
      moduleName: top,
      instanceName: top,
      childCount,
      childrenLoaded: childCount === 0,
      children: [],
    }
  })
  const overview: DesignOverview = {
    summary: {
      graphCount: graphEntries.length,
      operationCount: graphEntries.reduce((sum, entry) => sum + entry.summary.opCount, 0),
      valueCount: graphEntries.reduce((sum, entry) => sum + entry.summary.valueCount, 0),
      portCount: graphEntries.reduce((sum, entry) => sum + entry.summary.portCount, 0),
      instanceCount: graphEntries.reduce((sum, entry) => sum + entry.summary.instanceCount, 0),
    },
    graphs: graphEntries
      .map((entry) => entry.summary)
      .sort((left, right) => left.symbol.localeCompare(right.symbol)),
    tree,
    tops,
  }

  return {
    overview,
    graphsBySymbol,
  }
}

function buildGraphDetail(symbol: string, instancePath: string | undefined): GraphDetail {
  if (!currentDesign) {
    throw new Error('No design is loaded yet')
  }
  const entry = currentDesign.graphsBySymbol.get(symbol)
  if (!entry) {
    throw new Error(`Graph not found: ${symbol}`)
  }
  const graph = entry.raw
  const ports = graph.ports ?? {}
  const inputPorts = ports.in ?? []
  const outputPorts = ports.out ?? []
  const inoutPorts = ports.inout ?? []
  const vals = graph.vals ?? []
  const rawOps = graph.ops ?? []
  const ops = rawOps.filter((op) => !isDeclarationOp(op.kind))
  const instanceBasePath = instancePath ?? symbol
  const instanceOrdinalByOpSym = new Map(
    rawOps
      .filter((op) => op.kind === 'kInstance' || op.kind === 'kBlackbox')
      .map((op, index) => [op.sym, index] as const),
  )
  const valueBySymbol = new Map(vals.map((value) => [value.sym, value]))
  const opIndexBySymbol = new Map(ops.map((op, index) => [op.sym, index]))
  const inputPortByValue = new Map(inputPorts.map((port) => [port.val, port.name]))
  const inoutInByValue = new Map(inoutPorts.map((port) => [port.in, port.name]))

  const incomingDeps = Array.from({ length: ops.length }, () => new Set<number>())
  const outgoingDeps = Array.from({ length: ops.length }, () => [] as number[])
  const opEdges: Array<{ source: number; target: number; weight: number; value: string }> = []
  const portEdges: Array<{ sourceValue: string; target: number; weight: number }> = []

  for (let target = 0; target < ops.length; target += 1) {
    const op = ops[target]
    for (const inputValue of op.in ?? []) {
      const value = valueBySymbol.get(inputValue)
      const width = value?.w ?? 1
      const sourceOp = value?.def ? opIndexBySymbol.get(value.def) : undefined
      if (sourceOp !== undefined) {
        if (!incomingDeps[target].has(sourceOp)) {
          incomingDeps[target].add(sourceOp)
          outgoingDeps[sourceOp].push(target)
        }
        opEdges.push({ source: sourceOp, target, weight: width, value: inputValue })
      } else if (inputPortByValue.has(inputValue) || inoutInByValue.has(inputValue)) {
        portEdges.push({ sourceValue: inputValue, target, weight: width })
      }
    }
  }

  const topoOrder = buildTopologicalOrder(outgoingDeps, incomingDeps)
  const topoRank = new Map(topoOrder.map((opIndex, rank) => [opIndex, rank]))

  const incomingForward = Array.from({ length: ops.length }, () => new Set<number>())
  const forwardEdges: Array<{ source: number; target: number; weight: number; value: string }> = []
  const backEdges: Array<{ source: number; target: number; weight: number; value: string }> = []
  for (const edge of opEdges) {
    const sourceRank = topoRank.get(edge.source) ?? edge.source
    const targetRank = topoRank.get(edge.target) ?? edge.target
    if (sourceRank < targetRank) {
      incomingForward[edge.target].add(edge.source)
      forwardEdges.push(edge)
    } else {
      backEdges.push(edge)
    }
  }

  const layers = new Array<number>(ops.length).fill(2)
  for (const index of topoOrder) {
    if (isStateSourceOp(ops[index]?.kind ?? '')) {
      layers[index] = 1
      continue
    }
    if (isStateSinkOp(ops[index]?.kind ?? '')) {
      continue
    }
    let layer = 2
    for (const source of incomingForward[index]) {
      layer = Math.max(layer, layers[source] + 1)
    }
    layers[index] = layer
  }
  const middleMaxLayer = layers.reduce((max, current, index) => {
    if (isStateSourceOp(ops[index]?.kind ?? '') || isStateSinkOp(ops[index]?.kind ?? '')) {
      return max
    }
    return Math.max(max, current)
  }, 1)
  const sinkLayer = middleMaxLayer + 1
  for (let index = 0; index < ops.length; index += 1) {
    if (isStateSinkOp(ops[index]?.kind ?? '')) {
      layers[index] = sinkLayer
    }
  }
  const outputLayer = sinkLayer + 1

  const nodesByLayer = new Map<number, SchematicNode[]>()
  const pushNode = (layer: number, node: SchematicNode) => {
    const bucket = nodesByLayer.get(layer)
    if (bucket) {
      bucket.push(node)
      return
    }
    nodesByLayer.set(layer, [node])
  }

  for (const port of inputPorts) {
    pushNode(0, {
      id: `port:in:${port.name}`,
      label: port.name,
      secondaryLabel: port.val,
      kind: 'input-port',
      navigationPath: null,
      navigationSymbol: null,
      role: 'port-in',
      layer: 0,
      x: 0,
      y: 0,
      width: 132,
      height: 36,
      inputs: [],
      outputs: [port.val],
      attrs: [],
    })
  }
  for (const port of inoutPorts) {
    pushNode(0, {
      id: `port:inout:${port.name}`,
      label: port.name,
      secondaryLabel: `${port.in} / ${port.out}`,
      kind: 'inout-port',
      navigationPath: null,
      navigationSymbol: null,
      role: 'port-inout',
      layer: 0,
      x: 0,
      y: 0,
      width: 156,
      height: 38,
      inputs: [port.in],
      outputs: [port.out],
      attrs: port.oe ? [['oe', port.oe]] : [],
    })
  }

  for (const index of topoOrder) {
    const op = ops[index]
    const attrs: Array<[string, string]> = Object.entries(op.attrs ?? {}).map(
      ([key, payload]) => [key, attrPayloadToString(payload)] as [string, string],
    )
    const secondaryLabel = opSecondaryLabel(op)
    const label = opPrimaryLabel(op, secondaryLabel)
    const statePort = isStatePortOp(op.kind)
    const moduleName = attrAsString(op.attrs, 'moduleName')
    const instanceName =
      attrAsString(op.attrs, 'instanceName') ?? (op.sym.replace(/^_+/, '') || op.sym)
    const instanceOrdinal = instanceOrdinalByOpSym.get(op.sym)
    const navigationPath =
      op.kind === 'kInstance' && moduleName && instanceOrdinal !== undefined
        ? `${instanceBasePath}/${instanceName}:${moduleName}:${instanceOrdinal}`
        : null
    const width = statePort
      ? Math.min(224, Math.max(156, 92 + label.length * 7))
      : Math.min(272, Math.max(156, 92 + label.length * 8))
    pushNode(layers[index], {
      id: op.sym,
      label,
      secondaryLabel,
      kind: op.kind,
      navigationPath,
      navigationSymbol: op.kind === 'kInstance' ? moduleName ?? null : null,
      role: 'op',
      layer: layers[index],
      x: 0,
      y: 0,
      width,
      height: statePort ? (secondaryLabel ? 50 : 42) : secondaryLabel ? 62 : 48,
      inputs: op.in ?? [],
      outputs: op.out ?? [],
      attrs,
    })
  }

  for (const port of outputPorts) {
    pushNode(outputLayer, {
      id: `port:out:${port.name}`,
      label: port.name,
      secondaryLabel: port.val,
      kind: 'output-port',
      navigationPath: null,
      navigationSymbol: null,
      role: 'port-out',
      layer: outputLayer,
      x: 0,
      y: 0,
      width: 132,
      height: 36,
      inputs: [port.val],
      outputs: [],
      attrs: [],
    })
  }

  type PendingValueTarget = {
    nodeId: string
    layer: number
    kind: SchematicEdge['kind']
    weight: number
  }

  type PendingValueNode = {
    sym: string
    sourceId: string | null
    sourceLayer: number | null
    sourceKind: SchematicEdge['kind']
    targets: PendingValueTarget[]
  }

  const pendingValues = new Map<string, PendingValueNode>()

  const ensurePendingValue = (sym: string): PendingValueNode => {
    const existing = pendingValues.get(sym)
    if (existing) {
      return existing
    }
    const created: PendingValueNode = {
      sym,
      sourceId: null,
      sourceLayer: null,
      sourceKind: 'forward',
      targets: [],
    }
    pendingValues.set(sym, created)
    return created
  }

  const addPendingTarget = (entry: PendingValueNode, target: PendingValueTarget) => {
    if (entry.targets.some((item) => item.nodeId === target.nodeId && item.kind === target.kind)) {
      return
    }
    entry.targets.push(target)
  }

  for (const edge of forwardEdges) {
    const valueEntry = ensurePendingValue(edge.value)
    valueEntry.sourceId = ops[edge.source]?.sym ?? valueEntry.sourceId
    valueEntry.sourceLayer = layers[edge.source] ?? valueEntry.sourceLayer
    valueEntry.sourceKind = 'forward'
    addPendingTarget(valueEntry, {
      nodeId: ops[edge.target]?.sym ?? '',
      layer: layers[edge.target] ?? 0,
      kind: 'forward',
      weight: edge.weight,
    })
  }

  for (const edge of backEdges) {
    const valueEntry = ensurePendingValue(edge.value)
    valueEntry.sourceId = ops[edge.source]?.sym ?? valueEntry.sourceId
    valueEntry.sourceLayer = layers[edge.source] ?? valueEntry.sourceLayer
    valueEntry.sourceKind = 'forward'
    addPendingTarget(valueEntry, {
      nodeId: ops[edge.target]?.sym ?? '',
      layer: layers[edge.target] ?? 0,
      kind: 'backedge',
      weight: edge.weight,
    })
  }

  for (const edge of portEdges) {
    const portName =
      inputPortByValue.get(edge.sourceValue) ?? inoutInByValue.get(edge.sourceValue) ?? edge.sourceValue
    const sourceId = inputPortByValue.has(edge.sourceValue)
      ? `port:in:${portName}`
      : `port:inout:${portName}`
    const valueEntry = ensurePendingValue(edge.sourceValue)
    valueEntry.sourceId = sourceId
    valueEntry.sourceLayer = 0
    valueEntry.sourceKind = 'port'
    addPendingTarget(valueEntry, {
      nodeId: ops[edge.target]?.sym ?? '',
      layer: layers[edge.target] ?? 0,
      kind: 'port',
      weight: edge.weight,
    })
  }

  for (const port of outputPorts) {
    const value = valueBySymbol.get(port.val)
    const valueEntry = ensurePendingValue(port.val)
    if (!valueEntry.sourceId && value?.def) {
      const sourceOpIndex = opIndexBySymbol.get(value.def)
      if (sourceOpIndex !== undefined) {
        valueEntry.sourceId = value.def
        valueEntry.sourceLayer = layers[sourceOpIndex] ?? null
        valueEntry.sourceKind = 'forward'
      }
    }
    addPendingTarget(valueEntry, {
      nodeId: `port:out:${port.name}`,
      layer: outputLayer,
      kind: 'port',
      weight: value?.w ?? 1,
    })
  }

  for (const port of inoutPorts) {
    const value = valueBySymbol.get(port.out)
    const valueEntry = ensurePendingValue(port.out)
    if (!valueEntry.sourceId && value?.def) {
      const sourceOpIndex = opIndexBySymbol.get(value.def)
      if (sourceOpIndex !== undefined) {
        valueEntry.sourceId = value.def
        valueEntry.sourceLayer = layers[sourceOpIndex] ?? null
        valueEntry.sourceKind = 'forward'
      }
    }
    addPendingTarget(valueEntry, {
      nodeId: `port:inout:${port.name}`,
      layer: 0,
      kind: 'backedge',
      weight: value?.w ?? 1,
    })
  }

  for (const [sym, value] of valueBySymbol) {
    const entry = pendingValues.get(sym)
    if (!entry || entry.targets.length === 0) {
      continue
    }
    if (!entry.sourceId) {
      const inputName = inputPortByValue.get(sym)
      const inoutName = inoutInByValue.get(sym)
      if (inputName) {
        entry.sourceId = `port:in:${inputName}`
        entry.sourceLayer = 0
        entry.sourceKind = 'port'
      } else if (inoutName) {
        entry.sourceId = `port:inout:${inoutName}`
        entry.sourceLayer = 0
        entry.sourceKind = 'port'
      } else if (value.def) {
        const sourceOpIndex = opIndexBySymbol.get(value.def)
        if (sourceOpIndex !== undefined) {
          entry.sourceId = value.def
          entry.sourceLayer = layers[sourceOpIndex] ?? null
          entry.sourceKind = 'forward'
        }
      }
    }
  }

  const schematicValues = [...pendingValues.values()]
    .filter((entry) => entry.sourceId && entry.targets.length > 0)
    .map((entry) => {
      const value = valueBySymbol.get(entry.sym)
      const attrs: Array<[string, string]> = [
        ['width', String(value?.w ?? 1)],
        ['signed', value?.sgn ? 'true' : 'false'],
        ['users', String(value?.users?.length ?? entry.targets.length)],
      ]
      return {
        id: `value:${entry.sym}`,
        label: entry.sym,
        secondaryLabel: `${value?.w ?? 1}-bit${value?.sgn ? ' signed' : ''}`,
        sourceId: entry.sourceId,
        targetIds: entry.targets.map((target) => target.nodeId),
        attrs,
      }
    })
    .sort((left, right) => left.label.localeCompare(right.label))

  const orderedLayers = [...nodesByLayer.keys()].sort((left, right) => left - right)
  const nodes: SchematicNode[] = []
  const nodeIndexById = new Map<string, number>()
  const layerBands: LayerBand[] = []
  const layerSpacing = 132
  const splitLayerSpacing = 72
  const nodeSpacing = 44
  const leftMargin = 40
  const topMargin = 28

  const computeContentHeight = (layerNodes: SchematicNode[]) => {
    if (layerNodes.length === 0) {
      return 0
    }
    return layerNodes.reduce((sum, node) => sum + node.height, 0) + nodeSpacing * (layerNodes.length - 1)
  }

  const splitLayerColumns = (layer: number, layerNodes: SchematicNode[], targetContentHeight: number) => {
    const totalHeight = computeContentHeight(layerNodes)
    const requestedColumnCount = Math.max(1, Math.ceil(totalHeight / Math.max(1, targetContentHeight)))
    const columnCount = Math.min(layerNodes.length, requestedColumnCount)
    if (columnCount <= 1) {
      return [
        {
          layer,
          nodes: layerNodes,
          contentHeight: totalHeight,
          width: Math.max(...layerNodes.map((node) => node.width), 0),
        },
      ]
    }

    const columns = Array.from({ length: columnCount }, () => [] as SchematicNode[])
    const columnHeights = new Array<number>(columnCount).fill(0)
    const targetHeightPerColumn = totalHeight / columnCount
    let columnIndex = 0

    for (let nodeIndex = 0; nodeIndex < layerNodes.length; nodeIndex += 1) {
      const node = layerNodes[nodeIndex]
      const currentColumn = columns[columnIndex]
      const nodeContribution = node.height + (currentColumn.length > 0 ? nodeSpacing : 0)
      const remainingNodes = layerNodes.length - nodeIndex
      const remainingColumns = columnCount - columnIndex - 1
      const canAdvance = columnIndex < columnCount - 1 && remainingNodes > remainingColumns

      if (
        canAdvance &&
        currentColumn.length > 0 &&
        columnHeights[columnIndex] + nodeContribution > targetHeightPerColumn
      ) {
        columnIndex += 1
      }

      const destinationColumn = columns[columnIndex]
      const spacing = destinationColumn.length > 0 ? nodeSpacing : 0
      destinationColumn.push(node)
      columnHeights[columnIndex] += node.height + spacing
    }

    return columns
      .filter((column) => column.length > 0)
      .map((column) => ({
        layer,
        nodes: column,
        contentHeight: computeContentHeight(column),
        width: Math.max(...column.map((node) => node.width), 0),
      }))
  }

  const baseLayerWidths = orderedLayers.map((layer) => {
    const layerNodes = nodesByLayer.get(layer) ?? []
    return Math.max(...layerNodes.map((node) => node.width), 0)
  })
  const baseGraphWidthEstimate =
    leftMargin * 2 +
    baseLayerWidths.reduce((sum, width) => sum + width, 0) +
    Math.max(0, orderedLayers.length - 1) * layerSpacing

  const buildLayerPlan = (targetContentHeight: number) => {
    const layerPlans = orderedLayers.map((layer) => {
      const layerNodes = nodesByLayer.get(layer) ?? []
      const columns = splitLayerColumns(layer, layerNodes, targetContentHeight)
      const bandWidth =
        columns.reduce((sum, column) => sum + column.width, 0) +
        Math.max(0, columns.length - 1) * splitLayerSpacing
      return {
        layer,
        nodes: layerNodes,
        columns,
        bandWidth,
      }
    })
    const maxContentHeight = Math.max(
      80,
      ...layerPlans.flatMap((plan) => plan.columns.map((column) => column.contentHeight)),
    )
    const widthEstimate =
      leftMargin * 2 +
      layerPlans.reduce((sum, plan) => sum + plan.bandWidth, 0) +
      Math.max(0, layerPlans.length - 1) * layerSpacing
    const totalColumns = layerPlans.reduce((sum, plan) => sum + plan.columns.length, 0)
    return {
      layerPlans,
      maxContentHeight,
      widthEstimate,
      totalColumns,
    }
  }

  const aspectHeightFromWidth = (widthEstimate: number) => widthEstimate * (2 / 3) - topMargin * 2
  const strongTargetContentHeight = (widthEstimate: number) =>
    Math.max(220, Math.min(aspectHeightFromWidth(widthEstimate) * 0.82, aspectHeightFromWidth(widthEstimate) - 56))

  let targetContentHeight = strongTargetContentHeight(baseGraphWidthEstimate)
  let layoutPlan = buildLayerPlan(targetContentHeight)
  for (let iteration = 0; iteration < 4; iteration += 1) {
    const nextTargetHeight = strongTargetContentHeight(layoutPlan.widthEstimate)
    if (Math.abs(nextTargetHeight - targetContentHeight) < 16) {
      break
    }
    targetContentHeight = nextTargetHeight
    layoutPlan = buildLayerPlan(targetContentHeight)
  }

  const maxColumnContentHeight = layoutPlan.maxContentHeight
  const graphHeight = Math.max(160, topMargin * 2 + maxColumnContentHeight)

  let bandStartX = leftMargin
  for (const plan of layoutPlan.layerPlans) {
    let columnX = bandStartX
    for (const column of plan.columns) {
      let y = topMargin + (maxColumnContentHeight - column.contentHeight) / 2
      for (const node of column.nodes) {
        node.x = columnX + (column.width - node.width) / 2
        node.y = y
        nodeIndexById.set(node.id, nodes.length)
        nodes.push(node)
        y += node.height + nodeSpacing
      }
      columnX += column.width + splitLayerSpacing
    }
    layerBands[plan.layer] = {
      layer: plan.layer,
      x: bandStartX + plan.bandWidth / 2,
      centerY: graphHeight / 2,
      count: plan.nodes.length,
    }
    bandStartX += plan.bandWidth + layerSpacing
  }

  const edges: SchematicEdge[] = []

  for (const entry of pendingValues.values()) {
    if (!entry.sourceId || entry.targets.length === 0) {
      continue
    }
    const sourceIndex = nodeIndexById.get(entry.sourceId)
    if (sourceIndex === undefined) {
      continue
    }
    for (const target of entry.targets) {
      const targetIndex = nodeIndexById.get(target.nodeId)
      if (targetIndex === undefined) {
        continue
      }
      edges.push({
        id: `value-edge:${entry.sym}:${entry.sourceId}:${target.nodeId}`,
        source: sourceIndex,
        target: targetIndex,
        weight: target.weight,
        kind: target.kind,
        valueId: `value:${entry.sym}`,
      })
    }
  }

  const bundleMap = new Map<string, EdgeBundle>()
  for (const edge of edges) {
    const sourceLayer = nodes[edge.source]?.layer ?? 0
    const targetLayer = nodes[edge.target]?.layer ?? sourceLayer
    const key = `${sourceLayer}:${targetLayer}:${edge.kind}`
    const existing = bundleMap.get(key)
    if (existing) {
      existing.count += 1
      existing.weight += edge.weight
      continue
    }
    bundleMap.set(key, {
      id: key,
      fromLayer: sourceLayer,
      toLayer: targetLayer,
      count: 1,
      weight: edge.weight,
      kind: edge.kind,
    })
  }

  const graphWidth = nodes.reduce((max, node) => Math.max(max, node.x + node.width), leftMargin) + leftMargin

  return {
    symbol,
    instancePath: instancePath ?? null,
    opCount: ops.length,
    valueCount: vals.length,
    portCount: inputPorts.length + outputPorts.length + inoutPorts.length,
    backedgeCount: backEdges.length,
    layerCount: layoutPlan.totalColumns,
    width: graphWidth,
    height: graphHeight,
    nodes,
    values: schematicValues,
    edges,
    bundles: [...bundleMap.values()],
    layerBands,
  }
}

self.onmessage = (event: MessageEvent<WorkerRequest>) => {
  void handleMessage(event)
}

async function handleMessage(event: MessageEvent<WorkerRequest>) {
  const message = event.data
  if (message.type === 'load-design') {
    try {
      const payload = await parseDesignFile(message.file, message.requestId)
      postDesignProgress(message.requestId, 'Finalizing graph index', message.file.size, Math.max(message.file.size, 1), 1)
      currentDesign = normalizeDesign(payload)
      const response: WorkerResponse = {
        type: 'design-loaded',
        requestId: message.requestId,
        fileName: message.fileName,
        design: currentDesign.overview,
      }
      postMessage(response)
    } catch (error) {
      const messageText = error instanceof Error ? error.message : 'Unknown parse failure'
      fail(message.requestId, 'load-design', messageText)
    }
    return
  }

  if (message.type === 'load-hierarchy-children') {
    try {
      const response: WorkerResponse = {
        type: 'hierarchy-children-loaded',
        requestId: message.requestId,
        path: message.path,
        children: buildHierarchyChildren(message.symbol, message.path),
      }
      postMessage(response)
    } catch (error) {
      const messageText = error instanceof Error ? error.message : 'Unknown hierarchy failure'
      fail(message.requestId, 'load-hierarchy-children', messageText)
    }
    return
  }

  if (message.type === 'load-graph') {
    try {
      const graph = buildGraphDetail(message.symbol, message.instancePath)
      const response: WorkerResponse = {
        type: 'graph-loaded',
        requestId: message.requestId,
        graph,
      }
      postMessage(response)
    } catch (error) {
      const messageText = error instanceof Error ? error.message : 'Unknown graph build failure'
      fail(message.requestId, 'load-graph', messageText)
    }
  }
}