// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ICacheMainPipe(
  input              clock,
  input              reset,
  input  [5:0]       io_hartId,
  input              io_dataRead_req_ready,
  output             io_dataRead_req_valid,
  output [1:0][7:0]  io_dataRead_req_bits_vSetIdx,
  output             io_dataRead_req_bits_isDoubleLine,
  output [1:0][3:0]  io_dataRead_req_bits_waymask,
  output [5:0]       io_dataRead_req_bits_blkOffset,
  output [5:0]       io_dataRead_req_bits_blkEndOffset,
  input  [7:0][63:0] io_dataRead_resp_datas,
  input  [7:0]       io_dataRead_resp_codes,
  output             io_replacerTouch_req_0_valid,
  output [7:0]       io_replacerTouch_req_0_bits_vSetIdx,
  output [1:0]       io_replacerTouch_req_0_bits_way,
  output             io_replacerTouch_req_1_valid,
  output [7:0]       io_replacerTouch_req_1_bits_vSetIdx,
  output [1:0]       io_replacerTouch_req_1_bits_way,
  output             io_wayLookupRead_ready,
  input              io_wayLookupRead_valid,
  input  [1:0][7:0]  io_wayLookupRead_bits_entry_vSetIdx,
  input  [1:0][3:0]  io_wayLookupRead_bits_entry_waymask,
  input  [1:0][31:0] io_wayLookupRead_bits_entry_maybeRvcMap,
  input  [1:0]       io_wayLookupRead_bits_entry_metaCodes,
  input  [35:0]      io_wayLookupRead_bits_entry_pTag,
  input  [1:0]       io_wayLookupRead_bits_entry_itlbPbmt,
  input  [2:0]       io_wayLookupRead_bits_exceptionEntry_itlbException_value,
  input  [54:0]      io_wayLookupRead_bits_exceptionEntry_gpAddr_addr,
  input              io_wayLookupRead_bits_exceptionEntry_isForVSnonLeafPTE,
  input              io_missReq_ready,
  output             io_missReq_valid,
  output [41:0]      io_missReq_bits_blkPAddr,
  output [7:0]       io_missReq_bits_vSetIdx,
  input              io_missResp_valid,
  input  [41:0]      io_missResp_bits_blkPAddr,
  input  [7:0]       io_missResp_bits_vSetIdx,
  input  [511:0]     io_missResp_bits_data,
  input  [31:0]      io_missResp_bits_maybeRvcMap,
  input              io_missResp_bits_corrupt,
  input              io_missResp_bits_denied,
  input              io_eccEnable,
  output             io_req_ready,
  input              io_req_valid,
  input  [48:0]      io_req_bits_startVAddr_addr,
  input  [48:0]      io_req_bits_nextCachelineVAddr_addr,
  input              io_req_bits_ftqIdx_flag,
  input  [5:0]       io_req_bits_ftqIdx_value,
  input  [4:0]       io_req_bits_takenCfiOffset,
  input              io_req_bits_isBackendException,
  input              io_flush,
  input              io_flushFromBpu_s3_valid,
  input              io_flushFromBpu_s3_bits_flag,
  input  [5:0]       io_flushFromBpu_s3_bits_value,
  output [47:0]      io_pmp_req_bits_addr,
  input              io_pmp_resp_instr,
  input              io_pmp_resp_mmio,
  output             io_resp_valid,
  output             io_resp_bits_doubleline,
  output [48:0]      io_resp_bits_vAddr_0_addr,
  output [511:0]     io_resp_bits_data,
  output [31:0]      io_resp_bits_maybeRvcMap,
  output [46:0]      io_resp_bits_pAddr_addr,
  output [2:0]       io_resp_bits_exception_value,
  output             io_resp_bits_pmpMmio,
  output [1:0]       io_resp_bits_itlbPbmt,
  output             io_resp_bits_isBackendException,
  output [54:0]      io_resp_bits_gpAddr_addr,
  output             io_resp_bits_isForVSnonLeafPTE,
  input              io_respStall,
  output             io_errors_0_valid,
  output [47:0]      io_errors_0_bits_paddr,
  output             io_errors_0_bits_report_to_beu,
  output             io_errors_1_valid,
  output [47:0]      io_errors_1_bits_paddr,
  output             io_errors_1_bits_report_to_beu,
  output [1:0]       io_perf_rawHits,
  output             io_perf_pendingMiss,
  output [600:0]     gatewayIn_packed_0_bore,
  output [600:0]     gatewayIn_packed_1_bore
);

  wire [7:0]       _s1_dataCorrupt_WIRE_1;
  wire [7:0]       _s1_dataCorrupt_WIRE;
  wire             s1_ready;
  wire             s1_flush;
  wire [1:0]       s1_shouldFetch;
  wire [1:0]       s1_dataCorrupt;
  wire [7:0]       _s1_dataCorrupt_WIRE_4;
  wire [7:0]       _s1_dataCorrupt_WIRE_3;
  wire [1:0]       s1_metaCorrupt;
  wire [1:0]       s1_mshrValid;
  wire             s0_canGo;
  wire             _toMissArbiter_io_in_0_ready;
  wire             _toMissArbiter_io_in_1_ready;
  wire             _toMissArbiter_io_out_valid;
  wire             difftest_refill_valid = 1'h0;
  wire             difftest_refill_1_valid = 1'h0;
  wire [7:0]       difftest_refill_1_index = 8'h4;
  wire [7:0]       difftest_refill_index = 8'h3;
  reg  [31:0]      cntFtqFireInterval;
  wire [31:0]      cntFtqFireInterval_probe = cntFtqFireInterval;
  wire             x3_probe = s0_canGo & io_req_valid;
  wire [6:0]       s0_blkEndOffsetTmp =
    7'({1'h0, io_req_bits_startVAddr_addr[4:0], 1'h0}
       + {1'h0, io_req_bits_takenCfiOffset, 1'h0});
  wire             s0_doubleline = io_req_valid & s0_blkEndOffsetTmp[6];
  assign s0_canGo = io_dataRead_req_ready & io_wayLookupRead_valid & s1_ready;
  wire             s0_fire =
    io_req_valid & s0_canGo
    & ~(io_flush | io_req_valid & io_flushFromBpu_s3_valid
        & (io_flushFromBpu_s3_bits_flag ^ io_req_bits_ftqIdx_flag
           ^ io_flushFromBpu_s3_bits_value <= io_req_bits_ftqIdx_value));
  reg              s1_valid;
  reg              s1_ftqIdx_flag;
  reg  [5:0]       s1_ftqIdx_value;
  reg  [48:0]      s1_vAddr_0_addr;
  reg  [48:0]      s1_vAddr_1_addr;
  reg  [35:0]      s1_pTag;
  reg  [54:0]      s1_gpAddr_addr;
  reg              s1_isForVSnonLeafPTE;
  reg              s1_doubleline;
  reg  [2:0]       s1_itlbException_value;
  reg              s1_isBackendException;
  reg  [1:0]       s1_itlbPbmt;
  reg  [1:0][3:0]  s1_waymasks;
  reg  [1:0][31:0] s1_sramMaybeRvcMapRaw;
  reg  [1:0]       s1_metaCodes;
  reg  [5:0]       s1_blkEndOffset;
  reg  [1:0]       s1_sramHits;
  reg              s1_sramValid_REG;
  reg              s1_sramValid_REG_1;
  wire             _s1_sramValid_T = s1_sramValid_REG_1 & s1_doubleline;
  wire [7:0]       s1_bankSramValid;
  assign s1_bankSramValid =
    {{s1_sramValid_REG},
     {s1_vAddr_0_addr[4:2] != 3'h7 & s1_sramValid_REG | (&(s1_vAddr_0_addr[4:2]))
        & _s1_sramValid_T},
     {s1_vAddr_0_addr[4:3] != 2'h3 & s1_sramValid_REG | s1_vAddr_0_addr[4:2] > 3'h5
        & _s1_sramValid_T},
     {s1_vAddr_0_addr[4:2] < 3'h5 & s1_sramValid_REG | s1_vAddr_0_addr[4:2] > 3'h4
        & _s1_sramValid_T},
     {~(s1_vAddr_0_addr[4]) & s1_sramValid_REG | s1_vAddr_0_addr[4] & _s1_sramValid_T},
     {s1_vAddr_0_addr[4:2] < 3'h3 & s1_sramValid_REG | s1_vAddr_0_addr[4:2] > 3'h2
        & _s1_sramValid_T},
     {s1_vAddr_0_addr[4:2] < 3'h2 & s1_sramValid_REG | (|(s1_vAddr_0_addr[4:3]))
        & _s1_sramValid_T},
     {s1_vAddr_0_addr[4:2] == 3'h0 & s1_sramValid_REG | (|(s1_vAddr_0_addr[4:2]))
        & _s1_sramValid_T}};
  wire             s1_tlException_canAssert_1 = s1_valid & s1_doubleline;
  assign s1_mshrValid =
    {{s1_tlException_canAssert_1}, {s1_valid}} & {2{io_missResp_valid}}
    & {{s1_vAddr_1_addr[12:5] == io_missResp_bits_vSetIdx},
       {s1_vAddr_0_addr[12:5] == io_missResp_bits_vSetIdx}}
    & {{s1_pTag == io_missResp_bits_blkPAddr[41:6]},
       {s1_pTag == io_missResp_bits_blkPAddr[41:6]}};
  wire             _s1_bankMshrValid_T_4 =
    s1_vAddr_0_addr[4:2] == 3'h0 & s1_mshrValid[1'h0] | (|(s1_vAddr_0_addr[4:2]))
    & s1_mshrValid[1'h1];
  wire             _s1_bankMshrValid_T_9 =
    s1_vAddr_0_addr[4:2] < 3'h2 & s1_mshrValid[1'h0] | (|(s1_vAddr_0_addr[4:3]))
    & s1_mshrValid[1'h1];
  wire             _s1_bankMshrValid_T_14 =
    s1_vAddr_0_addr[4:2] < 3'h3 & s1_mshrValid[1'h0] | s1_vAddr_0_addr[4:2] > 3'h2
    & s1_mshrValid[1'h1];
  wire             _s1_bankMshrValid_T_19 =
    ~(s1_vAddr_0_addr[4]) & s1_mshrValid[1'h0] | s1_vAddr_0_addr[4] & s1_mshrValid[1'h1];
  wire             _s1_bankMshrValid_T_24 =
    s1_vAddr_0_addr[4:2] < 3'h5 & s1_mshrValid[1'h0] | s1_vAddr_0_addr[4:2] > 3'h4
    & s1_mshrValid[1'h1];
  wire             _s1_bankMshrValid_T_29 =
    s1_vAddr_0_addr[4:3] != 2'h3 & s1_mshrValid[1'h0] | s1_vAddr_0_addr[4:2] > 3'h5
    & s1_mshrValid[1'h1];
  wire             _s1_bankMshrValid_T_34 =
    s1_vAddr_0_addr[4:2] != 3'h7 & s1_mshrValid[1'h0] | (&(s1_vAddr_0_addr[4:2]))
    & s1_mshrValid[1'h1];
  wire             _s1_hits_T = s1_mshrValid[1'h0] | s1_sramHits[1'h0];
  wire             _s1_tlDenied_T_1 = s1_mshrValid[1'h0] | s1_sramValid_REG;
  reg              s1_hits_r;
  wire             _s1_hits_T_3 = s1_mshrValid[1'h1] | s1_sramHits[1'h1];
  wire             _s1_tlDenied_T_4 = s1_mshrValid[1'h1] | _s1_sramValid_T;
  reg              s1_hits_r_1;
  wire [63:0]      _s1_datas_T =
    _s1_bankMshrValid_T_4 ? io_missResp_bits_data[63:0] : io_dataRead_resp_datas[3'h0];
  wire             _s1_maybeRvcMap_T_10 = _s1_bankMshrValid_T_4 | s1_bankSramValid[3'h0];
  reg  [63:0]      s1_datas_r;
  wire [63:0]      _s1_datas_T_2 = _s1_maybeRvcMap_T_10 ? _s1_datas_T : s1_datas_r;
  wire [63:0]      _s1_datas_T_3 =
    _s1_bankMshrValid_T_9 ? io_missResp_bits_data[127:64] : io_dataRead_resp_datas[3'h1];
  wire             _s1_maybeRvcMap_T_22 = _s1_bankMshrValid_T_9 | s1_bankSramValid[3'h1];
  reg  [63:0]      s1_datas_r_1;
  wire [63:0]      _s1_datas_T_5 = _s1_maybeRvcMap_T_22 ? _s1_datas_T_3 : s1_datas_r_1;
  wire [63:0]      _s1_datas_T_6 =
    _s1_bankMshrValid_T_14
      ? io_missResp_bits_data[191:128]
      : io_dataRead_resp_datas[3'h2];
  wire             _s1_maybeRvcMap_T_34 = _s1_bankMshrValid_T_14 | s1_bankSramValid[3'h2];
  reg  [63:0]      s1_datas_r_2;
  wire [63:0]      _s1_datas_T_8 = _s1_maybeRvcMap_T_34 ? _s1_datas_T_6 : s1_datas_r_2;
  wire [63:0]      _s1_datas_T_9 =
    _s1_bankMshrValid_T_19
      ? io_missResp_bits_data[255:192]
      : io_dataRead_resp_datas[3'h3];
  wire             _s1_maybeRvcMap_T_46 = _s1_bankMshrValid_T_19 | s1_bankSramValid[3'h3];
  reg  [63:0]      s1_datas_r_3;
  wire [63:0]      _s1_datas_T_11 = _s1_maybeRvcMap_T_46 ? _s1_datas_T_9 : s1_datas_r_3;
  wire [63:0]      _s1_datas_T_12 =
    _s1_bankMshrValid_T_24
      ? io_missResp_bits_data[319:256]
      : io_dataRead_resp_datas[3'h4];
  wire             _s1_maybeRvcMap_T_58 = _s1_bankMshrValid_T_24 | s1_bankSramValid[3'h4];
  reg  [63:0]      s1_datas_r_4;
  wire [63:0]      _s1_datas_T_14 = _s1_maybeRvcMap_T_58 ? _s1_datas_T_12 : s1_datas_r_4;
  wire [63:0]      _s1_datas_T_15 =
    _s1_bankMshrValid_T_29
      ? io_missResp_bits_data[383:320]
      : io_dataRead_resp_datas[3'h5];
  wire             _s1_maybeRvcMap_T_70 = _s1_bankMshrValid_T_29 | s1_bankSramValid[3'h5];
  reg  [63:0]      s1_datas_r_5;
  wire [63:0]      _s1_datas_T_17 = _s1_maybeRvcMap_T_70 ? _s1_datas_T_15 : s1_datas_r_5;
  wire [63:0]      _s1_datas_T_18 =
    _s1_bankMshrValid_T_34
      ? io_missResp_bits_data[447:384]
      : io_dataRead_resp_datas[3'h6];
  wire             _s1_maybeRvcMap_T_82 = _s1_bankMshrValid_T_34 | s1_bankSramValid[3'h6];
  reg  [63:0]      s1_datas_r_6;
  wire [63:0]      _s1_datas_T_20 = _s1_maybeRvcMap_T_82 ? _s1_datas_T_18 : s1_datas_r_6;
  wire [63:0]      _s1_datas_T_21 =
    s1_mshrValid[1'h0] ? io_missResp_bits_data[511:448] : io_dataRead_resp_datas[3'h7];
  wire             _s1_maybeRvcMap_T_94 = s1_mshrValid[1'h0] | s1_bankSramValid[3'h7];
  reg  [63:0]      s1_datas_r_7;
  wire [63:0]      _s1_datas_T_23 = _s1_maybeRvcMap_T_94 ? _s1_datas_T_21 : s1_datas_r_7;
  wire [7:0][63:0] s1_datas =
    {{_s1_datas_T_23},
     {_s1_datas_T_20},
     {_s1_datas_T_17},
     {_s1_datas_T_14},
     {_s1_datas_T_11},
     {_s1_datas_T_8},
     {_s1_datas_T_5},
     {_s1_datas_T_2}};
  wire [7:0][63:0] difftest_refill_data;
  assign difftest_refill_data = s1_datas;
  wire [7:0][63:0] difftest_refill_1_data;
  assign difftest_refill_1_data = s1_datas;
  wire [3:0]       _s1_maybeRvcMap_T_9 =
    _s1_bankMshrValid_T_4
      ? io_missResp_bits_maybeRvcMap[3:0]
      : (|(s1_vAddr_0_addr[4:2]))
          ? s1_sramMaybeRvcMapRaw[1'h1][3:0]
          : s1_sramMaybeRvcMapRaw[1'h0][3:0];
  reg  [3:0]       s1_maybeRvcMap_r;
  wire [3:0]       _s1_maybeRvcMap_T_21 =
    _s1_bankMshrValid_T_9
      ? io_missResp_bits_maybeRvcMap[7:4]
      : (|(s1_vAddr_0_addr[4:3]))
          ? s1_sramMaybeRvcMapRaw[1'h1][7:4]
          : s1_sramMaybeRvcMapRaw[1'h0][7:4];
  reg  [3:0]       s1_maybeRvcMap_r_1;
  wire [3:0]       _s1_maybeRvcMap_T_33 =
    _s1_bankMshrValid_T_14
      ? io_missResp_bits_maybeRvcMap[11:8]
      : s1_vAddr_0_addr[4:2] > 3'h2
          ? s1_sramMaybeRvcMapRaw[1'h1][11:8]
          : s1_sramMaybeRvcMapRaw[1'h0][11:8];
  reg  [3:0]       s1_maybeRvcMap_r_2;
  wire [3:0]       _s1_maybeRvcMap_T_45 =
    _s1_bankMshrValid_T_19
      ? io_missResp_bits_maybeRvcMap[15:12]
      : s1_vAddr_0_addr[4]
          ? s1_sramMaybeRvcMapRaw[1'h1][15:12]
          : s1_sramMaybeRvcMapRaw[1'h0][15:12];
  reg  [3:0]       s1_maybeRvcMap_r_3;
  wire [3:0]       _s1_maybeRvcMap_T_57 =
    _s1_bankMshrValid_T_24
      ? io_missResp_bits_maybeRvcMap[19:16]
      : s1_vAddr_0_addr[4:2] > 3'h4
          ? s1_sramMaybeRvcMapRaw[1'h1][19:16]
          : s1_sramMaybeRvcMapRaw[1'h0][19:16];
  reg  [3:0]       s1_maybeRvcMap_r_4;
  wire [3:0]       _s1_maybeRvcMap_T_69 =
    _s1_bankMshrValid_T_29
      ? io_missResp_bits_maybeRvcMap[23:20]
      : s1_vAddr_0_addr[4:2] > 3'h5
          ? s1_sramMaybeRvcMapRaw[1'h1][23:20]
          : s1_sramMaybeRvcMapRaw[1'h0][23:20];
  reg  [3:0]       s1_maybeRvcMap_r_5;
  wire [3:0]       _s1_maybeRvcMap_T_81 =
    _s1_bankMshrValid_T_34
      ? io_missResp_bits_maybeRvcMap[27:24]
      : (&(s1_vAddr_0_addr[4:2]))
          ? s1_sramMaybeRvcMapRaw[1'h1][27:24]
          : s1_sramMaybeRvcMapRaw[1'h0][27:24];
  reg  [3:0]       s1_maybeRvcMap_r_6;
  wire [3:0]       _s1_maybeRvcMap_T_93 =
    s1_mshrValid[1'h0]
      ? io_missResp_bits_maybeRvcMap[31:28]
      : s1_sramMaybeRvcMapRaw[1'h0][31:28];
  reg  [3:0]       s1_maybeRvcMap_r_7;
  wire             _s1_tlCorrupt_T = s1_mshrValid[1'h0] & io_missResp_bits_corrupt;
  reg              s1_tlCorrupt_r;
  wire             _s1_tlCorrupt_T_2 =
    _s1_tlDenied_T_1 ? _s1_tlCorrupt_T : s1_tlCorrupt_r;
  wire             _s1_tlCorrupt_T_3 = s1_mshrValid[1'h1] & io_missResp_bits_corrupt;
  reg              s1_tlCorrupt_r_1;
  wire             _s1_tlDenied_T = s1_mshrValid[1'h0] & io_missResp_bits_denied;
  reg              s1_tlDenied_r;
  wire             _s1_tlDenied_T_2 = _s1_tlDenied_T_1 ? _s1_tlDenied_T : s1_tlDenied_r;
  wire             _s1_tlDenied_T_3 = s1_mshrValid[1'h1] & io_missResp_bits_denied;
  reg              s1_tlDenied_r_1;
  reg              io_replacerTouch_req_0_valid_REG;
  reg              io_replacerTouch_req_1_valid_REG;
  wire [2:0]       s1_exception_value =
    (|s1_itlbException_value) ? s1_itlbException_value : io_pmp_resp_instr ? 3'h3 : 3'h0;
  wire [2:0]       s1_metaCorrupt_hitNum =
    3'({1'h0, 2'({1'h0, s1_waymasks[1'h0][0]} + {1'h0, s1_waymasks[1'h0][1]})}
       + {1'h0, 2'({1'h0, s1_waymasks[1'h0][2]} + {1'h0, s1_waymasks[1'h0][3]})});
  wire [2:0]       s1_metaCorrupt_hitNum_1 =
    3'({1'h0, 2'({1'h0, s1_waymasks[1'h1][0]} + {1'h0, s1_waymasks[1'h1][1]})}
       + {1'h0, 2'({1'h0, s1_waymasks[1'h1][2]} + {1'h0, s1_waymasks[1'h1][3]})});
  assign s1_metaCorrupt =
    {{io_eccEnable
        & (^{s1_pTag, s1_sramMaybeRvcMapRaw[1'h1]} != s1_metaCodes[1'h1]
           & s1_metaCorrupt_hitNum_1 == 3'h1 | (|(s1_metaCorrupt_hitNum_1[2:1])))},
     {io_eccEnable}}
    & {{s1_doubleline},
       {^{s1_pTag, s1_sramMaybeRvcMapRaw[1'h0]} != s1_metaCodes[1'h0]
          & s1_metaCorrupt_hitNum == 3'h1 | (|(s1_metaCorrupt_hitNum[2:1]))}};
  wire [7:0]       _GEN =
    {8{io_eccEnable}}
    & {{^io_dataRead_resp_datas[3'h7] != io_dataRead_resp_codes[3'h7]},
       {^io_dataRead_resp_datas[3'h6] != io_dataRead_resp_codes[3'h6]},
       {^io_dataRead_resp_datas[3'h5] != io_dataRead_resp_codes[3'h5]},
       {^io_dataRead_resp_datas[3'h4] != io_dataRead_resp_codes[3'h4]},
       {^io_dataRead_resp_datas[3'h3] != io_dataRead_resp_codes[3'h3]},
       {^io_dataRead_resp_datas[3'h2] != io_dataRead_resp_codes[3'h2]},
       {^io_dataRead_resp_datas[3'h1] != io_dataRead_resp_codes[3'h1]},
       {^io_dataRead_resp_datas[3'h0] != io_dataRead_resp_codes[3'h0]}};
  wire [7:0]       _GEN_0 = s1_bankSramValid;
  assign _s1_dataCorrupt_WIRE_3 = _GEN & _s1_dataCorrupt_WIRE & _GEN_0;
  assign _s1_dataCorrupt_WIRE_4 = _GEN & _s1_dataCorrupt_WIRE_1 & _GEN_0;
  assign s1_dataCorrupt =
    ({{_s1_dataCorrupt_WIRE_4[3'h0]}, {_s1_dataCorrupt_WIRE_3[3'h0]}}
     | {{_s1_dataCorrupt_WIRE_4[3'h1]}, {_s1_dataCorrupt_WIRE_3[3'h1]}}
     | {{_s1_dataCorrupt_WIRE_4[3'h2]}, {_s1_dataCorrupt_WIRE_3[3'h2]}}
     | {{_s1_dataCorrupt_WIRE_4[3'h3]}, {_s1_dataCorrupt_WIRE_3[3'h3]}}
     | {{_s1_dataCorrupt_WIRE_4[3'h4]}, {_s1_dataCorrupt_WIRE_3[3'h4]}}
     | {{_s1_dataCorrupt_WIRE_4[3'h5]}, {_s1_dataCorrupt_WIRE_3[3'h5]}}
     | {{_s1_dataCorrupt_WIRE_4[3'h6]}, {_s1_dataCorrupt_WIRE_3[3'h6]}}
     | {{_s1_dataCorrupt_WIRE_4[3'h7]}, {_s1_dataCorrupt_WIRE_3[3'h7]}}) & s1_sramHits;
  wire             _io_errors_1_bits_report_to_beu_T =
    s1_metaCorrupt[1'h1] | s1_dataCorrupt[1'h1];
  wire             _io_errors_0_bits_report_to_beu_T =
    s1_metaCorrupt[1'h0] | s1_dataCorrupt[1'h0];
  reg              io_errors_0_valid_REG;
  reg              io_errors_0_bits_report_to_beu_REG;
  reg              io_errors_1_valid_REG;
  reg              io_errors_1_bits_report_to_beu_REG;
  reg              REG;
  wire             _GEN_1 = s1_dataCorrupt[1'h0] & REG;
  reg              REG_1;
  wire             _GEN_2 = s1_dataCorrupt[1'h1] & REG_1;
  reg              REG_2;
  wire             _GEN_3 = s1_metaCorrupt[1'h0] & REG_2;
  reg              REG_3;
  wire             _GEN_4 = s1_metaCorrupt[1'h1] & REG_3;
  wire             s1_isMmio =
    io_pmp_resp_mmio | s1_itlbPbmt == 2'h1 | s1_itlbPbmt == 2'h2;
  wire             _s1_shouldFetch_T_10 = s1_exception_value == 3'h0;
  assign s1_shouldFetch =
    {{~(_s1_tlDenied_T_4 ? _s1_hits_T_3 : s1_hits_r_1) & s1_doubleline},
     {~(_s1_tlDenied_T_1 ? _s1_hits_T : s1_hits_r)}}
    & {{_s1_shouldFetch_T_10}, {_s1_shouldFetch_T_10}} & {{~s1_isMmio}, {~s1_isMmio}};
  reg              s1_hasSend_valid;
  reg              s1_hasSend_valid_1;
  wire             toMissArbiter_io_in_0_valid =
    s1_valid & s1_shouldFetch[1'h0] & ~s1_hasSend_valid & ~s1_flush;
  wire             toMissArbiter_io_in_1_valid =
    s1_valid & s1_shouldFetch[1'h1] & ~s1_hasSend_valid_1 & ~s1_flush;
  wire             _GEN_5 = _toMissArbiter_io_out_valid & ~io_missReq_ready;
  wire             _io_perf_pendingMiss_T = s1_shouldFetch[1'h0] | s1_shouldFetch[1'h1];
  wire             _s1_tlException_T_8 = _s1_tlCorrupt_T_2 & ~_s1_tlDenied_T_2;
  wire [2:0]       _s1_tlException_T_26_value =
    _s1_tlDenied_T_2 ? 3'h3 : _s1_tlException_T_8 ? 3'h5 : 3'h0;
  wire             s1_tlException_realCorrupt_1 =
    (_s1_tlDenied_T_4 ? _s1_tlCorrupt_T_3 : s1_tlCorrupt_r_1) & s1_doubleline;
  wire             s1_tlException_realDenied_1 =
    (_s1_tlDenied_T_4 ? _s1_tlDenied_T_3 : s1_tlDenied_r_1) & s1_doubleline;
  wire             _s1_tlException_T_35 =
    s1_tlException_realCorrupt_1 & ~s1_tlException_realDenied_1;
  wire             _s1_eccException_T_2 =
    s1_metaCorrupt[1'h0] | s1_metaCorrupt[1'h1] | s1_dataCorrupt[1'h0]
    | s1_dataCorrupt[1'h1];
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (s0_fire & ~reset
          & ~(io_req_bits_startVAddr_addr[12:5] == io_wayLookupRead_bits_entry_vSetIdx[1'h0]
              & io_req_bits_nextCachelineVAddr_addr[12:5] == io_wayLookupRead_bits_entry_vSetIdx[1'h1])) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: vSetIdx from ftq and wayLookup mismatch! vAddr=0x%x ftq: vSet0=0x%x vSet1=0x%x wayLookup: vSet0=0x%x vSet1=0x%x\n",
                 {io_req_bits_startVAddr_addr, 1'h0}, io_req_bits_startVAddr_addr[12:5],
                 io_req_bits_nextCachelineVAddr_addr[12:5],
                 io_wayLookupRead_bits_entry_vSetIdx[1'h0],
                 io_wayLookupRead_bits_entry_vSetIdx[1'h1]);
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset & ~s1_doubleline & _io_errors_1_bits_report_to_beu_T) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: meta or data corrupt detected on line 1 but s2_doubleline is false.B\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset & ~(~s1_valid | ~(_s1_tlDenied_T_2 & ~_s1_tlCorrupt_T_2))) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: TileLink response should not be denied but !corrupt\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset
          & ~(~s1_valid
              | {1'h0,
                 2'({1'h0, _s1_tlException_T_8}
                    + {1'h0, _s1_tlDenied_T_2})} < 3'h2)) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: ExceptionType receives input that is not one-hot: pf=%d, gpf=%d, af=%d, ill=%d, hwe=%d\n",
                 1'h0, 1'h0, _s1_tlDenied_T_2, 1'h0, _s1_tlException_T_8);
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset
          & ~(~s1_tlException_canAssert_1
              | ~(s1_tlException_realDenied_1 & ~s1_tlException_realCorrupt_1))) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: TileLink response should not be denied but !corrupt\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset
          & ~(~s1_tlException_canAssert_1
              | {1'h0,
                 2'({1'h0, _s1_tlException_T_35}
                    + {1'h0, s1_tlException_realDenied_1})} < 3'h2)) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: ExceptionType receives input that is not one-hot: pf=%d, gpf=%d, af=%d, ill=%d, hwe=%d\n",
                 1'h0, 1'h0, s1_tlException_realDenied_1, 1'h0, _s1_tlException_T_35);
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset & ~(~s1_valid | {2'h0, _s1_eccException_T_2} < 3'h2)) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: ExceptionType receives input that is not one-hot: pf=%d, gpf=%d, af=%d, ill=%d, hwe=%d\n",
                 1'h0, 1'h0, 1'h0, 1'h0, _s1_eccException_T_2);
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [2:0]       _s1_exceptionOut_T_1_value =
    (|s1_exception_value)
      ? s1_exception_value
      : (|_s1_tlException_T_26_value)
          ? _s1_tlException_T_26_value
          : s1_tlException_realDenied_1 ? 3'h3 : _s1_tlException_T_35 ? 3'h5 : 3'h0;
  assign s1_flush =
    io_flush | s1_valid & io_flushFromBpu_s3_valid
    & (io_flushFromBpu_s3_bits_flag ^ s1_ftqIdx_flag
       ^ io_flushFromBpu_s3_bits_value <= s1_ftqIdx_value);
  assign s1_ready = ~_io_perf_pendingMiss_T & ~io_respStall | ~s1_valid;
  wire             s1_fire =
    s1_valid & ~_io_perf_pendingMiss_T & ~io_respStall & ~s1_flush;
  reg  [1:0]       s1_rawHits;
  wire             _GEN_6 = ~s1_fire;
  wire             _GEN_7 = io_req_valid & ~io_wayLookupRead_valid;
  wire             _GEN_8 = io_req_valid & ~io_dataRead_req_ready;
  wire             _GEN_9 = s1_valid & _io_perf_pendingMiss_T;
  wire             _bankSel_T_38 = s1_blkEndOffset[5:3] > 3'h2;
  wire             _bankSel_T_42 = s1_blkEndOffset[5:3] > 3'h4;
  wire             _bankSel_T_44 = s1_blkEndOffset[5:3] > 3'h5;
  wire [63:0]      difftest_refill_addr;
  wire [7:0]       difftest_refill_mask;
  wire [7:0]       difftest_refill_coreid;
  wire [7:0]       difftest_coreid = {2'h0, io_hartId};
  assign difftest_refill_coreid = difftest_coreid;
  wire [7:0]       difftest_refill_1_coreid;
  assign difftest_refill_1_coreid = difftest_coreid;
  assign difftest_refill_addr = {16'h0, s1_pTag, s1_vAddr_0_addr[10:5], 6'h0};
  assign difftest_refill_mask =
    {s1_doubleline | (&(s1_blkEndOffset[5:3])),
     s1_vAddr_0_addr[4:2] != 3'h7 & (s1_doubleline | _bankSel_T_44),
     s1_vAddr_0_addr[4:3] != 2'h3 & (s1_doubleline | _bankSel_T_42),
     s1_vAddr_0_addr[4:2] < 3'h5 & (s1_doubleline | s1_blkEndOffset[5]),
     ~(s1_vAddr_0_addr[4]) & (s1_doubleline | _bankSel_T_38),
     s1_vAddr_0_addr[4:2] < 3'h3 & (s1_doubleline | (|(s1_blkEndOffset[5:4]))),
     s1_vAddr_0_addr[4:2] < 3'h2 & (s1_doubleline | (|(s1_blkEndOffset[5:3]))),
     s1_vAddr_0_addr[4:2] == 3'h0};
  wire [63:0]      difftest_refill_1_addr;
  wire [7:0]       difftest_refill_1_mask;
  assign difftest_refill_1_addr = {16'h0, s1_pTag, s1_vAddr_1_addr[10:5], 6'h0};
  assign difftest_refill_1_mask =
    {(&(s1_blkEndOffset[5:3])) & s1_doubleline,
     _bankSel_T_44 & s1_doubleline,
     _bankSel_T_42 & s1_doubleline,
     s1_blkEndOffset[5] & s1_doubleline,
     _bankSel_T_38 & s1_doubleline,
     (|(s1_blkEndOffset[5:4])) & s1_doubleline,
     (|(s1_blkEndOffset[5:3])) & s1_doubleline,
     s1_doubleline};
  assign _s1_dataCorrupt_WIRE =
    {{s1_doubleline},
     {s1_vAddr_0_addr[4:2] != 3'h7 & s1_doubleline},
     {s1_vAddr_0_addr[4:3] != 2'h3 & s1_doubleline},
     {s1_vAddr_0_addr[4:2] < 3'h5 & s1_doubleline},
     {~(s1_vAddr_0_addr[4]) & s1_doubleline},
     {s1_vAddr_0_addr[4:2] < 3'h3 & s1_doubleline},
     {s1_vAddr_0_addr[4:2] < 3'h2 & s1_doubleline},
     {s1_vAddr_0_addr[4:2] == 3'h0}};
  assign _s1_dataCorrupt_WIRE_1 =
    {{1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {1'h0}, {s1_doubleline}};
  wire [1:0]       _s1_metaCodes_r_WIRE = '{1'h0, 1'h0};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      cntFtqFireInterval <= 32'h0;
      s1_valid <= 1'h0;
      s1_ftqIdx_flag <= 1'h0;
      s1_ftqIdx_value <= 6'h0;
      s1_vAddr_0_addr <= 49'h0;
      s1_vAddr_1_addr <= 49'h0;
      s1_pTag <= 36'h0;
      s1_gpAddr_addr <= 55'h0;
      s1_isForVSnonLeafPTE <= 1'h0;
      s1_doubleline <= 1'h0;
      s1_itlbException_value <= 3'h0;
      s1_isBackendException <= 1'h0;
      s1_itlbPbmt <= 2'h0;
      s1_waymasks <= '{4'h0, 4'h0};
      s1_sramMaybeRvcMapRaw <= '{32'h0, 32'h0};
      s1_metaCodes <= _s1_metaCodes_r_WIRE;
      s1_blkEndOffset <= 6'h0;
      s1_sramHits <= _s1_metaCodes_r_WIRE;
      s1_hasSend_valid <= 1'h0;
      s1_hasSend_valid_1 <= 1'h0;
      s1_rawHits <= _s1_metaCodes_r_WIRE;
    end
    else begin
      cntFtqFireInterval <= x3_probe ? 32'h1 : 32'(cntFtqFireInterval + 32'h1);
      s1_valid <= ~s1_flush & (s0_fire | ~s1_fire & s1_valid);
      if (s0_fire) begin
        s1_ftqIdx_flag <= io_req_bits_ftqIdx_flag;
        s1_ftqIdx_value <= io_req_bits_ftqIdx_value;
        s1_vAddr_0_addr <= io_req_bits_startVAddr_addr;
        s1_vAddr_1_addr <= io_req_bits_nextCachelineVAddr_addr;
        s1_pTag <= io_wayLookupRead_bits_entry_pTag;
        s1_gpAddr_addr <= io_wayLookupRead_bits_exceptionEntry_gpAddr_addr;
        s1_isForVSnonLeafPTE <= io_wayLookupRead_bits_exceptionEntry_isForVSnonLeafPTE;
        s1_doubleline <= s0_doubleline;
        s1_itlbException_value <=
          io_wayLookupRead_bits_exceptionEntry_itlbException_value;
        s1_isBackendException <= io_req_bits_isBackendException;
        s1_itlbPbmt <= io_wayLookupRead_bits_entry_itlbPbmt;
        s1_waymasks <= io_wayLookupRead_bits_entry_waymask;
        s1_sramMaybeRvcMapRaw <= io_wayLookupRead_bits_entry_maybeRvcMap;
        s1_metaCodes <= io_wayLookupRead_bits_entry_metaCodes;
        s1_blkEndOffset <= s0_blkEndOffsetTmp[5:0];
        s1_sramHits[1'h1] <= |io_wayLookupRead_bits_entry_waymask[1'h1];
        s1_sramHits[1'h0] <= |io_wayLookupRead_bits_entry_waymask[1'h0];
        s1_rawHits[1'h1] <= |io_wayLookupRead_bits_entry_waymask[1'h1];
        s1_rawHits[1'h0] <= |io_wayLookupRead_bits_entry_waymask[1'h0];
      end
      s1_hasSend_valid <=
        ~s1_flush
        & (_toMissArbiter_io_in_0_ready & toMissArbiter_io_in_0_valid | ~s1_fire
           & s1_hasSend_valid);
      s1_hasSend_valid_1 <=
        ~s1_flush
        & (_toMissArbiter_io_in_1_ready & toMissArbiter_io_in_1_valid | ~s1_fire
           & s1_hasSend_valid_1);
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    s1_sramValid_REG <= s0_fire;
    s1_sramValid_REG_1 <= s0_fire;
    if (_s1_tlDenied_T_1) begin
      s1_hits_r <= _s1_hits_T;
      s1_tlCorrupt_r <= _s1_tlCorrupt_T;
      s1_tlDenied_r <= _s1_tlDenied_T;
    end
    if (_s1_tlDenied_T_4) begin
      s1_hits_r_1 <= _s1_hits_T_3;
      s1_tlCorrupt_r_1 <= _s1_tlCorrupt_T_3;
      s1_tlDenied_r_1 <= _s1_tlDenied_T_3;
    end
    if (_s1_maybeRvcMap_T_10) begin
      s1_datas_r <= _s1_datas_T;
      s1_maybeRvcMap_r <= _s1_maybeRvcMap_T_9;
    end
    if (_s1_maybeRvcMap_T_22) begin
      s1_datas_r_1 <= _s1_datas_T_3;
      s1_maybeRvcMap_r_1 <= _s1_maybeRvcMap_T_21;
    end
    if (_s1_maybeRvcMap_T_34) begin
      s1_datas_r_2 <= _s1_datas_T_6;
      s1_maybeRvcMap_r_2 <= _s1_maybeRvcMap_T_33;
    end
    if (_s1_maybeRvcMap_T_46) begin
      s1_datas_r_3 <= _s1_datas_T_9;
      s1_maybeRvcMap_r_3 <= _s1_maybeRvcMap_T_45;
    end
    if (_s1_maybeRvcMap_T_58) begin
      s1_datas_r_4 <= _s1_datas_T_12;
      s1_maybeRvcMap_r_4 <= _s1_maybeRvcMap_T_57;
    end
    if (_s1_maybeRvcMap_T_70) begin
      s1_datas_r_5 <= _s1_datas_T_15;
      s1_maybeRvcMap_r_5 <= _s1_maybeRvcMap_T_69;
    end
    if (_s1_maybeRvcMap_T_82) begin
      s1_datas_r_6 <= _s1_datas_T_18;
      s1_maybeRvcMap_r_6 <= _s1_maybeRvcMap_T_81;
    end
    if (_s1_maybeRvcMap_T_94) begin
      s1_datas_r_7 <= _s1_datas_T_21;
      s1_maybeRvcMap_r_7 <= _s1_maybeRvcMap_T_93;
    end
    io_replacerTouch_req_0_valid_REG <= s0_fire;
    io_replacerTouch_req_1_valid_REG <= s0_fire;
    io_errors_0_valid_REG <= s0_fire;
    io_errors_0_bits_report_to_beu_REG <= s0_fire;
    io_errors_1_valid_REG <= s0_fire;
    io_errors_1_bits_report_to_beu_REG <= s0_fire;
    REG <= s0_fire;
    REG_1 <= s0_fire;
    REG_2 <= s0_fire;
    REG_3 <= s0_fire;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:27];
    wire  [1:0]  _s1_metaCodes_r_WIRE_0 = '{1'h0, 1'h0};
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h1C; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        cntFtqFireInterval = _RANDOM[5'h0];
        s1_valid = _RANDOM[5'h1][0];
        s1_ftqIdx_flag = _RANDOM[5'h1][1];
        s1_ftqIdx_value = _RANDOM[5'h1][7:2];
        s1_vAddr_0_addr = {_RANDOM[5'h1][31:8], _RANDOM[5'h2][24:0]};
        s1_vAddr_1_addr = {_RANDOM[5'h2][31:25], _RANDOM[5'h3], _RANDOM[5'h4][9:0]};
        s1_pTag = {_RANDOM[5'h4][31:10], _RANDOM[5'h5][13:0]};
        s1_gpAddr_addr = {_RANDOM[5'h5][31:14], _RANDOM[5'h6], _RANDOM[5'h7][4:0]};
        s1_isForVSnonLeafPTE = _RANDOM[5'h7][5];
        s1_doubleline = _RANDOM[5'h7][6];
        s1_itlbException_value = _RANDOM[5'h7][9:7];
        s1_isBackendException = _RANDOM[5'h7][10];
        s1_itlbPbmt = _RANDOM[5'h7][12:11];
        s1_waymasks[1'h0] = _RANDOM[5'h7][20:17];
        s1_waymasks[1'h1] = _RANDOM[5'h7][16:13];
        s1_sramMaybeRvcMapRaw[1'h0] = {_RANDOM[5'h7][31:21], _RANDOM[5'h8][31:11]};
        s1_sramMaybeRvcMapRaw[1'h1] = {_RANDOM[5'h8][10:0], _RANDOM[5'h9][20:0]};
        s1_metaCodes[1'h0] = _RANDOM[5'h9][22];
        s1_metaCodes[1'h1] = _RANDOM[5'h9][21];
        s1_blkEndOffset = _RANDOM[5'h9][28:23];
        s1_sramHits[1'h0] = _RANDOM[5'h9][30];
        s1_sramHits[1'h1] = _RANDOM[5'h9][29];
        s1_sramValid_REG = _RANDOM[5'h9][31];
        s1_sramValid_REG_1 = _RANDOM[5'hA][0];
        s1_hits_r = _RANDOM[5'hA][1];
        s1_hits_r_1 = _RANDOM[5'hA][2];
        s1_datas_r = {_RANDOM[5'hA][31:3], _RANDOM[5'hB], _RANDOM[5'hC][2:0]};
        s1_datas_r_1 = {_RANDOM[5'hC][31:3], _RANDOM[5'hD], _RANDOM[5'hE][2:0]};
        s1_datas_r_2 = {_RANDOM[5'hE][31:3], _RANDOM[5'hF], _RANDOM[5'h10][2:0]};
        s1_datas_r_3 = {_RANDOM[5'h10][31:3], _RANDOM[5'h11], _RANDOM[5'h12][2:0]};
        s1_datas_r_4 = {_RANDOM[5'h12][31:3], _RANDOM[5'h13], _RANDOM[5'h14][2:0]};
        s1_datas_r_5 = {_RANDOM[5'h14][31:3], _RANDOM[5'h15], _RANDOM[5'h16][2:0]};
        s1_datas_r_6 = {_RANDOM[5'h16][31:3], _RANDOM[5'h17], _RANDOM[5'h18][2:0]};
        s1_datas_r_7 = {_RANDOM[5'h18][31:3], _RANDOM[5'h19], _RANDOM[5'h1A][2:0]};
        s1_maybeRvcMap_r = _RANDOM[5'h1A][6:3];
        s1_maybeRvcMap_r_1 = _RANDOM[5'h1A][10:7];
        s1_maybeRvcMap_r_2 = _RANDOM[5'h1A][14:11];
        s1_maybeRvcMap_r_3 = _RANDOM[5'h1A][18:15];
        s1_maybeRvcMap_r_4 = _RANDOM[5'h1A][22:19];
        s1_maybeRvcMap_r_5 = _RANDOM[5'h1A][26:23];
        s1_maybeRvcMap_r_6 = _RANDOM[5'h1A][30:27];
        s1_maybeRvcMap_r_7 = {_RANDOM[5'h1A][31], _RANDOM[5'h1B][2:0]};
        s1_tlCorrupt_r = _RANDOM[5'h1B][3];
        s1_tlCorrupt_r_1 = _RANDOM[5'h1B][4];
        s1_tlDenied_r = _RANDOM[5'h1B][5];
        s1_tlDenied_r_1 = _RANDOM[5'h1B][6];
        io_replacerTouch_req_0_valid_REG = _RANDOM[5'h1B][7];
        io_replacerTouch_req_1_valid_REG = _RANDOM[5'h1B][8];
        io_errors_0_valid_REG = _RANDOM[5'h1B][9];
        io_errors_0_bits_report_to_beu_REG = _RANDOM[5'h1B][10];
        io_errors_1_valid_REG = _RANDOM[5'h1B][11];
        io_errors_1_bits_report_to_beu_REG = _RANDOM[5'h1B][12];
        REG = _RANDOM[5'h1B][13];
        REG_1 = _RANDOM[5'h1B][14];
        REG_2 = _RANDOM[5'h1B][15];
        REG_3 = _RANDOM[5'h1B][16];
        s1_hasSend_valid = _RANDOM[5'h1B][17];
        s1_hasSend_valid_1 = _RANDOM[5'h1B][18];
        s1_rawHits[1'h0] = _RANDOM[5'h1B][20];
        s1_rawHits[1'h1] = _RANDOM[5'h1B][19];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        cntFtqFireInterval = 32'h0;
        s1_valid = 1'h0;
        s1_ftqIdx_flag = 1'h0;
        s1_ftqIdx_value = 6'h0;
        s1_vAddr_0_addr = 49'h0;
        s1_vAddr_1_addr = 49'h0;
        s1_pTag = 36'h0;
        s1_gpAddr_addr = 55'h0;
        s1_isForVSnonLeafPTE = 1'h0;
        s1_doubleline = 1'h0;
        s1_itlbException_value = 3'h0;
        s1_isBackendException = 1'h0;
        s1_itlbPbmt = 2'h0;
        s1_waymasks = '{4'h0, 4'h0};
        s1_sramMaybeRvcMapRaw = '{32'h0, 32'h0};
        s1_metaCodes = _s1_metaCodes_r_WIRE_0;
        s1_blkEndOffset = 6'h0;
        s1_sramHits = _s1_metaCodes_r_WIRE_0;
        s1_hasSend_valid = 1'h0;
        s1_hasSend_valid_1 = 1'h0;
        s1_rawHits = _s1_metaCodes_r_WIRE_0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Arbiter2_MissReqBundle toMissArbiter (
    .io_in_0_ready         (_toMissArbiter_io_in_0_ready),
    .io_in_0_valid         (toMissArbiter_io_in_0_valid),
    .io_in_0_bits_blkPAddr ({s1_pTag, s1_vAddr_0_addr[10:5]}),
    .io_in_0_bits_vSetIdx  (s1_vAddr_0_addr[12:5]),
    .io_in_1_ready         (_toMissArbiter_io_in_1_ready),
    .io_in_1_valid         (toMissArbiter_io_in_1_valid),
    .io_in_1_bits_blkPAddr ({s1_pTag, s1_vAddr_1_addr[10:5]}),
    .io_in_1_bits_vSetIdx  (s1_vAddr_1_addr[12:5]),
    .io_out_ready          (io_missReq_ready),
    .io_out_valid          (_toMissArbiter_io_out_valid),
    .io_out_bits_blkPAddr  (io_missReq_bits_blkPAddr),
    .io_out_bits_vSetIdx   (io_missReq_bits_vSetIdx)
  );
  assign io_dataRead_req_valid = io_req_valid;
  assign io_dataRead_req_bits_vSetIdx =
    {{io_req_bits_nextCachelineVAddr_addr[12:5]}, {io_req_bits_startVAddr_addr[12:5]}};
  assign io_dataRead_req_bits_isDoubleLine = s0_doubleline;
  assign io_dataRead_req_bits_waymask = io_wayLookupRead_bits_entry_waymask;
  assign io_dataRead_req_bits_blkOffset = {io_req_bits_startVAddr_addr[4:0], 1'h0};
  assign io_dataRead_req_bits_blkEndOffset = s0_blkEndOffsetTmp[5:0];
  assign io_replacerTouch_req_0_valid =
    io_replacerTouch_req_0_valid_REG & s1_sramHits[1'h0];
  assign io_replacerTouch_req_0_bits_vSetIdx = s1_vAddr_0_addr[12:5];
  assign io_replacerTouch_req_0_bits_way =
    {|(s1_waymasks[1'h0][3:2]), s1_waymasks[1'h0][3] | s1_waymasks[1'h0][1]};
  assign io_replacerTouch_req_1_valid =
    io_replacerTouch_req_1_valid_REG & s1_sramHits[1'h1] & s1_doubleline;
  assign io_replacerTouch_req_1_bits_vSetIdx = s1_vAddr_1_addr[12:5];
  assign io_replacerTouch_req_1_bits_way =
    {|(s1_waymasks[1'h1][3:2]), s1_waymasks[1'h1][3] | s1_waymasks[1'h1][1]};
  assign io_wayLookupRead_ready = s0_fire;
  assign io_missReq_valid = _toMissArbiter_io_out_valid;
  assign io_req_ready = s0_canGo;
  assign io_pmp_req_bits_addr = {s1_pTag, s1_vAddr_0_addr[10:0], 1'h0};
  assign io_resp_valid = s1_fire;
  assign io_resp_bits_doubleline = s1_doubleline;
  assign io_resp_bits_vAddr_0_addr = s1_vAddr_0_addr;
  assign io_resp_bits_data =
    {_s1_datas_T_23,
     _s1_datas_T_20,
     _s1_datas_T_17,
     _s1_datas_T_14,
     _s1_datas_T_11,
     _s1_datas_T_8,
     _s1_datas_T_5,
     _s1_datas_T_2};
  assign io_resp_bits_maybeRvcMap =
    {_s1_maybeRvcMap_T_94 ? _s1_maybeRvcMap_T_93 : s1_maybeRvcMap_r_7,
     _s1_maybeRvcMap_T_82 ? _s1_maybeRvcMap_T_81 : s1_maybeRvcMap_r_6,
     _s1_maybeRvcMap_T_70 ? _s1_maybeRvcMap_T_69 : s1_maybeRvcMap_r_5,
     _s1_maybeRvcMap_T_58 ? _s1_maybeRvcMap_T_57 : s1_maybeRvcMap_r_4,
     _s1_maybeRvcMap_T_46 ? _s1_maybeRvcMap_T_45 : s1_maybeRvcMap_r_3,
     _s1_maybeRvcMap_T_34 ? _s1_maybeRvcMap_T_33 : s1_maybeRvcMap_r_2,
     _s1_maybeRvcMap_T_22 ? _s1_maybeRvcMap_T_21 : s1_maybeRvcMap_r_1,
     _s1_maybeRvcMap_T_10 ? _s1_maybeRvcMap_T_9 : s1_maybeRvcMap_r};
  assign io_resp_bits_pAddr_addr = {s1_pTag, s1_vAddr_0_addr[10:0]};
  assign io_resp_bits_exception_value =
    (|_s1_exceptionOut_T_1_value)
      ? _s1_exceptionOut_T_1_value
      : _s1_eccException_T_2 ? 3'h5 : 3'h0;
  assign io_resp_bits_pmpMmio = io_pmp_resp_mmio;
  assign io_resp_bits_itlbPbmt = s1_itlbPbmt;
  assign io_resp_bits_isBackendException = s1_isBackendException;
  assign io_resp_bits_gpAddr_addr = s1_gpAddr_addr;
  assign io_resp_bits_isForVSnonLeafPTE = s1_isForVSnonLeafPTE;
  assign io_errors_0_valid = _io_errors_0_bits_report_to_beu_T & io_errors_0_valid_REG;
  assign io_errors_0_bits_paddr = {s1_pTag, s1_vAddr_0_addr[10:0], 1'h0};
  assign io_errors_0_bits_report_to_beu =
    _io_errors_0_bits_report_to_beu_T & io_errors_0_bits_report_to_beu_REG;
  assign io_errors_1_valid = _io_errors_1_bits_report_to_beu_T & io_errors_1_valid_REG;
  assign io_errors_1_bits_paddr = {s1_pTag, s1_vAddr_1_addr[10:0], 1'h0};
  assign io_errors_1_bits_report_to_beu =
    _io_errors_1_bits_report_to_beu_T & io_errors_1_bits_report_to_beu_REG;
  assign io_perf_rawHits = s1_rawHits;
  assign io_perf_pendingMiss = s1_valid & _io_perf_pendingMiss_T;
  assign gatewayIn_packed_0_bore =
    {difftest_refill_valid,
     difftest_refill_addr,
     /*cast(bit[511:0])*/difftest_refill_data,
     difftest_refill_mask,
     difftest_refill_coreid,
     difftest_refill_index};
  assign gatewayIn_packed_1_bore =
    {difftest_refill_1_valid,
     difftest_refill_1_addr,
     /*cast(bit[511:0])*/difftest_refill_1_data,
     difftest_refill_1_mask,
     difftest_refill_1_coreid,
     difftest_refill_1_index};
endmodule

