#!/usr/bin/env python3
"""Generate a per-eval golden trace shim for a GrhSIM IR CPU-backend model.

The shim is a C++ header that is force-included (-include) when compiling a
hand-written testbench.  It defines a derived model class whose eval() calls
the base eval() and then appends one line with every interface port value to
GRHSIM_TRACE_PATH.  The testbench is compiled with
-D<macro-name>=<traced-name> so its references to the model class resolve to
the traced subclass without any testbench edits.

The port list is recovered from the generated model header: every public
member declared between the class's opening `public:` and its constructor is
an interface port.
"""

import argparse
import re
import sys
from pathlib import Path

SCALAR_TYPES = {
    "bool",
    "std::uint8_t",
    "std::uint16_t",
    "std::uint32_t",
    "std::uint64_t",
    "std::int8_t",
    "std::int16_t",
    "std::int32_t",
    "std::int64_t",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
    "double",
}
ARRAY_RE = re.compile(r"^std::array<\s*(?:std::)?u?int(?:8|16|32|64)_t\s*,\s*(\d+)\s*>$")
BITINT_RE = re.compile(r"^unsigned _BitInt\(\s*(\d+)\s*\)$")
MEMBER_RE = re.compile(r"^\s*([A-Za-z_:][A-Za-z0-9_:<> ,()]*?)\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?:\{\})?\s*;\s*$")


ALIAS_RE = re.compile(r"^\s*using\s+[A-Za-z_][A-Za-z0-9_]*\s*=\s*([A-Za-z_][A-Za-z0-9_]*)\s*;\s*$")
INCLUDE_RE = re.compile(r'^\s*#include\s+"([^"]+)"\s*$')


def parse_ports(header: Path, class_name: str) -> tuple[list[tuple[str, str]], str]:
    """Return (ports, defining class name). Follows the stable-alias header to
    the real generated header when `class_name` is a `using` alias."""
    seen: set[str] = set()
    current_header = header
    current_class = class_name
    while True:
        try:
            return parse_ports_direct(current_header, current_class), current_class
        except ClassNotFound:
            if current_class in seen:
                raise SystemExit(f"[trace-shim] alias cycle for {class_name} in {header}")
            seen.add(current_class)
            lines = current_header.read_text(encoding="utf-8").splitlines()
            alias = None
            include = None
            for line in lines:
                match = ALIAS_RE.match(line)
                if match:
                    alias = match.group(1)
                    continue
                match = INCLUDE_RE.match(line)
                if match and match.group(1).endswith(".hpp") and not match.group(1).endswith("_runtime.hpp"):
                    include = match.group(1)
            if alias is None or include is None:
                raise SystemExit(f"[trace-shim] class {current_class} not found in {current_header}")
            current_class = alias
            current_header = current_header.parent / include
            if not current_header.is_file():
                raise SystemExit(f"[trace-shim] alias target header missing: {current_header}")


class ClassNotFound(Exception):
    pass


def parse_ports_direct(header: Path, class_name: str) -> list[tuple[str, str]]:
    lines = header.read_text(encoding="utf-8").splitlines()
    class_re = re.compile(rf"^\s*class\s+{re.escape(class_name)}\s*(?:final\s*)?\{{\s*$")
    start = None
    for index, line in enumerate(lines):
        if class_re.match(line):
            start = index + 1
            break
    if start is None:
        raise ClassNotFound(f"{class_name} in {header}")
    ports: list[tuple[str, str]] = []
    in_public = False
    for line in lines[start:]:
        stripped = line.strip()
        if stripped.startswith("public:"):
            in_public = True
            continue
        if not in_public:
            continue
        match = MEMBER_RE.match(line)
        if match is None:
            # First non-member line (constructor, struct, method) ends the port block.
            break
        type_name = re.sub(r"\s+", " ", match.group(1).strip())
        name = match.group(2)
        if type_name in SCALAR_TYPES or ARRAY_RE.match(type_name) or BITINT_RE.match(type_name):
            ports.append((type_name, name))
        else:
            raise SystemExit(
                f"[trace-shim] unsupported port type {type_name!r} for member {name!r} in {header}"
            )
    if not ports:
        raise SystemExit(f"[trace-shim] no ports found in {header} class {class_name}")
    return ports


def render_shim(include_header: str, macro_name: str, base_class: str, traced_class: str, ports) -> str:
    lines = [
        "#pragma once",
        "// Auto-generated by scripts/gen_grhsim_ir_trace_shim.py -- do not edit.",
        "// Force-include this header and compile the testbench with",
        f"//   -D{macro_name}={traced_class}",
        "// to record one line of port values after every eval().",
        "#include <array>",
        "#include <cstdint>",
        "#include <cstdio>",
        "#include <cstdlib>",
        "#include <cstring>",
        "#include <type_traits>",
        f'#pragma push_macro("{macro_name}")',
        f"#undef {macro_name}",
        f'#include "{include_header}"',
        f"class {traced_class} : public {base_class} {{",
        "public:",
        "    void eval()",
        "    {",
        f"        {base_class}::eval();",
        "        traceEval();",
        "    }",
        f"    ~{traced_class}()",
        "    {",
        "        if (traceFile_) std::fclose(traceFile_);",
        "    }",
        "",
        "private:",
        "    std::uint64_t traceSeq_ = 0;",
        "    std::FILE *traceFile_ = nullptr;",
        "",
        "    std::FILE *traceStream()",
        "    {",
        "        if (!traceFile_)",
        "        {",
        "            const char *path = std::getenv(\"GRHSIM_TRACE_PATH\");",
        "            if (!path || !*path)",
        "            {",
        "                std::fprintf(stderr, \"[grhsim-trace] GRHSIM_TRACE_PATH is not set\\n\");",
        "                std::abort();",
        "            }",
        "            traceFile_ = std::fopen(path, \"w\");",
        "            if (!traceFile_)",
        "            {",
        "                std::fprintf(stderr, \"[grhsim-trace] cannot open %s\\n\", path);",
        "                std::abort();",
        "            }",
        "        }",
        "        return traceFile_;",
        "    }",
        "",
        "    void traceEval()",
        "    {",
        "        std::FILE *stream = traceStream();",
        "        std::fprintf(stream, \"eval %llu\", static_cast<unsigned long long>(traceSeq_++));",
    ]
    for _type_name, port_name in ports:
        lines.append(f"        tracePort(stream, \"{port_name}\", {port_name});")
    lines += [
        "        std::fputc('\\n', stream);",
        "        std::fflush(stream);",
        "    }",
        "",
        "    template <typename T>",
        "    static void traceValue(std::FILE *stream, T value)",
        "    {",
        "        if constexpr (std::is_same_v<T, bool>)",
        "        {",
        "            std::fprintf(stream, \"%u\", value ? 1u : 0u);",
        "        }",
        "        else if constexpr (std::is_integral_v<T>)",
        "        {",
        "            using U = std::make_unsigned_t<T>;",
        "            std::fprintf(stream, \"%0*llx\", static_cast<int>(sizeof(T)) * 2,",
        "                         static_cast<unsigned long long>(static_cast<U>(value)));",
        "        }",
        "        else if constexpr (std::is_same_v<T, double>)",
        "        {",
        "            std::uint64_t bits = 0;",
        "            static_assert(sizeof(bits) == sizeof(value));",
        "            std::memcpy(&bits, &value, sizeof(bits));",
        "            std::fprintf(stream, \"%016llx\", static_cast<unsigned long long>(bits));",
        "        }",
        "        else if constexpr (sizeof(T) > 8)",
        "        {",
        "            // Wide C23 _BitInt ports: print the u64-word image,",
        "            // most-significant word first (same text the std::array",
        "            // overload produced for word-array ports).",
        "            const auto *words = reinterpret_cast<const std::uint64_t *>(&value);",
        "            for (std::size_t i = sizeof(T) / 8; i-- > 0;)",
        "                std::fprintf(stream, \"%016llx\", static_cast<unsigned long long>(words[i]));",
        "        }",
        "        else",
        "        {",
        "            static_assert(!sizeof(T *), \"[grhsim-trace] unsupported port type\");",
        "        }",
        "    }",
        "",
        "    template <typename T, std::size_t N>",
        "    static void traceValue(std::FILE *stream, const std::array<T, N> &value)",
        "    {",
        "        for (std::size_t i = N; i-- > 0;) traceValue(stream, value[i]);",
        "    }",
        "",
        "    template <typename T>",
        "    static void tracePort(std::FILE *stream, const char *name, const T &value)",
        "    {",
        "        std::fprintf(stream, \" %s=\", name);",
        "        traceValue(stream, value);",
        "    }",
        "};",
        f'#pragma pop_macro("{macro_name}")',
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--header", required=True, type=Path, help="generated model header defining the class")
    parser.add_argument("--class-name", required=True, help="model class name (e.g. GrhSIM_top_module)")
    parser.add_argument("--include", required=True, help="header path as seen by the testbench include")
    parser.add_argument("--macro-name", required=True, help="identifier the testbench uses for the model class")
    parser.add_argument("--traced-name", required=True, help="name of the traced subclass to generate")
    parser.add_argument("--output", required=True, type=Path, help="output shim header path")
    args = parser.parse_args()

    ports, base_class = parse_ports(args.header, args.class_name)
    shim = render_shim(args.include, args.macro_name, base_class, args.traced_name, ports)
    args.output.write_text(shim, encoding="utf-8")
    sys.stderr.write(f"[trace-shim] wrote {args.output} with {len(ports)} ports\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
