// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RenameTable_4(
  input             clock,
  input             reset,
  input             io_redirect,
  input             io_readPorts_0_hold,
  output [7:0]      io_readPorts_0_data,
  input             io_readPorts_1_hold,
  output [7:0]      io_readPorts_1_data,
  input             io_readPorts_2_hold,
  output [7:0]      io_readPorts_2_data,
  input             io_readPorts_3_hold,
  output [7:0]      io_readPorts_3_data,
  input             io_readPorts_4_hold,
  output [7:0]      io_readPorts_4_data,
  input             io_readPorts_5_hold,
  output [7:0]      io_readPorts_5_data,
  input             io_readPorts_6_hold,
  output [7:0]      io_readPorts_6_data,
  input             io_readPorts_7_hold,
  output [7:0]      io_readPorts_7_data,
  input             io_specWritePorts_0_wen,
  input  [7:0]      io_specWritePorts_0_data,
  input             io_specWritePorts_1_wen,
  input  [7:0]      io_specWritePorts_1_data,
  input             io_specWritePorts_2_wen,
  input  [7:0]      io_specWritePorts_2_data,
  input             io_specWritePorts_3_wen,
  input  [7:0]      io_specWritePorts_3_data,
  input             io_specWritePorts_4_wen,
  input  [7:0]      io_specWritePorts_4_data,
  input             io_specWritePorts_5_wen,
  input  [7:0]      io_specWritePorts_5_data,
  input             io_specWritePorts_6_wen,
  input  [7:0]      io_specWritePorts_6_data,
  input             io_specWritePorts_7_wen,
  input  [7:0]      io_specWritePorts_7_data,
  input             io_archWritePorts_0_wen,
  input  [7:0]      io_archWritePorts_0_data,
  input             io_archWritePorts_1_wen,
  input  [7:0]      io_archWritePorts_1_data,
  input             io_archWritePorts_2_wen,
  input  [7:0]      io_archWritePorts_2_data,
  input             io_archWritePorts_3_wen,
  input  [7:0]      io_archWritePorts_3_data,
  input             io_archWritePorts_4_wen,
  input  [7:0]      io_archWritePorts_4_data,
  input             io_archWritePorts_5_wen,
  input  [7:0]      io_archWritePorts_5_data,
  input             io_archWritePorts_6_wen,
  input  [7:0]      io_archWritePorts_6_data,
  input             io_archWritePorts_7_wen,
  input  [7:0]      io_archWritePorts_7_data,
  output [7:0][7:0] io_old_pdest,
  output [7:0]      io_need_free,
  input             io_snpt_snptEnq,
  input             io_snpt_snptDeq,
  input             io_snpt_useSnpt,
  input  [1:0]      io_snpt_snptSelect,
  input  [3:0]      io_snpt_flushVec,
  input             io_diffWritePorts_0_wen,
  input  [7:0]      io_diffWritePorts_0_data,
  input             io_diffWritePorts_1_wen,
  input  [7:0]      io_diffWritePorts_1_data,
  input             io_diffWritePorts_2_wen,
  input  [7:0]      io_diffWritePorts_2_data,
  input             io_diffWritePorts_3_wen,
  input  [7:0]      io_diffWritePorts_3_data,
  input             io_diffWritePorts_4_wen,
  input  [7:0]      io_diffWritePorts_4_data,
  input             io_diffWritePorts_5_wen,
  input  [7:0]      io_diffWritePorts_5_data,
  input             io_diffWritePorts_6_wen,
  input  [7:0]      io_diffWritePorts_6_data,
  input             io_diffWritePorts_7_wen,
  input  [7:0]      io_diffWritePorts_7_data,
  output [7:0]      io_debug_rdata_0,
  output [7:0]      io_diff_rdata_0,
  output [7:0]      io_debug_vl,
  output [7:0]      io_diff_vl
);

  wire [7:0]      _snapshots_snapshotGen_io_snapshots_0_0;
  wire [7:0]      _snapshots_snapshotGen_io_snapshots_1_0;
  wire [7:0]      _snapshots_snapshotGen_io_snapshots_2_0;
  wire [7:0]      _snapshots_snapshotGen_io_snapshots_3_0;
  reg  [7:0]      spec_table_0;
  reg  [7:0]      arch_table_0;
  reg  [7:0][7:0] old_pdest;
  reg  [7:0]      need_free;
  reg             t1_redirect_last_REG;
  reg             t1_wSpec_0_wen;
  reg  [7:0]      t1_wSpec_0_data;
  reg             t1_wSpec_1_wen;
  reg  [7:0]      t1_wSpec_1_data;
  reg             t1_wSpec_2_wen;
  reg  [7:0]      t1_wSpec_2_data;
  reg             t1_wSpec_3_wen;
  reg  [7:0]      t1_wSpec_3_data;
  reg             t1_wSpec_4_wen;
  reg  [7:0]      t1_wSpec_4_data;
  reg             t1_wSpec_5_wen;
  reg  [7:0]      t1_wSpec_5_data;
  reg             t1_wSpec_6_wen;
  reg  [7:0]      t1_wSpec_6_data;
  reg             t1_wSpec_7_wen;
  reg  [7:0]      t1_wSpec_7_data;
  reg             t1_snpt_snptEnq;
  reg             t1_snpt_snptDeq;
  reg             t1_snpt_useSnpt;
  reg  [1:0]      t1_snpt_snptSelect;
  reg  [3:0]      t1_snpt_flushVec;
  reg             t2_snpt_useSnpt;
  reg  [1:0]      t2_snpt_snptSelect;
  reg             spec_table_next_0_REG;
  reg  [7:0]      t1_bypass;
  wire            _bypass_data_T = t1_bypass[3'h7] | t1_bypass[3'h6];
  reg  [7:0]      t1_bypass_1;
  wire            _bypass_data_T_13 = t1_bypass_1[3'h7] | t1_bypass_1[3'h6];
  reg  [7:0]      t1_bypass_2;
  wire            _bypass_data_T_26 = t1_bypass_2[3'h7] | t1_bypass_2[3'h6];
  reg  [7:0]      t1_bypass_3;
  wire            _bypass_data_T_39 = t1_bypass_3[3'h7] | t1_bypass_3[3'h6];
  reg  [7:0]      t1_bypass_4;
  wire            _bypass_data_T_52 = t1_bypass_4[3'h7] | t1_bypass_4[3'h6];
  reg  [7:0]      t1_bypass_5;
  wire            _bypass_data_T_65 = t1_bypass_5[3'h7] | t1_bypass_5[3'h6];
  reg  [7:0]      t1_bypass_6;
  wire            _bypass_data_T_78 = t1_bypass_6[3'h7] | t1_bypass_6[3'h6];
  reg  [7:0]      t1_bypass_7;
  wire            _bypass_data_T_91 = t1_bypass_7[3'h7] | t1_bypass_7[3'h6];
  reg  [7:0]      difftest_table_0;
  wire [3:0][7:0] _GEN =
    {{_snapshots_snapshotGen_io_snapshots_3_0},
     {_snapshots_snapshotGen_io_snapshots_2_0},
     {_snapshots_snapshotGen_io_snapshots_1_0},
     {_snapshots_snapshotGen_io_snapshots_0_0}};
  wire            _wMatch_T = t1_wSpec_7_wen | t1_wSpec_6_wen;
  wire [7:0]      arch_mask_1 = {8{io_archWritePorts_1_wen}};
  wire [7:0]      arch_mask_2 = {8{io_archWritePorts_2_wen}};
  wire [7:0]      arch_mask_3 = {8{io_archWritePorts_3_wen}};
  wire [7:0]      arch_mask_4 = {8{io_archWritePorts_4_wen}};
  wire [7:0]      arch_mask_5 = {8{io_archWritePorts_5_wen}};
  wire [7:0]      arch_mask_6 = {8{io_archWritePorts_6_wen}};
  wire [7:0]      arch_mask_7 = {8{io_archWritePorts_7_wen}};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      spec_table_0 <= 8'h0;
      arch_table_0 <= 8'h0;
      old_pdest <= '{8'h0, 8'h0, 8'h0, 8'h0, 8'h0, 8'h0, 8'h0, 8'h0};
      need_free <= '{1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
      t1_redirect_last_REG <= 1'h0;
      t1_snpt_snptEnq <= 1'h0;
      t1_snpt_snptDeq <= 1'h0;
      t1_snpt_useSnpt <= 1'h0;
      t1_snpt_snptSelect <= 2'h0;
      t1_snpt_flushVec <= '{1'h0, 1'h0, 1'h0, 1'h0};
      t2_snpt_useSnpt <= 1'h0;
      t2_snpt_snptSelect <= 2'h0;
      difftest_table_0 <= 8'h0;
    end
    else begin
      if (spec_table_next_0_REG)
        spec_table_0 <= t2_snpt_useSnpt ? _GEN[t2_snpt_snptSelect] : arch_table_0;
      else if (|{t1_wSpec_7_wen,
                 t1_wSpec_6_wen,
                 t1_wSpec_5_wen,
                 t1_wSpec_4_wen,
                 t1_wSpec_3_wen,
                 t1_wSpec_2_wen,
                 t1_wSpec_1_wen,
                 t1_wSpec_0_wen})
        spec_table_0 <=
          _wMatch_T | t1_wSpec_5_wen | t1_wSpec_4_wen
            ? (_wMatch_T
                 ? (t1_wSpec_7_wen ? t1_wSpec_7_data : t1_wSpec_6_data)
                 : t1_wSpec_5_wen ? t1_wSpec_5_data : t1_wSpec_4_data)
            : t1_wSpec_3_wen | t1_wSpec_2_wen
                ? (t1_wSpec_3_wen ? t1_wSpec_3_data : t1_wSpec_2_data)
                : t1_wSpec_1_wen ? t1_wSpec_1_data : t1_wSpec_0_data;
      if (io_archWritePorts_7_wen)
        arch_table_0 <= io_archWritePorts_7_data;
      else if (io_archWritePorts_6_wen)
        arch_table_0 <= io_archWritePorts_6_data;
      else if (io_archWritePorts_5_wen)
        arch_table_0 <= io_archWritePorts_5_data;
      else if (io_archWritePorts_4_wen)
        arch_table_0 <= io_archWritePorts_4_data;
      else if (io_archWritePorts_3_wen)
        arch_table_0 <= io_archWritePorts_3_data;
      else if (io_archWritePorts_2_wen)
        arch_table_0 <= io_archWritePorts_2_data;
      else if (io_archWritePorts_1_wen)
        arch_table_0 <= io_archWritePorts_1_data;
      else if (io_archWritePorts_0_wen)
        arch_table_0 <= io_archWritePorts_0_data;
      old_pdest[3'h7] <=
        io_archWritePorts_6_wen
          ? io_archWritePorts_6_data & arch_mask_7
          : io_archWritePorts_5_wen
              ? io_archWritePorts_5_data & arch_mask_7
              : io_archWritePorts_4_wen
                  ? io_archWritePorts_4_data & arch_mask_7
                  : io_archWritePorts_3_wen
                      ? io_archWritePorts_3_data & arch_mask_7
                      : io_archWritePorts_2_wen
                          ? io_archWritePorts_2_data & arch_mask_7
                          : io_archWritePorts_1_wen
                              ? io_archWritePorts_1_data & arch_mask_7
                              : io_archWritePorts_0_wen
                                  ? io_archWritePorts_0_data & arch_mask_7
                                  : arch_table_0 & arch_mask_7;
      old_pdest[3'h6] <=
        io_archWritePorts_5_wen
          ? io_archWritePorts_5_data & arch_mask_6
          : io_archWritePorts_4_wen
              ? io_archWritePorts_4_data & arch_mask_6
              : io_archWritePorts_3_wen
                  ? io_archWritePorts_3_data & arch_mask_6
                  : io_archWritePorts_2_wen
                      ? io_archWritePorts_2_data & arch_mask_6
                      : io_archWritePorts_1_wen
                          ? io_archWritePorts_1_data & arch_mask_6
                          : io_archWritePorts_0_wen
                              ? io_archWritePorts_0_data & arch_mask_6
                              : arch_table_0 & arch_mask_6;
      old_pdest[3'h5] <=
        io_archWritePorts_4_wen
          ? io_archWritePorts_4_data & arch_mask_5
          : io_archWritePorts_3_wen
              ? io_archWritePorts_3_data & arch_mask_5
              : io_archWritePorts_2_wen
                  ? io_archWritePorts_2_data & arch_mask_5
                  : io_archWritePorts_1_wen
                      ? io_archWritePorts_1_data & arch_mask_5
                      : io_archWritePorts_0_wen
                          ? io_archWritePorts_0_data & arch_mask_5
                          : arch_table_0 & arch_mask_5;
      old_pdest[3'h4] <=
        io_archWritePorts_3_wen
          ? io_archWritePorts_3_data & arch_mask_4
          : io_archWritePorts_2_wen
              ? io_archWritePorts_2_data & arch_mask_4
              : io_archWritePorts_1_wen
                  ? io_archWritePorts_1_data & arch_mask_4
                  : io_archWritePorts_0_wen
                      ? io_archWritePorts_0_data & arch_mask_4
                      : arch_table_0 & arch_mask_4;
      old_pdest[3'h3] <=
        io_archWritePorts_2_wen
          ? io_archWritePorts_2_data & arch_mask_3
          : io_archWritePorts_1_wen
              ? io_archWritePorts_1_data & arch_mask_3
              : io_archWritePorts_0_wen
                  ? io_archWritePorts_0_data & arch_mask_3
                  : arch_table_0 & arch_mask_3;
      old_pdest[3'h2] <=
        io_archWritePorts_1_wen
          ? io_archWritePorts_1_data & arch_mask_2
          : io_archWritePorts_0_wen
              ? io_archWritePorts_0_data & arch_mask_2
              : arch_table_0 & arch_mask_2;
      old_pdest[3'h1] <=
        io_archWritePorts_0_wen
          ? io_archWritePorts_0_data & arch_mask_1
          : arch_table_0 & arch_mask_1;
      old_pdest[3'h0] <= arch_table_0 & {8{io_archWritePorts_0_wen}};
      need_free[3'h7] <=
        arch_table_0 != old_pdest[3'h7]
        & {old_pdest[3'h6] == old_pdest[3'h7],
           old_pdest[3'h5] == old_pdest[3'h7],
           old_pdest[3'h4] == old_pdest[3'h7],
           old_pdest[3'h3] == old_pdest[3'h7],
           old_pdest[3'h2] == old_pdest[3'h7],
           old_pdest[3'h1] == old_pdest[3'h7],
           old_pdest[3'h0] == old_pdest[3'h7]} == 7'h0;
      need_free[3'h6] <=
        arch_table_0 != old_pdest[3'h6]
        & {old_pdest[3'h5] == old_pdest[3'h6],
           old_pdest[3'h4] == old_pdest[3'h6],
           old_pdest[3'h3] == old_pdest[3'h6],
           old_pdest[3'h2] == old_pdest[3'h6],
           old_pdest[3'h1] == old_pdest[3'h6],
           old_pdest[3'h0] == old_pdest[3'h6]} == 6'h0;
      need_free[3'h5] <=
        arch_table_0 != old_pdest[3'h5]
        & {old_pdest[3'h4] == old_pdest[3'h5],
           old_pdest[3'h3] == old_pdest[3'h5],
           old_pdest[3'h2] == old_pdest[3'h5],
           old_pdest[3'h1] == old_pdest[3'h5],
           old_pdest[3'h0] == old_pdest[3'h5]} == 5'h0;
      need_free[3'h4] <=
        arch_table_0 != old_pdest[3'h4]
        & {old_pdest[3'h3] == old_pdest[3'h4],
           old_pdest[3'h2] == old_pdest[3'h4],
           old_pdest[3'h1] == old_pdest[3'h4],
           old_pdest[3'h0] == old_pdest[3'h4]} == 4'h0;
      need_free[3'h3] <=
        arch_table_0 != old_pdest[3'h3]
        & {old_pdest[3'h2] == old_pdest[3'h3],
           old_pdest[3'h1] == old_pdest[3'h3],
           old_pdest[3'h0] == old_pdest[3'h3]} == 3'h0;
      need_free[3'h2] <=
        arch_table_0 != old_pdest[3'h2]
        & {old_pdest[3'h1] == old_pdest[3'h2],
           old_pdest[3'h0] == old_pdest[3'h2]} == 2'h0;
      need_free[3'h1] <=
        arch_table_0 != old_pdest[3'h1] & old_pdest[3'h0] != old_pdest[3'h1];
      need_free[3'h0] <= arch_table_0 != old_pdest[3'h0];
      t1_redirect_last_REG <= io_redirect;
      t1_snpt_snptEnq <= io_snpt_snptEnq;
      t1_snpt_snptDeq <= io_snpt_snptDeq;
      t1_snpt_useSnpt <= io_snpt_useSnpt;
      t1_snpt_snptSelect <= io_snpt_snptSelect;
      t1_snpt_flushVec <= io_snpt_flushVec;
      t2_snpt_useSnpt <= t1_snpt_useSnpt;
      t2_snpt_snptSelect <= t1_snpt_snptSelect;
      if (io_diffWritePorts_7_wen)
        difftest_table_0 <= io_diffWritePorts_7_data;
      else if (io_diffWritePorts_6_wen)
        difftest_table_0 <= io_diffWritePorts_6_data;
      else if (io_diffWritePorts_5_wen)
        difftest_table_0 <= io_diffWritePorts_5_data;
      else if (io_diffWritePorts_4_wen)
        difftest_table_0 <= io_diffWritePorts_4_data;
      else if (io_diffWritePorts_3_wen)
        difftest_table_0 <= io_diffWritePorts_3_data;
      else if (io_diffWritePorts_2_wen)
        difftest_table_0 <= io_diffWritePorts_2_data;
      else if (io_diffWritePorts_1_wen)
        difftest_table_0 <= io_diffWritePorts_1_data;
      else if (io_diffWritePorts_0_wen)
        difftest_table_0 <= io_diffWritePorts_0_data;
    end
  end // always @(posedge, posedge)
  wire [7:0]      _need_free_WIRE = '{1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
  wire [7:0]      _t1_bypass_WIRE_1 =
    {{io_specWritePorts_7_wen},
     {io_specWritePorts_6_wen},
     {io_specWritePorts_5_wen},
     {io_specWritePorts_4_wen},
     {io_specWritePorts_3_wen},
     {io_specWritePorts_2_wen},
     {io_specWritePorts_1_wen},
     {io_specWritePorts_0_wen}};
  always @(posedge clock) begin
    if (io_redirect) begin
      t1_wSpec_0_wen <= 1'h0;
      t1_wSpec_0_data <= 8'h0;
      t1_wSpec_1_wen <= 1'h0;
      t1_wSpec_1_data <= 8'h0;
      t1_wSpec_2_wen <= 1'h0;
      t1_wSpec_2_data <= 8'h0;
      t1_wSpec_3_wen <= 1'h0;
      t1_wSpec_3_data <= 8'h0;
      t1_wSpec_4_wen <= 1'h0;
      t1_wSpec_4_data <= 8'h0;
      t1_wSpec_5_wen <= 1'h0;
      t1_wSpec_5_data <= 8'h0;
      t1_wSpec_6_wen <= 1'h0;
      t1_wSpec_6_data <= 8'h0;
      t1_wSpec_7_wen <= 1'h0;
      t1_wSpec_7_data <= 8'h0;
    end
    else begin
      t1_wSpec_0_wen <= io_specWritePorts_0_wen;
      t1_wSpec_0_data <= io_specWritePorts_0_data;
      t1_wSpec_1_wen <= io_specWritePorts_1_wen;
      t1_wSpec_1_data <= io_specWritePorts_1_data;
      t1_wSpec_2_wen <= io_specWritePorts_2_wen;
      t1_wSpec_2_data <= io_specWritePorts_2_data;
      t1_wSpec_3_wen <= io_specWritePorts_3_wen;
      t1_wSpec_3_data <= io_specWritePorts_3_data;
      t1_wSpec_4_wen <= io_specWritePorts_4_wen;
      t1_wSpec_4_data <= io_specWritePorts_4_data;
      t1_wSpec_5_wen <= io_specWritePorts_5_wen;
      t1_wSpec_5_data <= io_specWritePorts_5_data;
      t1_wSpec_6_wen <= io_specWritePorts_6_wen;
      t1_wSpec_6_data <= io_specWritePorts_6_data;
      t1_wSpec_7_wen <= io_specWritePorts_7_wen;
      t1_wSpec_7_data <= io_specWritePorts_7_data;
    end
    spec_table_next_0_REG <= t1_redirect_last_REG;
    t1_bypass <= io_redirect ? _need_free_WIRE : _t1_bypass_WIRE_1;
    t1_bypass_1 <= io_redirect ? _need_free_WIRE : _t1_bypass_WIRE_1;
    t1_bypass_2 <= io_redirect ? _need_free_WIRE : _t1_bypass_WIRE_1;
    t1_bypass_3 <= io_redirect ? _need_free_WIRE : _t1_bypass_WIRE_1;
    t1_bypass_4 <= io_redirect ? _need_free_WIRE : _t1_bypass_WIRE_1;
    t1_bypass_5 <= io_redirect ? _need_free_WIRE : _t1_bypass_WIRE_1;
    t1_bypass_6 <= io_redirect ? _need_free_WIRE : _t1_bypass_WIRE_1;
    t1_bypass_7 <= io_redirect ? _need_free_WIRE : _t1_bypass_WIRE_1;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:7];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;
        end
        spec_table_0 = _RANDOM[3'h0][7:0];
        arch_table_0 = _RANDOM[3'h0][15:8];
        old_pdest[3'h0] = _RANDOM[3'h0][31:24];
        old_pdest[3'h1] = _RANDOM[3'h0][23:16];
        old_pdest[3'h2] = _RANDOM[3'h1][31:24];
        old_pdest[3'h3] = _RANDOM[3'h1][23:16];
        old_pdest[3'h4] = _RANDOM[3'h1][15:8];
        old_pdest[3'h5] = _RANDOM[3'h1][7:0];
        old_pdest[3'h6] = _RANDOM[3'h2][15:8];
        old_pdest[3'h7] = _RANDOM[3'h2][7:0];
        need_free[3'h0] = _RANDOM[3'h2][23];
        need_free[3'h1] = _RANDOM[3'h2][22];
        need_free[3'h2] = _RANDOM[3'h2][21];
        need_free[3'h3] = _RANDOM[3'h2][20];
        need_free[3'h4] = _RANDOM[3'h2][19];
        need_free[3'h5] = _RANDOM[3'h2][18];
        need_free[3'h6] = _RANDOM[3'h2][17];
        need_free[3'h7] = _RANDOM[3'h2][16];
        t1_redirect_last_REG = _RANDOM[3'h2][24];
        t1_wSpec_0_wen = _RANDOM[3'h2][25];
        t1_wSpec_0_data = {_RANDOM[3'h2][31:26], _RANDOM[3'h3][1:0]};
        t1_wSpec_1_wen = _RANDOM[3'h3][2];
        t1_wSpec_1_data = _RANDOM[3'h3][10:3];
        t1_wSpec_2_wen = _RANDOM[3'h3][11];
        t1_wSpec_2_data = _RANDOM[3'h3][19:12];
        t1_wSpec_3_wen = _RANDOM[3'h3][20];
        t1_wSpec_3_data = _RANDOM[3'h3][28:21];
        t1_wSpec_4_wen = _RANDOM[3'h3][29];
        t1_wSpec_4_data = {_RANDOM[3'h3][31:30], _RANDOM[3'h4][5:0]};
        t1_wSpec_5_wen = _RANDOM[3'h4][6];
        t1_wSpec_5_data = _RANDOM[3'h4][14:7];
        t1_wSpec_6_wen = _RANDOM[3'h4][15];
        t1_wSpec_6_data = _RANDOM[3'h4][23:16];
        t1_wSpec_7_wen = _RANDOM[3'h4][24];
        t1_wSpec_7_data = {_RANDOM[3'h4][31:25], _RANDOM[3'h5][0]};
        t1_snpt_snptEnq = _RANDOM[3'h5][1];
        t1_snpt_snptDeq = _RANDOM[3'h5][2];
        t1_snpt_useSnpt = _RANDOM[3'h5][3];
        t1_snpt_snptSelect = _RANDOM[3'h5][5:4];
        t1_snpt_flushVec[2'h0] = _RANDOM[3'h5][9];
        t1_snpt_flushVec[2'h1] = _RANDOM[3'h5][8];
        t1_snpt_flushVec[2'h2] = _RANDOM[3'h5][7];
        t1_snpt_flushVec[2'h3] = _RANDOM[3'h5][6];
        t2_snpt_useSnpt = _RANDOM[3'h5][12];
        t2_snpt_snptSelect = _RANDOM[3'h5][14:13];
        spec_table_next_0_REG = _RANDOM[3'h5][19];
        t1_bypass[3'h0] = _RANDOM[3'h5][27];
        t1_bypass[3'h1] = _RANDOM[3'h5][26];
        t1_bypass[3'h2] = _RANDOM[3'h5][25];
        t1_bypass[3'h3] = _RANDOM[3'h5][24];
        t1_bypass[3'h4] = _RANDOM[3'h5][23];
        t1_bypass[3'h5] = _RANDOM[3'h5][22];
        t1_bypass[3'h6] = _RANDOM[3'h5][21];
        t1_bypass[3'h7] = _RANDOM[3'h5][20];
        t1_bypass_1[3'h0] = _RANDOM[3'h5][31];
        t1_bypass_1[3'h1] = _RANDOM[3'h5][30];
        t1_bypass_1[3'h2] = _RANDOM[3'h5][29];
        t1_bypass_1[3'h3] = _RANDOM[3'h5][28];
        t1_bypass_1[3'h4] = _RANDOM[3'h6][3];
        t1_bypass_1[3'h5] = _RANDOM[3'h6][2];
        t1_bypass_1[3'h6] = _RANDOM[3'h6][1];
        t1_bypass_1[3'h7] = _RANDOM[3'h6][0];
        t1_bypass_2[3'h0] = _RANDOM[3'h6][11];
        t1_bypass_2[3'h1] = _RANDOM[3'h6][10];
        t1_bypass_2[3'h2] = _RANDOM[3'h6][9];
        t1_bypass_2[3'h3] = _RANDOM[3'h6][8];
        t1_bypass_2[3'h4] = _RANDOM[3'h6][7];
        t1_bypass_2[3'h5] = _RANDOM[3'h6][6];
        t1_bypass_2[3'h6] = _RANDOM[3'h6][5];
        t1_bypass_2[3'h7] = _RANDOM[3'h6][4];
        t1_bypass_3[3'h0] = _RANDOM[3'h6][19];
        t1_bypass_3[3'h1] = _RANDOM[3'h6][18];
        t1_bypass_3[3'h2] = _RANDOM[3'h6][17];
        t1_bypass_3[3'h3] = _RANDOM[3'h6][16];
        t1_bypass_3[3'h4] = _RANDOM[3'h6][15];
        t1_bypass_3[3'h5] = _RANDOM[3'h6][14];
        t1_bypass_3[3'h6] = _RANDOM[3'h6][13];
        t1_bypass_3[3'h7] = _RANDOM[3'h6][12];
        t1_bypass_4[3'h0] = _RANDOM[3'h6][27];
        t1_bypass_4[3'h1] = _RANDOM[3'h6][26];
        t1_bypass_4[3'h2] = _RANDOM[3'h6][25];
        t1_bypass_4[3'h3] = _RANDOM[3'h6][24];
        t1_bypass_4[3'h4] = _RANDOM[3'h6][23];
        t1_bypass_4[3'h5] = _RANDOM[3'h6][22];
        t1_bypass_4[3'h6] = _RANDOM[3'h6][21];
        t1_bypass_4[3'h7] = _RANDOM[3'h6][20];
        t1_bypass_5[3'h0] = _RANDOM[3'h6][31];
        t1_bypass_5[3'h1] = _RANDOM[3'h6][30];
        t1_bypass_5[3'h2] = _RANDOM[3'h6][29];
        t1_bypass_5[3'h3] = _RANDOM[3'h6][28];
        t1_bypass_5[3'h4] = _RANDOM[3'h7][3];
        t1_bypass_5[3'h5] = _RANDOM[3'h7][2];
        t1_bypass_5[3'h6] = _RANDOM[3'h7][1];
        t1_bypass_5[3'h7] = _RANDOM[3'h7][0];
        t1_bypass_6[3'h0] = _RANDOM[3'h7][11];
        t1_bypass_6[3'h1] = _RANDOM[3'h7][10];
        t1_bypass_6[3'h2] = _RANDOM[3'h7][9];
        t1_bypass_6[3'h3] = _RANDOM[3'h7][8];
        t1_bypass_6[3'h4] = _RANDOM[3'h7][7];
        t1_bypass_6[3'h5] = _RANDOM[3'h7][6];
        t1_bypass_6[3'h6] = _RANDOM[3'h7][5];
        t1_bypass_6[3'h7] = _RANDOM[3'h7][4];
        t1_bypass_7[3'h0] = _RANDOM[3'h7][19];
        t1_bypass_7[3'h1] = _RANDOM[3'h7][18];
        t1_bypass_7[3'h2] = _RANDOM[3'h7][17];
        t1_bypass_7[3'h3] = _RANDOM[3'h7][16];
        t1_bypass_7[3'h4] = _RANDOM[3'h7][15];
        t1_bypass_7[3'h5] = _RANDOM[3'h7][14];
        t1_bypass_7[3'h6] = _RANDOM[3'h7][13];
        t1_bypass_7[3'h7] = _RANDOM[3'h7][12];
        difftest_table_0 = _RANDOM[3'h7][27:20];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        spec_table_0 = 8'h0;
        arch_table_0 = 8'h0;
        old_pdest = '{8'h0, 8'h0, 8'h0, 8'h0, 8'h0, 8'h0, 8'h0, 8'h0};
        need_free = '{1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
        t1_redirect_last_REG = 1'h0;
        t1_snpt_snptEnq = 1'h0;
        t1_snpt_snptDeq = 1'h0;
        t1_snpt_useSnpt = 1'h0;
        t1_snpt_snptSelect = 2'h0;
        t1_snpt_flushVec = '{1'h0, 1'h0, 1'h0, 1'h0};
        t2_snpt_useSnpt = 1'h0;
        t2_snpt_snptSelect = 2'h0;
        difftest_table_0 = 8'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  SnapshotGenerator_7 snapshots_snapshotGen (
    .clock            (clock),
    .reset            (reset),
    .io_enq           (t1_snpt_snptEnq),
    .io_enqData_0     (spec_table_0),
    .io_deq           (t1_snpt_snptDeq),
    .io_redirect      (t1_redirect_last_REG),
    .io_flushVec      (t1_snpt_flushVec),
    .io_snapshots_0_0 (_snapshots_snapshotGen_io_snapshots_0_0),
    .io_snapshots_1_0 (_snapshots_snapshotGen_io_snapshots_1_0),
    .io_snapshots_2_0 (_snapshots_snapshotGen_io_snapshots_2_0),
    .io_snapshots_3_0 (_snapshots_snapshotGen_io_snapshots_3_0)
  );
  assign io_readPorts_0_data =
    (|t1_bypass)
      ? (_bypass_data_T | t1_bypass[3'h5] | t1_bypass[3'h4]
           ? (_bypass_data_T
                ? (t1_bypass[3'h7] ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass[3'h5] ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass[3'h3] | t1_bypass[3'h2]
               ? (t1_bypass[3'h3] ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass[3'h1] ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_1_data =
    (|t1_bypass_1)
      ? (_bypass_data_T_13 | t1_bypass_1[3'h5] | t1_bypass_1[3'h4]
           ? (_bypass_data_T_13
                ? (t1_bypass_1[3'h7] ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_1[3'h5] ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_1[3'h3] | t1_bypass_1[3'h2]
               ? (t1_bypass_1[3'h3] ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_1[3'h1] ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_2_data =
    (|t1_bypass_2)
      ? (_bypass_data_T_26 | t1_bypass_2[3'h5] | t1_bypass_2[3'h4]
           ? (_bypass_data_T_26
                ? (t1_bypass_2[3'h7] ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_2[3'h5] ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_2[3'h3] | t1_bypass_2[3'h2]
               ? (t1_bypass_2[3'h3] ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_2[3'h1] ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_3_data =
    (|t1_bypass_3)
      ? (_bypass_data_T_39 | t1_bypass_3[3'h5] | t1_bypass_3[3'h4]
           ? (_bypass_data_T_39
                ? (t1_bypass_3[3'h7] ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_3[3'h5] ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_3[3'h3] | t1_bypass_3[3'h2]
               ? (t1_bypass_3[3'h3] ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_3[3'h1] ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_4_data =
    (|t1_bypass_4)
      ? (_bypass_data_T_52 | t1_bypass_4[3'h5] | t1_bypass_4[3'h4]
           ? (_bypass_data_T_52
                ? (t1_bypass_4[3'h7] ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_4[3'h5] ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_4[3'h3] | t1_bypass_4[3'h2]
               ? (t1_bypass_4[3'h3] ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_4[3'h1] ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_5_data =
    (|t1_bypass_5)
      ? (_bypass_data_T_65 | t1_bypass_5[3'h5] | t1_bypass_5[3'h4]
           ? (_bypass_data_T_65
                ? (t1_bypass_5[3'h7] ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_5[3'h5] ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_5[3'h3] | t1_bypass_5[3'h2]
               ? (t1_bypass_5[3'h3] ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_5[3'h1] ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_6_data =
    (|t1_bypass_6)
      ? (_bypass_data_T_78 | t1_bypass_6[3'h5] | t1_bypass_6[3'h4]
           ? (_bypass_data_T_78
                ? (t1_bypass_6[3'h7] ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_6[3'h5] ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_6[3'h3] | t1_bypass_6[3'h2]
               ? (t1_bypass_6[3'h3] ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_6[3'h1] ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_7_data =
    (|t1_bypass_7)
      ? (_bypass_data_T_91 | t1_bypass_7[3'h5] | t1_bypass_7[3'h4]
           ? (_bypass_data_T_91
                ? (t1_bypass_7[3'h7] ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_7[3'h5] ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_7[3'h3] | t1_bypass_7[3'h2]
               ? (t1_bypass_7[3'h3] ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_7[3'h1] ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_old_pdest = old_pdest;
  assign io_need_free = need_free;
  assign io_debug_rdata_0 = arch_table_0;
  assign io_diff_rdata_0 = difftest_table_0;
  assign io_debug_vl = arch_table_0;
  assign io_diff_vl = difftest_table_0;
endmodule

