// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SnapshotGenerator_5(
  input              clock,
  input              reset,
  input              io_enq,
  input  [33:0][7:0] io_enqData,
  input              io_deq,
  input              io_redirect,
  input  [3:0]       io_flushVec,
  output [33:0][7:0] io_snapshots_0,
  output [33:0][7:0] io_snapshots_1,
  output [33:0][7:0] io_snapshots_2,
  output [33:0][7:0] io_snapshots_3
);

  reg  [33:0][7:0] snapshots_0;
  reg  [33:0][7:0] snapshots_1;
  reg  [33:0][7:0] snapshots_2;
  reg  [33:0][7:0] snapshots_3;
  reg              snptEnqPtr_flag;
  reg  [1:0]       snptEnqPtr_value;
  reg              snptDeqPtr_flag;
  reg  [1:0]       snptDeqPtr_value;
  reg  [3:0]       snptValids;
  wire             _GEN =
    ~io_redirect
    & ~(snptEnqPtr_flag != snptDeqPtr_flag & snptEnqPtr_value == snptDeqPtr_value)
    & io_enq;
  wire             _GEN_0 = _GEN & snptEnqPtr_value == 2'h0;
  wire             _GEN_1 = _GEN & snptEnqPtr_value == 2'h1;
  wire             _GEN_2 = _GEN & snptEnqPtr_value == 2'h2;
  wire             _GEN_3 = _GEN & (&snptEnqPtr_value);
  wire [2:0]       _GEN_4 = {snptEnqPtr_flag, snptEnqPtr_value};
  wire             _GEN_5 = ~io_redirect & io_deq;
  wire             _GEN_6 = _GEN_5 & _GEN_4 == {snptDeqPtr_flag, snptDeqPtr_value};
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (_GEN_6 & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at LogUtils.scala:132\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin
    if (_GEN_0)
      snapshots_0 <= io_enqData;
    if (_GEN_1)
      snapshots_1 <= io_enqData;
    if (_GEN_2)
      snapshots_2 <= io_enqData;
    if (_GEN_3)
      snapshots_3 <= io_enqData;
  end // always @(posedge)
  wire             _newEnqPtrQualified_0_T_1 =
    ~snptValids[snptDeqPtr_value] | io_flushVec[snptDeqPtr_value];
  wire [2:0]       _snptEnqPtr_new_ptr_T_1 = 3'(_GEN_4 + 3'h1);
  wire [2:0]       _GEN_7 = {snptDeqPtr_flag, snptDeqPtr_value};
  wire [2:0]       _newEnqPtrCandidate_new_ptr_T_7 = 3'(_GEN_7 + 3'h1);
  wire [2:0]       _newEnqPtrCandidate_new_ptr_T_13 = 3'(_GEN_7 + 3'h2);
  wire [2:0]       _newEnqPtrCandidate_new_ptr_T_19 = 3'(_GEN_7 + 3'h3);
  wire             _GEN_8 = snptValids[_newEnqPtrCandidate_new_ptr_T_7[1:0]];
  wire             _GEN_9 =
    _GEN_8 & (~_GEN_8 | io_flushVec[_newEnqPtrCandidate_new_ptr_T_7[1:0]]);
  wire             _GEN_10 = snptValids[_newEnqPtrCandidate_new_ptr_T_13[1:0]];
  wire             _GEN_11 =
    _GEN_10 & (~_GEN_10 | io_flushVec[_newEnqPtrCandidate_new_ptr_T_13[1:0]]);
  wire [2:0]       _snptDeqPtr_new_ptr_T_1 = 3'(_GEN_7 + 3'h1);
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      snptEnqPtr_flag <= 1'h0;
      snptEnqPtr_value <= 2'h0;
      snptDeqPtr_flag <= 1'h0;
      snptDeqPtr_value <= 2'h0;
      snptValids <= '{1'h0, 1'h0, 1'h0, 1'h0};
    end
    else begin
      if (|({io_flushVec[2'h0], io_flushVec[2'h1], io_flushVec[2'h2], io_flushVec[2'h3]}
            & {snptValids[2'h0],
               snptValids[2'h1],
               snptValids[2'h2],
               snptValids[2'h3]})) begin
        snptEnqPtr_flag <=
          _newEnqPtrQualified_0_T_1
            ? snptDeqPtr_flag
            : _GEN_9
                ? _newEnqPtrCandidate_new_ptr_T_7[2]
                : _GEN_11
                    ? _newEnqPtrCandidate_new_ptr_T_13[2]
                    : _newEnqPtrCandidate_new_ptr_T_19[2];
        snptEnqPtr_value <=
          _newEnqPtrQualified_0_T_1
            ? snptDeqPtr_value
            : _GEN_9
                ? _newEnqPtrCandidate_new_ptr_T_7[1:0]
                : _GEN_11
                    ? _newEnqPtrCandidate_new_ptr_T_13[1:0]
                    : _newEnqPtrCandidate_new_ptr_T_19[1:0];
      end
      else if (_GEN) begin
        snptEnqPtr_flag <= _snptEnqPtr_new_ptr_T_1[2];
        snptEnqPtr_value <= _snptEnqPtr_new_ptr_T_1[1:0];
      end
      if (_GEN_5) begin
        snptDeqPtr_flag <= _snptDeqPtr_new_ptr_T_1[2];
        snptDeqPtr_value <= _snptDeqPtr_new_ptr_T_1[1:0];
      end
      snptValids[2'h3] <=
        ~(io_flushVec[2'h3] | _GEN_5 & (&snptDeqPtr_value)) & (_GEN_3 | snptValids[2'h3]);
      snptValids[2'h2] <=
        ~(io_flushVec[2'h2] | _GEN_5 & snptDeqPtr_value == 2'h2)
        & (_GEN_2 | snptValids[2'h2]);
      snptValids[2'h1] <=
        ~(io_flushVec[2'h1] | _GEN_5 & snptDeqPtr_value == 2'h1)
        & (_GEN_1 | snptValids[2'h1]);
      snptValids[2'h0] <=
        ~(io_flushVec[2'h0] | _GEN_5 & snptDeqPtr_value == 2'h0)
        & (_GEN_0 | snptValids[2'h0]);
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:34];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h23; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        snapshots_0[6'h0] = _RANDOM[6'h0][31:24];
        snapshots_0[6'h1] = _RANDOM[6'h0][23:16];
        snapshots_0[6'h2] = _RANDOM[6'h0][15:8];
        snapshots_0[6'h3] = _RANDOM[6'h0][7:0];
        snapshots_0[6'h4] = _RANDOM[6'h1][31:24];
        snapshots_0[6'h5] = _RANDOM[6'h1][23:16];
        snapshots_0[6'h6] = _RANDOM[6'h1][15:8];
        snapshots_0[6'h7] = _RANDOM[6'h1][7:0];
        snapshots_0[6'h8] = _RANDOM[6'h2][31:24];
        snapshots_0[6'h9] = _RANDOM[6'h2][23:16];
        snapshots_0[6'hA] = _RANDOM[6'h2][15:8];
        snapshots_0[6'hB] = _RANDOM[6'h2][7:0];
        snapshots_0[6'hC] = _RANDOM[6'h3][31:24];
        snapshots_0[6'hD] = _RANDOM[6'h3][23:16];
        snapshots_0[6'hE] = _RANDOM[6'h3][15:8];
        snapshots_0[6'hF] = _RANDOM[6'h3][7:0];
        snapshots_0[6'h10] = _RANDOM[6'h4][31:24];
        snapshots_0[6'h11] = _RANDOM[6'h4][23:16];
        snapshots_0[6'h12] = _RANDOM[6'h4][15:8];
        snapshots_0[6'h13] = _RANDOM[6'h4][7:0];
        snapshots_0[6'h14] = _RANDOM[6'h5][31:24];
        snapshots_0[6'h15] = _RANDOM[6'h5][23:16];
        snapshots_0[6'h16] = _RANDOM[6'h5][15:8];
        snapshots_0[6'h17] = _RANDOM[6'h5][7:0];
        snapshots_0[6'h18] = _RANDOM[6'h6][31:24];
        snapshots_0[6'h19] = _RANDOM[6'h6][23:16];
        snapshots_0[6'h1A] = _RANDOM[6'h6][15:8];
        snapshots_0[6'h1B] = _RANDOM[6'h6][7:0];
        snapshots_0[6'h1C] = _RANDOM[6'h7][31:24];
        snapshots_0[6'h1D] = _RANDOM[6'h7][23:16];
        snapshots_0[6'h1E] = _RANDOM[6'h7][15:8];
        snapshots_0[6'h1F] = _RANDOM[6'h7][7:0];
        snapshots_0[6'h20] = _RANDOM[6'h8][15:8];
        snapshots_0[6'h21] = _RANDOM[6'h8][7:0];
        snapshots_1[6'h0] = _RANDOM[6'h8][31:24];
        snapshots_1[6'h1] = _RANDOM[6'h8][23:16];
        snapshots_1[6'h2] = _RANDOM[6'h9][31:24];
        snapshots_1[6'h3] = _RANDOM[6'h9][23:16];
        snapshots_1[6'h4] = _RANDOM[6'h9][15:8];
        snapshots_1[6'h5] = _RANDOM[6'h9][7:0];
        snapshots_1[6'h6] = _RANDOM[6'hA][31:24];
        snapshots_1[6'h7] = _RANDOM[6'hA][23:16];
        snapshots_1[6'h8] = _RANDOM[6'hA][15:8];
        snapshots_1[6'h9] = _RANDOM[6'hA][7:0];
        snapshots_1[6'hA] = _RANDOM[6'hB][31:24];
        snapshots_1[6'hB] = _RANDOM[6'hB][23:16];
        snapshots_1[6'hC] = _RANDOM[6'hB][15:8];
        snapshots_1[6'hD] = _RANDOM[6'hB][7:0];
        snapshots_1[6'hE] = _RANDOM[6'hC][31:24];
        snapshots_1[6'hF] = _RANDOM[6'hC][23:16];
        snapshots_1[6'h10] = _RANDOM[6'hC][15:8];
        snapshots_1[6'h11] = _RANDOM[6'hC][7:0];
        snapshots_1[6'h12] = _RANDOM[6'hD][31:24];
        snapshots_1[6'h13] = _RANDOM[6'hD][23:16];
        snapshots_1[6'h14] = _RANDOM[6'hD][15:8];
        snapshots_1[6'h15] = _RANDOM[6'hD][7:0];
        snapshots_1[6'h16] = _RANDOM[6'hE][31:24];
        snapshots_1[6'h17] = _RANDOM[6'hE][23:16];
        snapshots_1[6'h18] = _RANDOM[6'hE][15:8];
        snapshots_1[6'h19] = _RANDOM[6'hE][7:0];
        snapshots_1[6'h1A] = _RANDOM[6'hF][31:24];
        snapshots_1[6'h1B] = _RANDOM[6'hF][23:16];
        snapshots_1[6'h1C] = _RANDOM[6'hF][15:8];
        snapshots_1[6'h1D] = _RANDOM[6'hF][7:0];
        snapshots_1[6'h1E] = _RANDOM[6'h10][31:24];
        snapshots_1[6'h1F] = _RANDOM[6'h10][23:16];
        snapshots_1[6'h20] = _RANDOM[6'h10][15:8];
        snapshots_1[6'h21] = _RANDOM[6'h10][7:0];
        snapshots_2[6'h0] = _RANDOM[6'h11][31:24];
        snapshots_2[6'h1] = _RANDOM[6'h11][23:16];
        snapshots_2[6'h2] = _RANDOM[6'h11][15:8];
        snapshots_2[6'h3] = _RANDOM[6'h11][7:0];
        snapshots_2[6'h4] = _RANDOM[6'h12][31:24];
        snapshots_2[6'h5] = _RANDOM[6'h12][23:16];
        snapshots_2[6'h6] = _RANDOM[6'h12][15:8];
        snapshots_2[6'h7] = _RANDOM[6'h12][7:0];
        snapshots_2[6'h8] = _RANDOM[6'h13][31:24];
        snapshots_2[6'h9] = _RANDOM[6'h13][23:16];
        snapshots_2[6'hA] = _RANDOM[6'h13][15:8];
        snapshots_2[6'hB] = _RANDOM[6'h13][7:0];
        snapshots_2[6'hC] = _RANDOM[6'h14][31:24];
        snapshots_2[6'hD] = _RANDOM[6'h14][23:16];
        snapshots_2[6'hE] = _RANDOM[6'h14][15:8];
        snapshots_2[6'hF] = _RANDOM[6'h14][7:0];
        snapshots_2[6'h10] = _RANDOM[6'h15][31:24];
        snapshots_2[6'h11] = _RANDOM[6'h15][23:16];
        snapshots_2[6'h12] = _RANDOM[6'h15][15:8];
        snapshots_2[6'h13] = _RANDOM[6'h15][7:0];
        snapshots_2[6'h14] = _RANDOM[6'h16][31:24];
        snapshots_2[6'h15] = _RANDOM[6'h16][23:16];
        snapshots_2[6'h16] = _RANDOM[6'h16][15:8];
        snapshots_2[6'h17] = _RANDOM[6'h16][7:0];
        snapshots_2[6'h18] = _RANDOM[6'h17][31:24];
        snapshots_2[6'h19] = _RANDOM[6'h17][23:16];
        snapshots_2[6'h1A] = _RANDOM[6'h17][15:8];
        snapshots_2[6'h1B] = _RANDOM[6'h17][7:0];
        snapshots_2[6'h1C] = _RANDOM[6'h18][31:24];
        snapshots_2[6'h1D] = _RANDOM[6'h18][23:16];
        snapshots_2[6'h1E] = _RANDOM[6'h18][15:8];
        snapshots_2[6'h1F] = _RANDOM[6'h18][7:0];
        snapshots_2[6'h20] = _RANDOM[6'h19][15:8];
        snapshots_2[6'h21] = _RANDOM[6'h19][7:0];
        snapshots_3[6'h0] = _RANDOM[6'h19][31:24];
        snapshots_3[6'h1] = _RANDOM[6'h19][23:16];
        snapshots_3[6'h2] = _RANDOM[6'h1A][31:24];
        snapshots_3[6'h3] = _RANDOM[6'h1A][23:16];
        snapshots_3[6'h4] = _RANDOM[6'h1A][15:8];
        snapshots_3[6'h5] = _RANDOM[6'h1A][7:0];
        snapshots_3[6'h6] = _RANDOM[6'h1B][31:24];
        snapshots_3[6'h7] = _RANDOM[6'h1B][23:16];
        snapshots_3[6'h8] = _RANDOM[6'h1B][15:8];
        snapshots_3[6'h9] = _RANDOM[6'h1B][7:0];
        snapshots_3[6'hA] = _RANDOM[6'h1C][31:24];
        snapshots_3[6'hB] = _RANDOM[6'h1C][23:16];
        snapshots_3[6'hC] = _RANDOM[6'h1C][15:8];
        snapshots_3[6'hD] = _RANDOM[6'h1C][7:0];
        snapshots_3[6'hE] = _RANDOM[6'h1D][31:24];
        snapshots_3[6'hF] = _RANDOM[6'h1D][23:16];
        snapshots_3[6'h10] = _RANDOM[6'h1D][15:8];
        snapshots_3[6'h11] = _RANDOM[6'h1D][7:0];
        snapshots_3[6'h12] = _RANDOM[6'h1E][31:24];
        snapshots_3[6'h13] = _RANDOM[6'h1E][23:16];
        snapshots_3[6'h14] = _RANDOM[6'h1E][15:8];
        snapshots_3[6'h15] = _RANDOM[6'h1E][7:0];
        snapshots_3[6'h16] = _RANDOM[6'h1F][31:24];
        snapshots_3[6'h17] = _RANDOM[6'h1F][23:16];
        snapshots_3[6'h18] = _RANDOM[6'h1F][15:8];
        snapshots_3[6'h19] = _RANDOM[6'h1F][7:0];
        snapshots_3[6'h1A] = _RANDOM[6'h20][31:24];
        snapshots_3[6'h1B] = _RANDOM[6'h20][23:16];
        snapshots_3[6'h1C] = _RANDOM[6'h20][15:8];
        snapshots_3[6'h1D] = _RANDOM[6'h20][7:0];
        snapshots_3[6'h1E] = _RANDOM[6'h21][31:24];
        snapshots_3[6'h1F] = _RANDOM[6'h21][23:16];
        snapshots_3[6'h20] = _RANDOM[6'h21][15:8];
        snapshots_3[6'h21] = _RANDOM[6'h21][7:0];
        snptEnqPtr_flag = _RANDOM[6'h22][0];
        snptEnqPtr_value = _RANDOM[6'h22][2:1];
        snptDeqPtr_flag = _RANDOM[6'h22][3];
        snptDeqPtr_value = _RANDOM[6'h22][5:4];
        snptValids[2'h0] = _RANDOM[6'h22][9];
        snptValids[2'h1] = _RANDOM[6'h22][8];
        snptValids[2'h2] = _RANDOM[6'h22][7];
        snptValids[2'h3] = _RANDOM[6'h22][6];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        snptEnqPtr_flag = 1'h0;
        snptEnqPtr_value = 2'h0;
        snptDeqPtr_flag = 1'h0;
        snptDeqPtr_value = 2'h0;
        snptValids = '{1'h0, 1'h0, 1'h0, 1'h0};
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_snapshots_0 = snapshots_0;
  assign io_snapshots_1 = snapshots_1;
  assign io_snapshots_2 = snapshots_2;
  assign io_snapshots_3 = snapshots_3;
endmodule

