`timescale 1ns/1ps

module xs_bugcase_tb (
    input  logic        clk,
    input  logic        rst_n,

    input  logic        redirect_valid,
    input  logic        redirect_level,
    input  logic        redirect_robIdx_flag,
    input  logic [8:0]  redirect_robIdx_value,

    input  logic        rob_pendingPtr_flag,
    input  logic [8:0]  rob_pendingPtr_value,

    input  logic        req_valid,
    input  logic [8:0]  req_robIdx_value,
    input  logic [49:0] req_vaddr,
    input  logic [47:0] req_paddr,
    input  logic [15:0] req_mask,
    input  logic        req_nc,
    input  logic        req_mmio,

    input  logic        mmioOut_ready,
    input  logic        ncOut_ready,
    input  logic        uncache_req_ready,
    input  logic        uncache_idResp_valid,
    input  logic [6:0]  uncache_idResp_mid,
    input  logic [3:0]  uncache_idResp_sid,
    input  logic        uncache_resp_valid,
    input  logic [63:0] uncache_resp_data,
    input  logic        uncache_resp_denied,
    input  logic        uncache_resp_corrupt,

    output logic        flush,
    output logic        mmioSelect,
    output logic        slaveId_valid,
    output logic [3:0]  slaveId_bits,
    output logic        mmioOut_valid,
    output logic        ncOut_valid,
    output logic        uncache_req_valid,
    output logic [47:0] uncache_req_addr,
    output logic [7:0]  uncache_req_mask,
    output logic        exception_valid,
    output logic [63:0] mmioRawData_lqData,

    output logic        dbg_req_valid,
    output logic        dbg_slaveAccept,
    output logic [1:0]  dbg_uncacheState,
    output logic        dbg_needFlushReg,
    output logic [3:0]  dbg_slaveId
);
    UncacheEntryCase007 dut (
        .clock(clk),
        .reset(!rst_n),
        .redirect_valid(redirect_valid),
        .redirect_level(redirect_level),
        .redirect_robIdx_flag(redirect_robIdx_flag),
        .redirect_robIdx_value(redirect_robIdx_value),
        .rob_pendingPtr_flag(rob_pendingPtr_flag),
        .rob_pendingPtr_value(rob_pendingPtr_value),
        .req_valid(req_valid),
        .req_robIdx_value(req_robIdx_value),
        .req_vaddr(req_vaddr),
        .req_paddr(req_paddr),
        .req_mask(req_mask),
        .req_nc(req_nc),
        .req_mmio(req_mmio),
        .mmioOut_ready(mmioOut_ready),
        .ncOut_ready(ncOut_ready),
        .uncache_req_ready(uncache_req_ready),
        .uncache_idResp_valid(uncache_idResp_valid),
        .uncache_idResp_mid(uncache_idResp_mid),
        .uncache_idResp_sid(uncache_idResp_sid),
        .uncache_resp_valid(uncache_resp_valid),
        .uncache_resp_data(uncache_resp_data),
        .uncache_resp_denied(uncache_resp_denied),
        .uncache_resp_corrupt(uncache_resp_corrupt),
        .flush(flush),
        .mmioSelect(mmioSelect),
        .slaveId_valid(slaveId_valid),
        .slaveId_bits(slaveId_bits),
        .mmioOut_valid(mmioOut_valid),
        .ncOut_valid(ncOut_valid),
        .uncache_req_valid(uncache_req_valid),
        .uncache_req_addr(uncache_req_addr),
        .uncache_req_mask(uncache_req_mask),
        .exception_valid(exception_valid),
        .mmioRawData_lqData(mmioRawData_lqData),
        .dbg_req_valid(dbg_req_valid),
        .dbg_slaveAccept(dbg_slaveAccept),
        .dbg_uncacheState(dbg_uncacheState),
        .dbg_needFlushReg(dbg_needFlushReg),
        .dbg_slaveId(dbg_slaveId)
    );
endmodule
