`timescale 1ns/1ps

// Bugcase stub: drop xs_assert_v2 calls for standalone conversion/sim.
`ifndef xs_assert_v2
  `define xs_assert_v2(file, line)
`endif

module UncacheEntryCase007 (
    input  logic        clock,
    input  logic        reset,

    input  logic        redirect_valid,
    input  logic        redirect_level,
    input  logic        redirect_robIdx_flag,
    input  logic [8:0]  redirect_robIdx_value,

    input  logic        rob_pendingPtr_flag,
    input  logic [8:0]  rob_pendingPtr_value,

    input  logic        req_valid,
    input  logic [8:0]  req_robIdx_value,
    input  logic [49:0] req_vaddr,
    input  logic [47:0] req_paddr,
    input  logic [15:0] req_mask,
    input  logic        req_nc,
    input  logic        req_mmio,

    input  logic        mmioOut_ready,
    input  logic        ncOut_ready,
    input  logic        uncache_req_ready,
    input  logic        uncache_idResp_valid,
    input  logic [6:0]  uncache_idResp_mid,
    input  logic [3:0]  uncache_idResp_sid,
    input  logic        uncache_resp_valid,
    input  logic [63:0] uncache_resp_data,
    input  logic        uncache_resp_denied,
    input  logic        uncache_resp_corrupt,

    output logic        flush,
    output logic        mmioSelect,
    output logic        slaveId_valid,
    output logic [3:0]  slaveId_bits,
    output logic        mmioOut_valid,
    output logic        ncOut_valid,
    output logic        uncache_req_valid,
    output logic [47:0] uncache_req_addr,
    output logic [7:0]  uncache_req_mask,
    output logic        exception_valid,
    output logic [63:0] mmioRawData_lqData,

    output logic        dbg_req_valid,
    output logic        dbg_slaveAccept,
    output logic [1:0]  dbg_uncacheState,
    output logic        dbg_needFlushReg,
    output logic [3:0]  dbg_slaveId
);

    UncacheEntry_5 dut (
        .clock(clock),
        .reset(reset),
        .io_redirect_valid(redirect_valid),
        .io_redirect_bits_level(redirect_level),
        .io_redirect_bits_robIdx_flag(redirect_robIdx_flag),
        .io_redirect_bits_robIdx_value(redirect_robIdx_value),
        .io_flush(flush),
        .io_rob_pendingPtr_flag(rob_pendingPtr_flag),
        .io_rob_pendingPtr_value(rob_pendingPtr_value),
        .io_mmioSelect(mmioSelect),
        .io_slaveId_valid(slaveId_valid),
        .io_slaveId_bits(slaveId_bits),
        .io_req_valid(req_valid),
        .io_req_bits_uop_pc('0),
        .io_req_bits_uop_exceptionVec_0('0),
        .io_req_bits_uop_exceptionVec_1('0),
        .io_req_bits_uop_exceptionVec_2('0),
        .io_req_bits_uop_exceptionVec_3('0),
        .io_req_bits_uop_exceptionVec_4('0),
        .io_req_bits_uop_exceptionVec_6('0),
        .io_req_bits_uop_exceptionVec_7('0),
        .io_req_bits_uop_exceptionVec_8('0),
        .io_req_bits_uop_exceptionVec_9('0),
        .io_req_bits_uop_exceptionVec_10('0),
        .io_req_bits_uop_exceptionVec_11('0),
        .io_req_bits_uop_exceptionVec_12('0),
        .io_req_bits_uop_exceptionVec_13('0),
        .io_req_bits_uop_exceptionVec_14('0),
        .io_req_bits_uop_exceptionVec_15('0),
        .io_req_bits_uop_exceptionVec_16('0),
        .io_req_bits_uop_exceptionVec_17('0),
        .io_req_bits_uop_exceptionVec_18('0),
        .io_req_bits_uop_exceptionVec_20('0),
        .io_req_bits_uop_exceptionVec_21('0),
        .io_req_bits_uop_exceptionVec_22('0),
        .io_req_bits_uop_exceptionVec_23('0),
        .io_req_bits_uop_trigger('0),
        .io_req_bits_uop_isRVC('0),
        .io_req_bits_uop_ftqPtr_flag('0),
        .io_req_bits_uop_ftqPtr_value('0),
        .io_req_bits_uop_ftqOffset('0),
        .io_req_bits_uop_fuOpType('0),
        .io_req_bits_uop_rfWen('0),
        .io_req_bits_uop_fpWen('0),
        .io_req_bits_uop_vpu_vstart('0),
        .io_req_bits_uop_vpu_veew('0),
        .io_req_bits_uop_uopIdx('0),
        .io_req_bits_uop_pdest('0),
        .io_req_bits_uop_robIdx_flag(1'b0),
        .io_req_bits_uop_robIdx_value(req_robIdx_value),
        .io_req_bits_uop_perfDebugInfo_eliminatedMove('0),
        .io_req_bits_uop_perfDebugInfo_renameTime('0),
        .io_req_bits_uop_perfDebugInfo_dispatchTime('0),
        .io_req_bits_uop_perfDebugInfo_enqRsTime('0),
        .io_req_bits_uop_perfDebugInfo_selectTime('0),
        .io_req_bits_uop_perfDebugInfo_issueTime('0),
        .io_req_bits_uop_perfDebugInfo_runahead_checkpoint_id('0),
        .io_req_bits_uop_perfDebugInfo_tlbFirstReqTime('0),
        .io_req_bits_uop_perfDebugInfo_tlbRespTime('0),
        .io_req_bits_uop_debug_seqNum_seqNum('0),
        .io_req_bits_uop_debug_seqNum_uopIdx('0),
        .io_req_bits_uop_storeSetHit('0),
        .io_req_bits_uop_waitForRobIdx_flag('0),
        .io_req_bits_uop_waitForRobIdx_value('0),
        .io_req_bits_uop_loadWaitBit('0),
        .io_req_bits_uop_loadWaitStrict('0),
        .io_req_bits_uop_lqIdx_flag('0),
        .io_req_bits_uop_lqIdx_value('0),
        .io_req_bits_uop_sqIdx_flag('0),
        .io_req_bits_uop_sqIdx_value('0),
        .io_req_bits_vaddr(req_vaddr),
        .io_req_bits_fullva({14'h0, req_vaddr}),
        .io_req_bits_paddr(req_paddr),
        .io_req_bits_gpaddr({16'h0, req_paddr}),
        .io_req_bits_mask(req_mask),
        .io_req_bits_nc(req_nc),
        .io_req_bits_mmio(req_mmio),
        .io_req_bits_memBackTypeMM(1'b0),
        .io_req_bits_isHyper(1'b0),
        .io_req_bits_isForVSnonLeafPTE(1'b0),
        .io_req_bits_isvec(1'b0),
        .io_req_bits_is128bit(1'b0),
        .io_req_bits_vecActive(1'b0),
        .io_req_bits_schedIndex('0),
        .io_mmioOut_ready(mmioOut_ready),
        .io_mmioOut_valid(mmioOut_valid),
        .io_mmioOut_bits_uop_pc(),
        .io_mmioOut_bits_uop_exceptionVec_0(),
        .io_mmioOut_bits_uop_exceptionVec_1(),
        .io_mmioOut_bits_uop_exceptionVec_2(),
        .io_mmioOut_bits_uop_exceptionVec_3(),
        .io_mmioOut_bits_uop_exceptionVec_4(),
        .io_mmioOut_bits_uop_exceptionVec_5(),
        .io_mmioOut_bits_uop_exceptionVec_6(),
        .io_mmioOut_bits_uop_exceptionVec_7(),
        .io_mmioOut_bits_uop_exceptionVec_8(),
        .io_mmioOut_bits_uop_exceptionVec_9(),
        .io_mmioOut_bits_uop_exceptionVec_10(),
        .io_mmioOut_bits_uop_exceptionVec_11(),
        .io_mmioOut_bits_uop_exceptionVec_12(),
        .io_mmioOut_bits_uop_exceptionVec_13(),
        .io_mmioOut_bits_uop_exceptionVec_14(),
        .io_mmioOut_bits_uop_exceptionVec_15(),
        .io_mmioOut_bits_uop_exceptionVec_16(),
        .io_mmioOut_bits_uop_exceptionVec_17(),
        .io_mmioOut_bits_uop_exceptionVec_18(),
        .io_mmioOut_bits_uop_exceptionVec_19(),
        .io_mmioOut_bits_uop_exceptionVec_20(),
        .io_mmioOut_bits_uop_exceptionVec_21(),
        .io_mmioOut_bits_uop_exceptionVec_22(),
        .io_mmioOut_bits_uop_exceptionVec_23(),
        .io_mmioOut_bits_uop_trigger(),
        .io_mmioOut_bits_uop_isRVC(),
        .io_mmioOut_bits_uop_ftqPtr_flag(),
        .io_mmioOut_bits_uop_ftqPtr_value(),
        .io_mmioOut_bits_uop_ftqOffset(),
        .io_mmioOut_bits_uop_fuOpType(),
        .io_mmioOut_bits_uop_rfWen(),
        .io_mmioOut_bits_uop_fpWen(),
        .io_mmioOut_bits_uop_vpu_vstart(),
        .io_mmioOut_bits_uop_vpu_veew(),
        .io_mmioOut_bits_uop_uopIdx(),
        .io_mmioOut_bits_uop_pdest(),
        .io_mmioOut_bits_uop_robIdx_flag(),
        .io_mmioOut_bits_uop_robIdx_value(),
        .io_mmioOut_bits_uop_perfDebugInfo_eliminatedMove(),
        .io_mmioOut_bits_uop_perfDebugInfo_renameTime(),
        .io_mmioOut_bits_uop_perfDebugInfo_dispatchTime(),
        .io_mmioOut_bits_uop_perfDebugInfo_enqRsTime(),
        .io_mmioOut_bits_uop_perfDebugInfo_selectTime(),
        .io_mmioOut_bits_uop_perfDebugInfo_issueTime(),
        .io_mmioOut_bits_uop_perfDebugInfo_runahead_checkpoint_id(),
        .io_mmioOut_bits_uop_perfDebugInfo_tlbFirstReqTime(),
        .io_mmioOut_bits_uop_perfDebugInfo_tlbRespTime(),
        .io_mmioOut_bits_uop_debug_seqNum_seqNum(),
        .io_mmioOut_bits_uop_debug_seqNum_uopIdx(),
        .io_mmioOut_bits_uop_storeSetHit(),
        .io_mmioOut_bits_uop_waitForRobIdx_flag(),
        .io_mmioOut_bits_uop_waitForRobIdx_value(),
        .io_mmioOut_bits_uop_loadWaitBit(),
        .io_mmioOut_bits_uop_loadWaitStrict(),
        .io_mmioOut_bits_uop_lqIdx_flag(),
        .io_mmioOut_bits_uop_lqIdx_value(),
        .io_mmioOut_bits_uop_sqIdx_flag(),
        .io_mmioOut_bits_uop_sqIdx_value(),
        .io_mmioOut_bits_debug_paddr(),
        .io_mmioOut_bits_debug_vaddr(),
        .io_mmioRawData_lqData(mmioRawData_lqData),
        .io_mmioRawData_uop_fuOpType(),
        .io_mmioRawData_uop_fpWen(),
        .io_mmioRawData_addrOffset(),
        .io_ncOut_ready(ncOut_ready),
        .io_ncOut_valid(ncOut_valid),
        .io_ncOut_bits_uop_pc(),
        .io_ncOut_bits_uop_exceptionVec_0(),
        .io_ncOut_bits_uop_exceptionVec_1(),
        .io_ncOut_bits_uop_exceptionVec_2(),
        .io_ncOut_bits_uop_exceptionVec_4(),
        .io_ncOut_bits_uop_exceptionVec_6(),
        .io_ncOut_bits_uop_exceptionVec_7(),
        .io_ncOut_bits_uop_exceptionVec_8(),
        .io_ncOut_bits_uop_exceptionVec_9(),
        .io_ncOut_bits_uop_exceptionVec_10(),
        .io_ncOut_bits_uop_exceptionVec_11(),
        .io_ncOut_bits_uop_exceptionVec_12(),
        .io_ncOut_bits_uop_exceptionVec_14(),
        .io_ncOut_bits_uop_exceptionVec_15(),
        .io_ncOut_bits_uop_exceptionVec_16(),
        .io_ncOut_bits_uop_exceptionVec_17(),
        .io_ncOut_bits_uop_exceptionVec_18(),
        .io_ncOut_bits_uop_exceptionVec_19(),
        .io_ncOut_bits_uop_exceptionVec_20(),
        .io_ncOut_bits_uop_exceptionVec_22(),
        .io_ncOut_bits_uop_exceptionVec_23(),
        .io_ncOut_bits_uop_isRVC(),
        .io_ncOut_bits_uop_ftqPtr_flag(),
        .io_ncOut_bits_uop_ftqPtr_value(),
        .io_ncOut_bits_uop_ftqOffset(),
        .io_ncOut_bits_uop_fuOpType(),
        .io_ncOut_bits_uop_rfWen(),
        .io_ncOut_bits_uop_fpWen(),
        .io_ncOut_bits_uop_vpu_vstart(),
        .io_ncOut_bits_uop_vpu_veew(),
        .io_ncOut_bits_uop_uopIdx(),
        .io_ncOut_bits_uop_pdest(),
        .io_ncOut_bits_uop_robIdx_flag(),
        .io_ncOut_bits_uop_robIdx_value(),
        .io_ncOut_bits_uop_perfDebugInfo_eliminatedMove(),
        .io_ncOut_bits_uop_perfDebugInfo_renameTime(),
        .io_ncOut_bits_uop_perfDebugInfo_dispatchTime(),
        .io_ncOut_bits_uop_perfDebugInfo_enqRsTime(),
        .io_ncOut_bits_uop_perfDebugInfo_selectTime(),
        .io_ncOut_bits_uop_perfDebugInfo_issueTime(),
        .io_ncOut_bits_uop_perfDebugInfo_runahead_checkpoint_id(),
        .io_ncOut_bits_uop_perfDebugInfo_tlbFirstReqTime(),
        .io_ncOut_bits_uop_perfDebugInfo_tlbRespTime(),
        .io_ncOut_bits_uop_debug_seqNum_seqNum(),
        .io_ncOut_bits_uop_debug_seqNum_uopIdx(),
        .io_ncOut_bits_uop_storeSetHit(),
        .io_ncOut_bits_uop_waitForRobIdx_flag(),
        .io_ncOut_bits_uop_waitForRobIdx_value(),
        .io_ncOut_bits_uop_loadWaitBit(),
        .io_ncOut_bits_uop_loadWaitStrict(),
        .io_ncOut_bits_uop_lqIdx_flag(),
        .io_ncOut_bits_uop_lqIdx_value(),
        .io_ncOut_bits_uop_sqIdx_flag(),
        .io_ncOut_bits_uop_sqIdx_value(),
        .io_ncOut_bits_vaddr(),
        .io_ncOut_bits_paddr(),
        .io_ncOut_bits_data(),
        .io_ncOut_bits_isvec(),
        .io_ncOut_bits_is128bit(),
        .io_ncOut_bits_vecActive(),
        .io_ncOut_bits_schedIndex(),
        .io_uncache_req_ready(uncache_req_ready),
        .io_uncache_req_valid(uncache_req_valid),
        .io_uncache_req_bits_robIdx_flag(),
        .io_uncache_req_bits_robIdx_value(),
        .io_uncache_req_bits_addr(uncache_req_addr),
        .io_uncache_req_bits_vaddr(),
        .io_uncache_req_bits_mask(uncache_req_mask),
        .io_uncache_req_bits_nc(),
        .io_uncache_req_bits_memBackTypeMM(),
        .io_uncache_idResp_valid(uncache_idResp_valid),
        .io_uncache_idResp_bits_mid(uncache_idResp_mid),
        .io_uncache_idResp_bits_sid(uncache_idResp_sid),
        .io_uncache_resp_valid(uncache_resp_valid),
        .io_uncache_resp_bits_data(uncache_resp_data),
        .io_uncache_resp_bits_denied(uncache_resp_denied),
        .io_uncache_resp_bits_corrupt(uncache_resp_corrupt),
        .io_exception_valid(exception_valid),
        .io_exception_bits_uop_exceptionVec_3(),
        .io_exception_bits_uop_exceptionVec_4(),
        .io_exception_bits_uop_exceptionVec_5(),
        .io_exception_bits_uop_exceptionVec_13(),
        .io_exception_bits_uop_exceptionVec_19(),
        .io_exception_bits_uop_exceptionVec_21(),
        .io_exception_bits_uop_robIdx_flag(),
        .io_exception_bits_uop_robIdx_value(),
        .io_exception_bits_uop_lqIdx_flag(),
        .io_exception_bits_uop_lqIdx_value(),
        .io_exception_bits_fullva(),
        .io_exception_bits_gpaddr(),
        .io_exception_bits_isHyper(),
        .io_exception_bits_isForVSnonLeafPTE()
    );

    assign dbg_req_valid = dut.req_valid;
    assign dbg_slaveAccept = dut.slaveAccept;
    assign dbg_uncacheState = dut.uncacheState;
    assign dbg_needFlushReg = dut.needFlushReg;
    assign dbg_slaveId = dut.slaveId;
endmodule
